"""
Django settings for core project.
Generated by 'django-admin startproject' using Django 6.0.2.
"""

from pathlib import Path
import os
import sys

BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / ".env", override=False)
except ImportError:
    pass


def _env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    normalized = value.strip().lower()
    if normalized in {"true", "1", "yes", "on"}:
        return True
    if normalized in {"false", "0", "no", "off"}:
        return False
    raise ValueError(f"Environment variable {name} must be a boolean value")


def _require_env(name, default=None, dev_default=None):
    """
    Get environment variable with three modes:
    - If var is set → always use that
    - If DEBUG=True and var not set → use dev_default (development convenience)
    - If DEBUG=False and var not set → use default OR crash if default is None (production strict)
    """
    val = os.environ.get(name)
    if val is not None and val != "":
        return val
    if DEBUG and dev_default is not None:
        return dev_default
    if default is None:
        print(f"[FATAL] Required environment variable '{name}' is not set. "
              f"Please configure it via environment or .env file.")
        sys.exit(1)
    return default


# ===============================
# SECURITY
# ===============================

DEBUG = _env_bool("DEBUG", default=False)
GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID", "")

SECRET_KEY = _require_env(
    "SECRET_KEY",
    dev_default="django-insecure-dev-change-me-please-123456789"
)
if not DEBUG and len(SECRET_KEY) < 50:
    raise ValueError("Production SECRET_KEY must be at least 50 characters")

# Production: strict list. Dev: allow localhost + wildcard for flexibility.
_ALLOWED_HOSTS_DEFAULT = (
    "imronm.pythonanywhere.com,localhost,127.0.0.1"
    if DEBUG else
    "imronm.pythonanywhere.com"
)
ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get("ALLOWED_HOSTS", _ALLOWED_HOSTS_DEFAULT).split(",")
    if h.strip()
]
if not DEBUG and (not ALLOWED_HOSTS or "*" in ALLOWED_HOSTS):
    raise ValueError("Production ALLOWED_HOSTS must be a non-empty explicit host list")


# ===============================
# APPLICATIONS
# ===============================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "corsheaders",
    "django_ratelimit",  # Rate limiting untuk perlindungan DDoS

    "ninja",
    "ninja_extra",
    "ninja_jwt",

    "users",
    "content",
    "learning",
]

AUTH_USER_MODEL = "users.User"


# ===============================
# MIDDLEWARE
# ===============================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",

    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"


# ===============================
# CORS
# ===============================

# NEVER allow all origins in production. Use explicit whitelist.
_CORS_DEFAULT = (
    "http://localhost:3000,http://127.0.0.1:3000,http://localhost:8000"
    if DEBUG else
    "https://jbook-five.vercel.app,https://imronm.pythonanywhere.com"
)
_CORS_ORIGINS = [
    o.strip() for o in os.environ.get("CORS_ALLOWED_ORIGINS", _CORS_DEFAULT).split(",")
    if o.strip()
]

if DEBUG and not _CORS_ORIGINS:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = _CORS_ORIGINS
if not DEBUG and (not _CORS_ORIGINS or "*" in _CORS_ORIGINS):
    raise ValueError("Production CORS_ALLOWED_ORIGINS must be an explicit origin allowlist")

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get(
        "CSRF_TRUSTED_ORIGINS",
        "http://localhost:3000,https://jbook-five.vercel.app"
    ).split(",")
    if o.strip()
]


# ===============================
# TEMPLATES
# ===============================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "core" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]




WSGI_APPLICATION = "core.wsgi.application"


# ===============================
# DATABASE
# ===============================

DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
if DATABASE_URL:
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=int(os.environ.get("DB_CONN_MAX_AGE", "600")),
            ssl_require=not DEBUG,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
    if not DEBUG:
        print("[WARNING] DATABASE_URL is unset; production is using SQLite")


# ===============================
# PASSWORD VALIDATION
# ===============================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ===============================
# INTERNATIONALIZATION
# ===============================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ===============================
# STATIC FILES
# ===============================

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# ===============================
# MEDIA FILES (Uploads)
# ===============================

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "mediafiles"


# ===============================
# EMAIL CONFIG
# ===============================

# In development/dev mode, default to console backend so no credentials needed.
if DEBUG:
    EMAIL_BACKEND = os.environ.get(
        "EMAIL_BACKEND",
        "django.core.mail.backends.console.EmailBackend"
    )
else:
    EMAIL_BACKEND = os.environ.get(
        "EMAIL_BACKEND",
        "django.core.mail.backends.smtp.EmailBackend"
    )

EMAIL_HOST = _require_env("EMAIL_HOST", dev_default="smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True") == "True"

# Credentials: NEVER hardcode. Production must set env, dev can be empty (console backend).
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_CONFIGURED = bool(EMAIL_HOST_USER and EMAIL_HOST_PASSWORD)
if not DEBUG and EMAIL_BACKEND.endswith("smtp.EmailBackend") and not EMAIL_CONFIGURED:
    print("[WARNING] SMTP credentials are missing; password-reset emails are disabled")
if not DEBUG and not GOOGLE_CLIENT_ID:
    print("[WARNING] GOOGLE_CLIENT_ID is missing; Google sign-in is disabled")

DEFAULT_FROM_EMAIL = (
    os.environ.get("DEFAULT_FROM_EMAIL")
    or EMAIL_HOST_USER
    or "noreply@jbook.local"
)

FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:3000" if DEBUG else "https://jbook-five.vercel.app")
BACKEND_URL = os.environ.get("BACKEND_URL", "http://localhost:8000" if DEBUG else "https://imronm.pythonanywhere.com")


# ===============================
# CACHE (OTP RESET)
# ===============================

# Cache backend selection
# Default to a file-based cache which is "shared" and satisfies django-ratelimit checks.
# You can override via the CACHE_BACKEND environment variable (e.g., set to 'locmem' or 'filebased').
CACHE_BACKEND = os.environ.get('CACHE_BACKEND', 'filebased')

if CACHE_BACKEND == 'filebased':
    CACHE_DIR = os.environ.get('CACHE_DIR') or str(BASE_DIR / 'django_cache')
    os.makedirs(CACHE_DIR, exist_ok=True)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
            'LOCATION': CACHE_DIR,
        }
    }
elif CACHE_BACKEND == 'locmem':
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }
else:
    # Fallback: try filebased if unknown value provided
    CACHE_DIR = str(BASE_DIR / 'django_cache')
    os.makedirs(CACHE_DIR, exist_ok=True)
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
            'LOCATION': CACHE_DIR,
        }
    }

SILENCED_SYSTEM_CHECKS = ['django_ratelimit.E003', 'django_ratelimit.W001']



# ===============================
# AUTHENTICATION & JWT
# ===============================

from datetime import timedelta

# Access token: short-lived (15 minutes is industry standard)
# Refresh token: long-lived (7 days) with rotation + blacklist
NINJA_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.environ.get('JWT_ACCESS_MINUTES', 15))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.environ.get('JWT_REFRESH_DAYS', 7))),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUDIENCE': 'jbook',
    'ISSUER': 'jbook',
    'JWK_URL': os.environ.get('JWK_URL', None),
}

# Session settings
SESSION_COOKIE_AGE = 60 * 60 * 24 * int(os.environ.get('SESSION_DAYS', 7))  # 7 days
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Cookie security (production-only hardening)
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", default=True)
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False)
    SECURE_HSTS_PRELOAD = _env_bool("SECURE_HSTS_PRELOAD", default=False)
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = 'Lax'

# ===============================
# LOGGING
# ===============================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        # You can add custom loggers for your apps here
        # 'users': {
        #     'handlers': ['console', 'file'],
        #     'level': 'DEBUG',
        #     'propagate': True,
        # },
    },
}