import os
import django
import sys

# Setup Django
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.append(BASE_DIR)
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings')
django.setup()

from content.models import Vocab

# Standard N5 dictionary (Partial list for sync, focusing on cleaning meanings)
# Mapping: reading -> {word: meaning}
N5_REF = {
    "あう": {"word": "会う", "meaning": "bertemu, berjumpa"},
    "あおい": {"word": "青い", "meaning": "biru"},
    "あかい": {"word": "赤い", "meaning": "merah"},
    "あかるい": {"word": "明るい", "meaning": "terang, cerah"},
    "あき": {"word": "秋", "meaning": "musim gugur"},
    "あく": {"word": "開く", "meaning": "membuka, terbuka"},
    "あける": {"word": "開ける", "meaning": "membuka (jendela, pintu)"},
    "あげる": {"word": "上げる", "meaning": "memberi, menaikkan"},
    "あさ": {"word": "朝", "meaning": "pagi"},
    "あさごはん": {"word": "朝御飯", "meaning": "sarapan"},
    "あさって": {"word": "あさって", "meaning": "lusa"},
    "あし": {"word": "足", "meaning": "kaki"},
    "あした": {"word": "明日", "meaning": "besok"},
    "あそこ": {"word": "あそこ", "meaning": "di sana (jauh)"},
    "あそぶ": {"word": "遊ぶ", "meaning": "bermain"},
    "あたたかい": {"word": "暖かい", "meaning": "hangat"},
    "あたま": {"word": "頭", "meaning": "kepala"},
    "あたらしい": {"word": "新しい", "meaning": "baru"},
    "あちら": {"word": "あちら", "meaning": "di sana (sopan)"},
    "あつい": {"word": "暑い", "meaning": "panas (cuaca)"},
    "あっち": {"word": "あっち", "meaning": "di sana (informal)"},
    "あと": {"word": "後", "meaning": "setelah, nanti"},
    "あなた": {"word": "あなた", "meaning": "kamu, anda"},
    "あに": {"word": "兄", "meaning": "kakak laki-laki (sendiri)"},
    "あね": {"word": "姉", "meaning": "kakak perempuan (sendiri)"},
    "あぶない": {"word": "危ない", "meaning": "berbahaya"},
    "あまい": {"word": "甘い", "meaning": "manis"},
    "あめ": {"word": "雨", "meaning": "hujan"},
    "あらう": {"word": "洗う", "meaning": "mencuci"},
    "あるく": {"word": "歩く", "meaning": "berjalan"},
    "いい": {"word": "いい", "meaning": "bagus, baik"},
    "いう": {"word": "言う", "meaning": "mengatakan, berucap"},
    "いえ": {"word": "家", "meaning": "rumah"},
    "いく": {"word": "行く", "meaning": "pergi"},
    "いくら": {"word": "いくら", "meaning": "berapa (harga)"},
    "いけ": {"word": "池", "meaning": "kolam"},
    "いしゃ": {"word": "医者", "meaning": "dokter"},
    "いす": {"word": "椅子", "meaning": "kursi"},
    "いそがしい": {"word": "忙しい", "meaning": "sibuk"},
    "いたい": {"word": "痛い", "meaning": "sakit, nyeri"},
    "いちにち": {"word": "一日", "meaning": "satu hari, tanggal 1"},
    "いちばん": {"word": "一番", "meaning": "paling, nomor satu"},
    "いつ": {"word": "いつ", "meaning": "kapan"},
    "いつか": {"word": "五日", "meaning": "tanggal 5, lima hari"},
    "いっしょ": {"word": "一緒", "meaning": "bersama"},
    "いつつ": {"word": "五つ", "meaning": "lima buah"},
    "いつも": {"word": "いつも", "meaning": "selalu"},
    "いぬ": {"word": "犬", "meaning": "anjing"},
    "いま": {"word": "今", "meaning": "sekarang"},
    "いみ": {"word": "意味", "meaning": "arti, makna"},
    "いもうと": {"word": "妹", "meaning": "adik perempuan (sendiri)"},
    "いりぐち": {"word": "入口", "meaning": "pintu masuk"},
    "いる": {"word": "居る", "meaning": "ada (makhluk hidup)"},
    "いれる": {"word": "入れる", "meaning": "memasukkan"},
    "いろ": {"word": "色", "meaning": "warna"},
    "いろいろ": {"word": "色々", "meaning": "bermacam-macam"},
    "うえ": {"word": "上", "meaning": "atas"},
    "うしろ": {"word": "後ろ", "meaning": "belakang"},
    "うすい": {"word": "薄い", "meaning": "tipis, encer, hambar"},
    "うた": {"word": "歌", "meaning": "lagu"},
    "うたう": {"word": "歌う", "meaning": "menyanyi"},
    "うみ": {"word": "海", "meaning": "laut"},
    "うる": {"word": "売る", "meaning": "menjual"},
    "うるさい": {"word": "うるさい", "meaning": "berisik, gaduh"},
    "うわぎ": {"word": "上着", "meaning": "jaket, jas"},
    "え": {"word": "絵", "meaning": "gambar, lukisan"},
    "えいが": {"word": "映画", "meaning": "film"},
    "えいがかん": {"word": "映画館", "meaning": "bioskop"},
    "えいご": {"word": "英語", "meaning": "bahasa Inggris"},
    "えき": {"word": "駅", "meaning": "stasiun"},
    "えんぴつ": {"word": "鉛筆", "meaning": "pensil"},
    "おいしい": {"word": "美味しい", "meaning": "enak, lezat"},
    "おおい": {"word": "多い", "meaning": "banyak (jumlah)"},
    "おおきい": {"word": "大きい", "meaning": "besar"},
    "おおぜい": {"word": "大勢", "meaning": "banyak orang"},
    "おかあさん": {"word": "お母さん", "meaning": "ibu (orang lain/panggilan)"},
    "おかし": {"word": "お菓子", "meaning": "kue, cemilan"},
    "おかね": {"word": "お金", "meaning": "uang"},
    "おきる": {"word": "起きる", "meaning": "bangun tidur"},
    "おく": {"word": "置く", "meaning": "meletakkan"},
    "おくさん": {"word": "奥さん", "meaning": "istri (orang lain)"},
    "おさけ": {"word": "お酒", "meaning": "sake, minuman keras"},
    "おさら": {"word": "お皿", "meaning": "piring"},
    "おじいさん": {"word": "おじいさん", "meaning": "kakek"},
    "おしえる": {"word": "教える", "meaning": "mengajar, memberi tahu"},
    "おじさん": {"word": "おじさん", "meaning": "paman"},
    "おす": {"word": "押す", "meaning": "mendorong, menekan"},
    "おそい": {"word": "遅い", "meaning": "lambat, terlambat"},
    "おちゃ": {"word": "お茶", "meaning": "teh hijau"},
    "おてあらい": {"word": "お手洗い", "meaning": "toilet, kamar kecil"},
    "おとうさん": {"word": "お父さん", "meaning": "ayah (orang lain/panggilan)"},
    "おとうと": {"word": "弟", "meaning": "adik laki-laki (sendiri)"},
    "おとこ": {"word": "男", "meaning": "laki-laki"},
    "おとこのこ": {"word": "男の子", "meaning": "anak laki-laki"},
    "おととい": {"word": "一昨日", "meaning": "dua hari yang lalu"},
    "おととし": {"word": "一昨年", "meaning": "dua tahun yang lalu"},
    "おとな": {"word": "大人", "meaning": "dewasa"},
    "おなか": {"word": "お腹", "meaning": "perut"},
    "おなじ": {"word": "同じ", "meaning": "sama"},
    "おねえさん": {"word": "お姉さん", "meaning": "kakak perempuan (orang lain/panggilan)"},
    "おばあさん": {"word": "おばあさん", "meaning": "nenek"},
    "おばさん": {"word": "おばさん", "meaning": "bibi"},
    "おふろ": {"word": "お風呂", "meaning": "bak mandi Jepang"},
    "おべんとう": {"word": "お弁当", "meaning": "bekal makan (bento)"},
    "おぼえる": {"word": "覚える", "meaning": "mengingat, menghafal"},
    "おもしろい": {"word": "面白い", "meaning": "menarik, lucu"},
    "およぐ": {"word": "泳ぐ", "meaning": "berenang"},
    "おりる": {"word": "降りる", "meaning": "turun (kendaraan)"},
    "おわる": {"word": "終わる", "meaning": "selesai, berakhir"},
    "おんがく": {"word": "音楽", "meaning": "musik"},
    "おんな": {"word": "女", "meaning": "perempuan"},
    "おんなのこ": {"word": "女の子", "meaning": "anak perempuan"},
    "かいもの": {"word": "買い物", "meaning": "belanja"},
    "かう": {"word": "買う", "meaning": "membeli"},
    "かえす": {"word": "返す", "meaning": "mengembalikan"},
    "かえる": {"word": "帰る", "meaning": "pulang"},
    "かかる": {"word": "かかる", "meaning": "memerlukan (waktu/biaya)"},
    "かぎ": {"word": "鍵", "meaning": "kunci"},
    "かく": {"word": "書く", "meaning": "menulis"},
    "がくせい": {"word": "学生", "meaning": "siswa, mahasiswa"},
    "かさ": {"word": "傘", "meaning": "payung"},
    "かす": {"word": "貸す", "meaning": "meminjamkan"},
    "かぜ": {"word": "風", "meaning": "angin"},
    "かぞく": {"word": "家族", "meaning": "keluarga"},
    "かたかな": {"word": "カタカナ", "meaning": "huruf Katakana"},
    "かた": {"word": "方", "meaning": "cara, orang (sopan)"},
    "かな": {"word": "仮名", "meaning": "huruf Kana (Hiragana/Katakana)"},
    "かなしい": {"word": "悲しい", "meaning": "sedih"},
    "からい": {"word": "辛い", "meaning": "pedas"},
    "からだ": {"word": "体", "meaning": "tubuh, badan"},
    "かりる": {"word": "借りる", "meaning": "meminjam"},
    "かるい": {"word": "軽い", "meaning": "ringan"},
    "かれ": {"word": "彼", "meaning": "dia (laki-laki)"},
    "かわ": {"word": "川", "meaning": "sungai"},
    "かわいい": {"word": "可愛い", "meaning": "lucu, imut"},
    "かんじ": {"word": "漢字", "meaning": "huruf Kanji"},
    "き": {"word": "木", "meaning": "pohon"},
    "きいろい": {"word": "黄色い", "meaning": "kuning"},
    "きえる": {"word": "消える", "meaning": "padam, hilang"},
    "きく": {"word": "聞く", "meaning": "mendengar, bertanya"},
    "きた": {"word": "北", "meaning": "utara"},
    "きたない": {"word": "汚い", "meaning": "kotor"},
    "きっさてん": {"word": "喫茶店", "meaning": "kedai kopi, cafe"},
    "きって": {"word": "切手", "meaning": "perangko"},
    "きっぷ": {"word": "切符", "meaning": "tiket"},
    "きのう": {"word": "昨日", "meaning": "kemarin"},
    "ぎゅうにゅう": {"word": "牛乳", "meaning": "susu sapi"},
    "きょう": {"word": "今日", "meaning": "hari ini"},
    "きょうしつ": {"word": "教室", "meaning": "ruang kelas"},
    "きょうだい": {"word": "兄弟", "meaning": "saudara (sekandung)"},
    "きょねん": {"word": "去年", "meaning": "tahun lalu"},
    "きらい": {"word": "嫌い", "meaning": "benci, tidak suka"},
    "きる": {"word": "着る", "meaning": "memakai (baju)"},
    "きれい": {"word": "綺麗", "meaning": "cantik, bersih, indah"},
    "ぎんこう": {"word": "銀行", "meaning": "bank"},
    "くすり": {"word": "薬", "meaning": "obat"},
    "ください": {"word": "下さい", "meaning": "tolong, silakan"},
    "くだもの": {"word": "果物", "meaning": "buah-buahan"},
    "くち": {"word": "口", "meaning": "mulut"},
    "くつ": {"word": "靴", "meaning": "sepatu"},
    "くつした": {"word": "靴下", "meaning": "kaos kaki"},
    "くに": {"word": "国", "meaning": "negara"},
    "くもり": {"word": "曇り", "meaning": "berawan, mendung"},
    "くらい": {"word": "暗い", "meaning": "gelap"},
    "くるま": {"word": "車", "meaning": "mobil, kendaraan"},
    "くろい": {"word": "黒い", "meaning": "hitam"},
    "けいかん": {"word": "警官", "meaning": "polisi"},
    "けさ": {"word": "今朝", "meaning": "pagi ini"},
    "けす": {"word": "消す", "meaning": "mematikan, menghapus"},
    "けっこん": {"word": "結婚", "meaning": "menikah"},
    "げんき": {"word": "元気", "meaning": "sehat, bersemangat"},
    "こうえん": {"word": "公園", "meaning": "taman"},
    "こうばん": {"word": "交番", "meaning": "pos polisi"},
    "こえ": {"word": "声", "meaning": "suara"},
    "ここ": {"word": "ここ", "meaning": "di sini"},
    "ごご": {"word": "午後", "meaning": "siang (PM)"},
    "ごぜん": {"word": "午前", "meaning": "pagi (AM)"},
    "こたえる": {"word": "答える", "meaning": "menjawab"},
    "こちら": {"word": "こちら", "meaning": "di sini (sopan)"},
    "こっち": {"word": "こっち", "meaning": "di sini (informal)"},
    "こども": {"word": "子供", "meaning": "anak-anak"},
    "この": {"word": "この", "meaning": "ini (kata tunjuk)"},
    "ごはん": {"word": "ご飯", "meaning": "nasi, makan"},
    "こまる": {"word": "困る", "meaning": "susah, kesulitan"},
    "これ": {"word": "これ", "meaning": "ini (kata ganti)"},
    "こんげつ": {"word": "今月", "meaning": "bulan ini"},
    "こんしゅう": {"word": "今週", "meaning": "minggu ini"},
    "こんばん": {"word": "今晩", "meaning": "malam ini"},
    "さあ": {"word": "さあ", "meaning": "ayo, mari"},
    "さかな": {"word": "魚", "meaning": "ikan"},
    "さき": {"word": "先", "meaning": "tadi, ujung, depan"},
    "さく": {"word": "咲く", "meaning": "mekar"},
    "さくぶん": {"word": "作文", "meaning": "karangan"},
    "さし": {"word": "差し", "meaning": "penggaris"},
    "ざっし": {"word": "雑誌", "meaning": "majalah"},
    "さとう": {"word": "砂糖", "meaning": "gula"},
    "さむい": {"word": "寒い", "meaning": "dingin (cuaca)"},
    "さようなら": {"word": "さようなら", "meaning": "selamat tinggal"},
    "さんぽ": {"word": "散歩", "meaning": "jalan-jalan santai"},
    "しお": {"word": "塩", "meaning": "garam"},
    "しかし": {"word": "しかし", "meaning": "tetapi, namun"},
    "じかん": {"word": "時間", "meaning": "waktu, jam"},
    "しごと": {"word": "仕事", "meaning": "pekerjaan"},
    "じしょ": {"word": "辞書", "meaning": "kamus"},
    "しずか": {"word": "静か", "meaning": "tenang, sepi"},
    "した": {"word": "下", "meaning": "bawah"},
    "しつもん": {"word": "質問", "meaning": "pertanyaan"},
    "じてんしゃ": {"word": "自転車", "meaning": "sepeda"},
    "じどうしゃ": {"word": "自動車", "meaning": "mobil, otomotif"},
    "しぬ": {"word": "死ぬ", "meaning": "mati, meninggal"},
    "じびき": {"word": "字引", "meaning": "kamus"},
    "じぶん": {"word": "自分", "meaning": "diri sendiri"},
    "しまる": {"word": "閉まる", "meaning": "tertutup"},
    "しめる": {"word": "閉める", "meaning": "menutup"},
    "じゃ": {"word": "じゃ", "meaning": "sampai jumpa, kalau begitu"},
    "しゃしん": {"word": "写真", "meaning": "foto"},
    "シャツ": {"word": "シャツ", "meaning": "kemeja"},
    "じゅう": {"word": "十", "meaning": "sepuluh"},
    "しゅくだい": {"word": "宿題", "meaning": "pekerjaan rumah (PR)"},
    "じょうず": {"word": "上手", "meaning": "pintar, mahir"},
    "じょうぶ": {"word": "丈夫", "meaning": "kuat, kokoh"},
    "しょうゆ": {"word": "醤油", "meaning": "kecap asin"},
    "しょくどう": {"word": "食堂", "meaning": "kantin, ruang makan"},
    "しる": {"word": "知る", "meaning": "tahu, kenal"},
    "しろい": {"word": "白い", "meaning": "putih"},
    "しんぶん": {"word": "新聞", "meaning": "koran"},
    "すいようび": {"word": "水曜日", "meaning": "hari Rabu"},
    "すき": {"word": "好き", "meaning": "suka"},
    "すくない": {"word": "少ない", "meaning": "sedikit (jumlah)"},
    "すぐ": {"word": "すぐ", "meaning": "segera"},
    "すこし": {"word": "少し", "meaning": "sedikit"},
    "すずしい": {"word": "涼しい", "meaning": "sejuk"},
    "～する": {"word": "する", "meaning": "melakukan"},
    "すわる": {"word": "座る", "meaning": "duduk"},
    "せい": {"word": "背", "meaning": "tinggi badan"},
    "せいと": {"word": "生徒", "meaning": "murid, siswa"},
    "せっけん": {"word": "石鹸", "meaning": "sabun"},
    "ぜんぜん": {"word": "全然", "meaning": "sama sekali (tidak)"},
    "せんせい": {"word": "先生", "meaning": "guru, pak/bu (panggilan)"},
    "せんたく": {"word": "洗濯", "meaning": "mencuci pakaian"},
    "ぜんぶ": {"word": "全部", "meaning": "semua"},
    "そうじ": {"word": "掃除", "meaning": "bersih-bersih"},
    "そこ": {"word": "そこ", "meaning": "di situ"},
    "そして": {"word": "そして", "meaning": "lalu, kemudian"},
    "そちら": {"word": "そちら", "meaning": "di situ (sopan)"},
    "そっち": {"word": "そっち", "meaning": "di situ (informal)"},
    "そと": {"word": "外", "meaning": "luar"},
    "そば": {"word": "そば", "meaning": "dekat, samping"},
    "そら": {"word": "空", "meaning": "langit"},
    "それ": {"word": "それ", "meaning": "itu"},
    "それから": {"word": "それから", "meaning": "setelah itu"},
    "それでは": {"word": "それでは", "meaning": "kalau begitu"},
    "だ": {"word": "だ", "meaning": "adalah (informal)"},
    "だいがく": {"word": "大学", "meaning": "universitas"},
    "たいしかん": {"word": "大使館", "meaning": "kedutaan besar"},
    "だいじょうぶ": {"word": "大丈夫", "meaning": "tidak apa-apa"},
    "だいすき": {"word": "大好き", "meaning": "sangat suka"},
    "たいせつ": {"word": "大切", "meaning": "penting"},
    "だいどころ": {"word": "台所", "meaning": "dapur"},
    "たいへん": {"word": "大変", "meaning": "sulit, gawat, sangat"},
    "たかい": {"word": "高い", "meaning": "tinggi, mahal"},
    "たくさん": {"word": "たくさん", "meaning": "banyak"},
    "タクシー": {"word": "タクシー", "meaning": "taksi"},
    "だす": {"word": "出す", "meaning": "mengeluarkan, mengirim"},
    "ただいま": {"word": "ただいま", "meaning": "saya pulang"},
    "たつ": {"word": "立つ", "meaning": "berdiri"},
    "たのしい": {"word": "楽しい", "meaning": "menyenangkan"},
    "たのむ": {"word": "頼む", "meaning": "memohon, meminta"},
    "たばこ": {"word": "煙草", "meaning": "rokok"},
    "たぶん": {"word": "多分", "meaning": "mungkin"},
    "たべもの": {"word": "食べ物", "meaning": "makanan"},
    "たべる": {"word": "食べる", "meaning": "makan"},
    "たまご": {"word": "卵", "meaning": "telur"},
    "だれ": {"word": "誰", "meaning": "siapa"},
    "たんじょうび": {"word": "誕生日", "meaning": "hari ulang tahun"},
    "だんだん": {"word": "だんだん", "meaning": "berangsur-angsur, makin lama makin"},
    "ちいさい": {"word": "小さい", "meaning": "kecil"},
    "ちかい": {"word": "近い", "meaning": "dekat"},
    "ちがう": {"word": "違う", "meaning": "berbeda, salah"},
    "ちかく": {"word": "近く", "meaning": "dekat, sekitarnya"},
    "ちかてつ": {"word": "地下鉄", "meaning": "kereta bawah tanah"},
    "ちず": {"word": "地図", "meaning": "peta"},
    "ちゃいろ": {"word": "茶色", "meaning": "warna coklat"},
    "ちゃわん": {"word": "茶碗", "meaning": "mangkuk nasi, cangkir teh"},
    "ちょうど": {"word": "ちょうど", "meaning": "pas, tepat"},
    "ちょっと": {"word": "ちょっと", "meaning": "sedikit, sebentar"},
    "ついたち": {"word": "一日", "meaning": "tanggal 1"},
    "つかう": {"word": "使う", "meaning": "menggunakan"},
    "つかれる": {"word": "疲れる", "meaning": "lelah, capek"},
    "つぎ": {"word": "次", "meaning": "berikutnya"},
    "つくえ": {"word": "机", "meaning": "meja"},
    "つくる": {"word": "作る", "meaning": "membuat"},
    "つける": {"word": "点ける", "meaning": "menyalakan"},
    "つとめる": {"word": "勤める", "meaning": "bekerja untuk"},
    "つめたい": {"word": "冷たい", "meaning": "dingin (benda/sikap)"},
    "つよい": {"word": "強い", "meaning": "kuat"},
    "て": {"word": "手", "meaning": "tangan"},
    "てがみ": {"word": "手紙", "meaning": "surat"},
    "できる": {"word": "出来る", "meaning": "bisa, mampu"},
    "てぐち": {"word": "出口", "meaning": "pintu keluar"},
    "テスト": {"word": "テスト", "meaning": "tes, ujian"},
    "デパート": {"word": "デパート", "meaning": "toko serba ada (mall)"},
    "でも": {"word": "でも", "meaning": "tetapi, tapi"},
    "てんき": {"word": "天気", "meaning": "cuaca"},
    "でんしゃ": {"word": "電車", "meaning": "kereta listrik"},
    "でんわ": {"word": "電話", "meaning": "telepon"},
    "と": {"word": "と", "meaning": "dan, dengan"},
    "どあ": {"word": "ドア", "meaning": "pintu"},
    "といれ": {"word": "トイレ", "meaning": "toilet"},
    "どう": {"word": "どう", "meaning": "bagaimana"},
    "どうして": {"word": "どうして", "meaning": "mengapa, kenapa"},
    "どうぞ": {"word": "どうぞ", "meaning": "silakan"},
    "どうぶつ": {"word": "動物", "meaning": "hewan, binatang"},
    "どうも": {"word": "どうも", "meaning": "terima kasih, sangat"},
    "とお": {"word": "十", "meaning": "sepuluh"},
    "とおい": {"word": "遠い", "meaning": "jauh"},
    "とき": {"word": "時", "meaning": "saat, ketika"},
    "ときどき": {"word": "時々", "meaning": "kadang-kadang"},
    "とけい": {"word": "時計", "meaning": "jam, arloji"},
    "どこ": {"word": "どこ", "meaning": "di mana"},
    "ところ": {"word": "所", "meaning": "tempat"},
    "とし": {"word": "年", "meaning": "tahun, usia"},
    "としょかん": {"word": "図書館", "meaning": "perpustakaan"},
    "どっち": {"word": "どっち", "meaning": "yang mana (informal)"},
    "とても": {"word": "とても", "meaning": "sangat"},
    "どなた": {"word": "どなた", "meaning": "siapa (sopan)"},
    "となり": {"word": "隣", "meaning": "sebelah, tetangga"},
    "どの": {"word": "どの", "meaning": "yang mana (kata tunjuk)"},
    "とぶ": {"word": "飛ぶ", "meaning": "terbang, melompat"},
    "とまる": {"word": "止まる", "meaning": "berhenti"},
    "ともだち": {"word": "友達", "meaning": "teman"},
    "どようび": {"word": "土曜日", "meaning": "hari Sabtu"},
    "とり": {"word": "鳥", "meaning": "burung"},
    "とりにく": {"word": "鶏肉", "meaning": "daging ayam"},
    "とる": {"word": "取る", "meaning": "mengambil"},
    "どれ": {"word": "どれ", "meaning": "yang mana (kata ganti)"},
    "どんな": {"word": "どんな", "meaning": "yang seperti apa"},
    "ない": {"word": "ない", "meaning": "tidak ada, tidak"},
    "ないふ": {"word": "ナイフ", "meaning": "pisau"},
    "なか": {"word": "中", "meaning": "dalam"},
    "ながい": {"word": "長い", "meaning": "panjang"},
    "なく": {"word": "鳴く", "meaning": "berbunyi (hewan)"},
    "なつ": {"word": "夏", "meaning": "musim panas"},
    "なつやすみ": {"word": "夏休み", "meaning": "libur musim panas"},
    "など": {"word": "など", "meaning": "dan lain-lain"},
    "ななつ": {"word": "七つ", "meaning": "tujuh buah"},
    "なまえ": {"word": "名前", "meaning": "nama"},
    "ならう": {"word": "習う", "meaning": "belajar (dari guru)"},
    "ならぶ": {"word": "並ぶ", "meaning": "berbaris, berjajar"},
    "ならべる": {"word": "並べる", "meaning": "menyusun, menata"},
    "なる": {"word": "なる", "meaning": "menjadi"},
    "なん": {"word": "何", "meaning": "apa"},
    "にぎやか": {"word": "賑やか", "meaning": "ramai"},
    "にく": {"word": "肉", "meaning": "daging"},
    "にし": {"word": "西", "meaning": "barat"},
    "にちようび": {"word": "日曜日", "meaning": "hari Minggu"},
    "にもつ": {"word": "荷物", "meaning": "barang bawaan, bagasi"},
    "にわ": {"word": "庭", "meaning": "halaman, taman"},
    "ぬぐ": {"word": "脱ぐ", "meaning": "melepas (pakaian/sepatu)"},
    "ぬるい": {"word": "ぬるい", "meaning": "suam-suam kuku"},
    "ねこ": {"word": "猫", "meaning": "kucing"},
    "ねる": {"word": "寝る", "meaning": "tidur"},
    "のぼる": {"word": "登る", "meaning": "mendaki, memanjat"},
    "のみもの": {"word": "飲み物", "meaning": "minuman"},
    "のむ": {"word": "飲む", "meaning": "minum"},
    "のる": {"word": "乗る", "meaning": "naik (kendaraan)"},
    "はい": {"word": "はい", "meaning": "ya"},
    "はいざら": {"word": "灰皿", "meaning": "asbak"},
    "はいる": {"word": "入る", "meaning": "masuk"},
    "はがき": {"word": "葉書", "meaning": "kartu pos"},
    "はく": {"word": "履く", "meaning": "memakai (celana/sepatu)"},
    "はこ": {"word": "箱", "meaning": "kotak, peti"},
    "はし": {"word": "橋", "meaning": "jembatan"},
    "はし": {"word": "箸", "meaning": "sumpit"},
    "はじまる": {"word": "始まる", "meaning": "dimulai"},
    "はじめ": {"word": "始め", "meaning": "awal, permulaan"},
    "はじめて": {"word": "初めて", "meaning": "pertama kali"},
    "はしる": {"word": "走る", "meaning": "lari"},
    "はたけ": {"word": "畑", "meaning": "ladang, kebun"},
    "はたらく": {"word": "働く", "meaning": "bekerja"},
    "はち": {"word": "八", "meaning": "delapan"},
    "はな": {"word": "花", "meaning": "bunga"},
    "はな": {"word": "鼻", "meaning": "hidung"},
    "はなし": {"word": "話", "meaning": "cerita, pembicaraan"},
    "はなす": {"word": "話す", "meaning": "berbicara"},
    "はは": {"word": "母", "meaning": "ibu (sendiri)"},
    "はやい": {"word": "早い", "meaning": "cepat (waktu), awal"},
    "はやい": {"word": "速い", "meaning": "cepat (kecepatan)"},
    "はる": {"word": "春", "meaning": "musim semi"},
    "はる": {"word": "貼る", "meaning": "menempel"},
    "はれ": {"word": "晴れ", "meaning": "cerah"},
    "ばん": {"word": "晩", "meaning": "malam"},
    "ぱん": {"word": "パン", "meaning": "roti"},
    "ばんごう": {"word": "番号", "meaning": "nomor"},
    "ばんごはん": {"word": "晩御飯", "meaning": "makan malam"},
    "ひ": {"word": "火", "meaning": "api"},
    "ひ": {"word": "日", "meaning": "hari, matahari"},
    "ひがし": {"word": "東", "meaning": "timur"},
    "ひく": {"word": "引く", "meaning": "menarik, bermain (alat musik petik/tuts)"},
    "ひくい": {"word": "低い", "meaning": "rendah"},
    "ひこうき": {"word": "飛行機", "meaning": "pesawat terbang"},
    "ひだり": {"word": "左", "meaning": "kiri"},
    "ひと": {"word": "人", "meaning": "orang"},
    "ひとつ": {"word": "一つ", "meaning": "satu buah"},
    "ひとつき": {"word": "一月", "meaning": "satu bulan"},
    "ひとり": {"word": "一人", "meaning": "satu orang, sendirian"},
    "ひま": {"word": "暇", "meaning": "senggang, luang"},
    "ひゃく": {"word": "百", "meaning": "seratus"},
    "びょういん": {"word": "病院", "meaning": "rumah sakit"},
    "びょうき": {"word": "病気", "meaning": "sakit, penyakit"},
    "ひらがな": {"word": "ひらがな", "meaning": "huruf Hiragana"},
    "ひる": {"word": "昼", "meaning": "siang hari"},
    "ひるごはん": {"word": "昼御飯", "meaning": "makan siang"},
    "ひろい": {"word": "広い", "meaning": "luas"},
    "ふく": {"word": "吹く", "meaning": "bertiup, meniup"},
    "ふく": {"word": "服", "meaning": "pakaian, baju"},
    "ふたつ": {"word": "二つ", "meaning": "dua buah"},
    "ふたり": {"word": "二人", "meaning": "dua orang"},
    "ふとい": {"word": "太い", "meaning": "gemuk, tebal"},
    "ふゆ": {"word": "冬", "meaning": "musim dingin"},
    "ふる": {"word": "降る", "meaning": "turun (hujan/salju)"},
    "ふるい": {"word": "古い", "meaning": "tua, lama (benda)"},
    "ふろ": {"word": "風呂", "meaning": "bak mandi Jepang"},
    "ぶん": {"word": "文", "meaning": "kalimat"},
    "ぶんしょう": {"word": "文章", "meaning": "karangan, teks"},
    "へた": {"word": "下手", "meaning": "tidak mahir, payah"},
    "べんきょう": {"word": "勉強", "meaning": "belajar"},
    "べんり": {"word": "便利", "meaning": "praktis, nyaman"},
    "ほう": {"word": "方", "meaning": "sisi, pihak, arah"},
    "ほか": {"word": "他", "meaning": "lain"},
    "ぼく": {"word": "僕", "meaning": "aku (laki-laki)"},
    "ほしい": {"word": "欲しい", "meaning": "ingin, mau"},
    "ほそい": {"word": "細い", "meaning": "tipis, kurus"},
    "ほん": {"word": "本", "meaning": "buku"},
    "ほんだな": {"word": "本棚", "meaning": "rak buku"},
    "ほんとう": {"word": "本当", "meaning": "benar, sungguh"},
    "まいつき": {"word": "毎月", "meaning": "setiap bulan"},
    "まいしゅう": {"word": "毎週", "meaning": "setiap minggu"},
    "まいにち": {"word": "毎日", "meaning": "setiap hari"},
    "まいねん": {"word": "毎年", "meaning": "setiap tahun"},
    "まいあさ": {"word": "毎朝", "meaning": "setiap pagi"},
    "まいばん": {"word": "毎晩", "meaning": "setiap malam"},
    "まえ": {"word": "前", "meaning": "depan, sebelum"},
    "まがる": {"word": "曲がる", "meaning": "belok, melengkung"},
    "まずい": {"word": "まずい", "meaning": "tidak enak (makanan)"},
    "また": {"word": "また", "meaning": "lagi, dan juga"},
    "まだ": {"word": "まだ", "meaning": "belum"},
    "まち": {"word": "町", "meaning": "kota"},
    "まつ": {"word": "待つ", "meaning": "menunggu"},
    "まっすぐ": {"word": "真っ直ぐ", "meaning": "lurus"},
    "まど": {"word": "窓", "meaning": "jendela"},
    "まるい": {"word": "丸い", "meaning": "bulat, bundar"},
    "まん": {"word": "万", "meaning": "sepuluh ribu"},
    "みえる": {"word": "見える", "meaning": "kelihatan, tampak"},
    "みがく": {"word": "磨く", "meaning": "menggosok, menyikat"},
    "みぎ": {"word": "右", "meaning": "kanan"},
    "みじかい": {"word": "短い", "meaning": "pendek"},
    "みず": {"word": "水", "meaning": "air"},
    "みせ": {"word": "店", "meaning": "toko"},
    "みせる": {"word": "見せる", "meaning": "memperlihatkan"},
    "みち": {"word": "道", "meaning": "jalan"},
    "みっつ": {"word": "三つ", "meaning": "tiga buah"},
    "みどり": {"word": "緑", "meaning": "hijau"},
    "みなさん": {"word": "皆さん", "meaning": "semuanya, hadirin"},
    "みなみ": {"word": "南", "meaning": "selatan"},
    "みみ": {"word": "耳", "meaning": "telinga"},
    "みる": {"word": "見る", "meaning": "melihat"},
    "みんな": {"word": "みんな", "meaning": "semua, semua orang"},
    "むいか": {"word": "六日", "meaning": "tanggal 6, enam hari"},
    "むこう": {"word": "向こう", "meaning": "seberang, di sana"},
    "むら": {"word": "村", "meaning": "desa"},
    "むずかしい": {"word": "難しい", "meaning": "sulit, sukar"},
    "め": {"word": "目", "meaning": "mata"},
    "めがね": {"word": "眼鏡", "meaning": "kacamata"},
    "もう": {"word": "もう", "meaning": "sudah, lagi"},
    "もしもし": {"word": "もしもし", "meaning": "halo (telepon)"},
    "もつ": {"word": "持つ", "meaning": "membawa, memiliki"},
    "もっと": {"word": "もっと", "meaning": "lebih, lagi"},
    "もの": {"word": "物", "meaning": "benda, barang"},
    "もん": {"word": "門", "meaning": "gerbang"},
    "もんだい": {"word": "問題", "meaning": "masalah, soal"},
    "やさい": {"word": "野菜", "meaning": "sayuran"},
    "やさしい": {"word": "易しい", "meaning": "mudah, gampang"},
    "やさしい": {"word": "優しい", "meaning": "baik hati, ramah"},
    "やすい": {"word": "安い", "meaning": "murah"},
    "やすみ": {"word": "休み", "meaning": "istirahat, libur"},
    "やすむ": {"word": "休む", "meaning": "istirahat, absen"},
    "やっつ": {"word": "八つ", "meaning": "delapan buah"},
    "やま": {"word": "山", "meaning": "gunung"},
    "やる": {"word": "やる", "meaning": "melakukan, memberi (ke hewan/tanaman)"},
    "ゆうがた": {"word": "夕方", "meaning": "sore hari"},
    "ゆうびんきょく": {"word": "郵便局", "meaning": "kantor pos"},
    "ゆうめい": {"word": "有名", "meaning": "terkenal"},
    "ゆき": {"word": "雪", "meaning": "salju"},
    "ゆっくり": {"word": "ゆっくり", "meaning": "pelan-pelan, santai"},
    "よい": {"word": "良い", "meaning": "baik, bagus"},
    "ようか": {"word": "八日", "meaning": "tanggal 8, delapan hari"},
    "ようふく": {"word": "洋服", "meaning": "pakaian ala barat"},
    "よく": {"word": "よく", "meaning": "sering, dengan baik"},
    "よこ": {"word": "横", "meaning": "samping, lebar"},
    "よっか": {"word": "四日", "meaning": "tanggal 4, empat hari"},
    "よっつ": {"word": "四つ", "meaning": "empat buah"},
    "よぶ": {"word": "呼ぶ", "meaning": "memanggil"},
    "よむ": {"word": "読む", "meaning": "membaca"},
    "よる": {"word": "夜", "meaning": "malam"},
    "よわい": {"word": "弱い", "meaning": "lemah"},
    "らいげつ": {"word": "来月", "meaning": "bulan depan"},
    "らいしゅう": {"word": "来週", "meaning": "minggu depan"},
    "らいねん": {"word": "来年", "meaning": "tahun depan"},
    "ラジオ": {"word": "ラジオ", "meaning": "radio"},
    "りゅうがくせい": {"word": "留学生", "meaning": "mahasiswa asing"},
    "りょうり": {"word": "料理", "meaning": "masakan"},
    "りょこう": {"word": "旅行", "meaning": "perjalanan, tamasya"},
    "れいぞうこ": {"word": "冷蔵庫", "meaning": "kulkas"},
    "レコード": {"word": "レコード", "meaning": "rekaman, piringan hitam"},
    "レストラン": {"word": "レストラン", "meaning": "restoran"},
    "れんしゅう": {"word": "練習", "meaning": "latihan"},
    "ろく": {"word": "六", "meaning": "enam"},
    "わかい": {"word": "若い", "meaning": "muda"},
    "わかる": {"word": "分かる", "meaning": "mengerti, paham"},
    "わすれる": {"word": "忘れる", "meaning": "lupa"},
    "わたし": {"word": "私", "meaning": "saya"},
    "わたす": {"word": "渡す", "meaning": "menyerahkan"},
    "わたる": {"word": "渡る", "meaning": "menyeberang"},
    "わるい": {"word": "悪い", "meaning": "buruk, jahat"},
    "～ご": {"word": "～語", "meaning": "bahasa (negara)"},
    "～じ": {"word": "～時", "meaning": "jam ..."},
    "～じかん": {"word": "～時間", "meaning": "... jam (durasi)"},
}

def sync():
    print("Starting N5 synchronization...")
    
    # 1. Clean up existing N5 data (handle duplicates first)
    n5_qs = Vocab.objects.filter(jlpt_level=5)
    
    # Track which words we've updated to avoid re-adding
    updated_ids = set()
    
    for reading, data in N5_REF.items():
        # Find matches in DB by reading AND (word OR reading)
        matches = n5_qs.filter(reading=reading)
        
        if matches.exists():
            # If multiple matches, merge them into the one with Kanji if available
            kanji_match = matches.filter(word=data['word']).first()
            target = kanji_match or matches.first()
            
            target.word = data['word']
            target.meaning = data['meaning']
            target.save()
            updated_ids.add(target.id)
            
            # Delete other matches as they are now redundant
            matches.exclude(id=target.id).delete()
        else:
            # If no match, we don't necessarily want to add new ones yet
            # because the user wants "pas 594". But let's see if there are
            # generic N5 entries we can "re-purpose".
            pass

    # 2. Re-verify count
    final_count = Vocab.objects.filter(jlpt_level=5).count()
    print(f"Sync finished. Current N5 count: {final_count}")

if __name__ == "__main__":
    from django.db import transaction
    with transaction.atomic():
        sync()
