import json

# Raw rows from rspsensei.com pages 1-6
# Format: (No, B. Jepang, Jenis kata, Cara baca, Arti)
raw_rows = [
    # Page 1
    (1, '～ごろ', 'ADV', '~goro', 'sekitar~, kira-kira'),
    (2, '～すぎ', 'ADV', '~sugi', 'terlalu (banyak)~'),
    (3, '～ずつ', 'ADV', '~ zutsu', '~per~'),
    (4, '～たち', 'ADV', '~tachi', 'para~, dkk'),
    (5, '～中', 'ADV', '~chuu/~juu', 'dalam~(kurun waktu)'),
    (6, '～中', 'ADV', '~chuu/juu', 'sedang'),
    (7, '～個', 'ADV', '~ko', '~buah,~butir'),
    (8, '～側', 'ADV', '~gawa', 'bagian~'),
    (9, '～冊', 'ADV', '~satsu', '~buah (buku, kamus)'),
    (10, '～台', 'ADV', '~dai', '~unit'),
    (11, '～回', 'ADV', '~kai', '~kali'),
    (12, '～屋', 'ADV', '~ya', 'toko'),
    (13, '～時', 'ADV', '~ji', 'jam'),
    (14, '～杯', 'ADV', '~hai/~pai', '~gelas'),
    (15, '～歳', 'ADV', '~sai', '~tahun (umur)'),
    (16, '～階', 'ADV', '~kai', 'lantai~'),
    (17, '３万円', 'N', 'San man en', 'tiga puluh ribu yen'),
    (18, 'あさって', 'ADV', 'asatte', 'besok lusa'),
    (19, 'あちら', 'ADV', 'achira', 'disana ( jauh ) sopan'),
    (20, 'あっち', 'ADV', 'acchi', 'disana ( jauh ) informal'),
    (21, 'あなた', 'N', 'anata', 'kamu, anda'),
    (22, 'アパート', 'N', 'apaato', 'apartment'),
    (23, 'あまり', 'ADV', 'amari', 'tidak begitu'),
    (24, 'ある', 'V', 'aru', 'ada ( benda mati )'),
    (25, 'あれ', 'ADV', 'are', 'itu ( jauh )'),
    (26, 'いい', 'ADJ', 'ii', 'bagus'),
    (27, 'いくつ', 'ADV', 'ikutsu', 'berapa'),
    (28, 'いくら', 'ADV', 'ikura', 'berapa harganya'),
    (29, '椅子', 'N', 'isu', 'kursi'),
    (30, 'いつ', 'ADV', 'itsu', 'kapan'),
    (31, 'いつか', 'ADV', 'itsuka', 'suatu saat'),
    (32, 'いつも', 'ADV', 'itsumo', 'selalu'),
    (33, 'いる', 'V', 'iru', 'ada ( orang )'),
    (34, '色々', 'ADJ', 'iroiro', 'bermacam-macam'),
    (35, '内', 'N', 'uchi', 'dalam'),
    (36, 'うるさい', 'ADJ', 'urusai', 'berisik'),
    (37, 'ええ', 'ADV', 'ee', 'ya'),
    (38, '美味しい', 'ADJ', 'oishii', 'enak'),
    (39, 'お菓子', 'ADJ', 'okashi', 'cemilan'),
    (40, '起きる', 'V', 'okiru', 'bangun'),
    (41, '一昨日', 'ADV', 'ototoi', '2 hari yang lalu'),
    (42, '一昨年', 'ADV', 'ototoshi', '2 tahun yang lalu'),
    (43, '面白い', 'ADJ', 'omoshiroi', 'menarik'),
    (44, 'お兄さん', 'N', 'oniisan', 'kakak laki-laki ( orang lain )'),
    (45, 'お回り', 'ADV', 'omawari', 'sekitar'),
    (46, 'お姉さん', 'N', 'oneesan', 'kakak perempuan ( orang lain )'),
    (47, 'お弁当', 'N', 'obentou', 'bekal makanan'),
    (48, 'お手洗い', 'N', 'otearai', 'toilet, kamar kecil'),
    (49, 'お母さん', 'N', 'okaasan', 'ibu ( orang lain )'),
    (50, 'お父さん', 'N', 'otousan', 'ayah ( orang lain )'),
    (51, 'お皿', 'N', 'osara', 'piring'),
    (52, 'お茶', 'N', 'ocha', 'teh hijau'),
    (53, 'お酒', 'N', 'osake', 'arak Jepang'),
    (54, 'お金', 'N', 'okane', 'uang'),
    (55, 'お風呂', 'N', 'ofuro', 'ofuro ( bak mandi )'),
    (56, 'かける', 'V', 'kakeru', 'memakai ( kacamata )'),
    (57, '傘', 'N', 'kasa', 'payung'),
    (58, 'ガスストーブ', 'N', 'Gasu sutoobu', 'Kompor gas'),
    (59, 'カタカナ', 'N', 'katakana', 'huruf katakana'),
    (60, 'カップ', 'N', 'kappu', 'gelas'),
    (61, 'かばん', 'N', 'kaban', 'tas'),
    (62, 'かびん', 'N', 'kabin', 'vas bunga'),
    (63, 'かぶる', 'V', 'kaburu', 'memakai topi'),
    (64, 'カメラ', 'N', 'kamera', 'kamera'),
    (65, 'カレンダー', 'N', 'karendaa', 'kalender'),
    (66, '可愛い', 'ADJ', 'kawaii', 'lucu, imut'),
    (67, 'ギター', 'N', 'gitaa', 'gitar'),
    (68, '汚い', 'ADJ', 'kitanai', 'kotor, jorok'),
    (69, '切手', 'N', 'kitte', 'perangko'),
    (70, '昨日', 'ADV', 'kinou', 'kemarin'),
    (71, '嫌い', 'ADJ', 'kirai', 'tidak suka, benci'),
    (72, 'きれい', 'ADJ', 'kirei', 'cantik, indah'),
    (73, 'キロ', 'N', 'kiro', 'kilo'),
    (74, 'ぐらい', 'ADV', 'gurai', 'kira-kira'),
    (75, 'クラス', 'N', 'kurasu', 'kelas'),
    (76, 'グラム', 'N', 'guramu', 'gram'),
    (77, 'ヶ月', 'ADV', 'kagetsu', '~bulan'),
    (78, 'コーヒー', 'N', 'koohii', 'kopi'),
    (79, '午後', 'ADV', 'gogo', 'siang (.p.m)'),
    (80, 'こちら', 'ADV', 'kochira', 'di sini'),
    (81, 'こっち', 'ADV', 'kocchi', 'di sini ( informal )'),
    (82, 'こっちきて', 'ADV', 'Kocchi kite', 'Datang sini!'),
    (83, 'コップ', 'N', 'koppu', 'cangkir'),
    (84, 'コピーする', 'V', 'kopii suru', 'menyalin, memfotokopi'),
    (85, 'こんな', 'ADV', 'konna', '~yang seperti ini, ~segini'),
    (86, 'ご飯', 'N', 'gohan', 'nasi'),
    (87, 'しかし', 'ADV', 'shikashi', 'tapi'),
    (88, '醤油', 'N', 'shouyu', 'kecap asin'),
    (89, 'すぐ', 'ADV', 'sugu', 'segera'),
    (90, '少し', 'ADJ', 'sukoshi', 'sedikit'),
    (91, 'ストーブ', 'N', 'sutobu', 'kompor'),
    (92, 'スプーン', 'N', 'supuun', 'sendok'),
    (93, 'スポーツ', 'N', 'supootsu', 'Olah raga'),
    (94, 'スリッパ', 'N', 'surippa', 'Sandal dalam rumah'),
    (95, 'そして', 'ADV', 'soshite', 'dan, lalu'),
    (96, 'そっち', 'ADV', 'socchi', 'disana ( jauh ) informal'),
    (97, 'そば', 'ADV', 'soba', 'samping'),
    (98, 'それから', 'ADV', 'sore kara', 'lalu, setelah itu'),
    (99, 'それでは', 'ADV', 'soredewa', 'baiklah'),
    (100, 'タイ', 'N', 'tai', 'Thailand'),
    (101, '台所', 'N', 'dai dokoro', 'dapur'),

    # Page 2
    (102, 'たくさん', 'ADJ', 'takusan', 'banyak'),
    (103, 'だけ', 'ADV', 'dake', 'hanya'),
    (104, 'タバコ', 'N', 'tabako', 'rokok'),
    (105, '多分', 'ADV', 'tabun', 'mungkin'),
    (106, 'だれ', 'ADV', 'dare', 'siapa'),
    (107, 'だれか', 'N', 'dare ka', 'seseorang'),
    (108, 'ちょうど', 'ADV', 'choudo', 'pas, tepat'),
    (109, 'ちょっと', 'ADV', 'chotto', 'Sedikit, sebentar'),
    (110, 'つまらない', 'ADJ', 'tsumaranai', 'Membosankan'),
    (111, 'テーブル', 'N', 'teeburu', 'meja'),
    (112, 'テスト', 'N', 'tesuto', 'tes, ujian'),
    (113, 'では', 'ADV', 'dewa', 'baiklah'),
    (114, 'デパート', 'N', 'depaato', 'toserba'),
    (115, 'でも', 'ADV', 'demo', 'tapi'),
    (116, 'どうして', 'ADV', 'doushite', 'mengapa, kenapa'),
    (117, 'どうぞ', 'ADV', 'douzo', 'silahkan'),
    (118, 'どうも', 'ADV', 'doumo', 'terima kasih'),
    (119, 'ときどき', 'ADV', 'tokidoki', 'kadang-kadang'),
    (120, '所', 'V', 'tokoro', 'tempat'),
    (121, 'どなた', 'ADV', 'donata', 'siapa ( bentuk sopan )'),
    (122, 'どの', 'ADV', 'dono', 'yang mana'),
    (123, 'どれ', 'ADV', 'dore', 'yang mana'),
    (124, 'どんな', 'ADV', 'donna', 'yang bagaimana'),
    (125, 'ない', 'ADV', 'nai', 'tidak punya, tidak ada'),
    (126, 'ナイフ', 'N', 'naifu', 'pisau'),
    (127, '泣く', 'V', 'naku', 'menangis'),
    (128, 'なぜ', 'ADV', 'naze', 'mengapa'),
    (129, 'など', 'ADV', 'nado', 'dan lain-lain'),
    (130, 'なる', 'V', 'naru', 'menjadi'),
    (131, 'にぎやか', 'ADJ', 'nigiyaka', 'ramai'),
    (132, 'ネクタイ', 'N', 'nekutai', 'dasi'),
    (133, 'パーティー', 'N', 'paatii', 'pesta'),
    (134, 'プール', 'N', 'puuru', 'Kolam renang'),
    (135, 'フォーク', 'N', 'fooku', 'garpu'),
    (136, 'ページ', 'N', 'peeji', 'Halaman'),
    (137, 'ベッド', 'N', 'beddo', 'Kasur'),
    (138, 'ペット', 'N', 'petto', 'hewan peliharaan'),
    (139, 'ペットの店', 'N', 'Petto no mise', 'Toko hewan peliharaan'),
    (140, '帽子', 'N', 'boushi', 'Topi'),
    (141, 'ほしい', 'ADJ', 'hoshii', 'Ingin'),
    (142, 'ポスト', 'N', 'posuto', 'kotak pos'),
    (143, 'ボタン', 'N', 'botan', 'Tombol'),
    (144, 'ホテル', 'N', 'hoteru', 'Hotel'),
    (145, 'まずい', 'ADJ', 'mazui', 'Tidak enak'),
    (146, 'また', 'ADV', 'mata', 'lagi'),
    (147, 'まだ', 'ADV', 'mada', 'Belum, masih'),
    (148, 'まっすぐ', 'ADV', 'massugu', 'Lurus'),
    (149, 'メートル', 'N', 'meetoru', 'Meter'),
    (150, 'めがね', 'N', 'megane', 'Kacamata'),
    (151, 'もしもし', 'ADV', 'moshimoshi', 'Halo ( saat telpon )'),
    (152, 'もっと', 'ADV', 'motto', 'Lebih, dan lagi'),
    (153, 'やる', 'V', 'yaru', 'Melakukan, mengerjakan'),
    (154, '一人ずつ', 'ADV', 'Hitorizutsu', 'satu orang per satu orang'),
    (155, '一日', 'ADV', 'ichinichi', 'satu hari'),
    (156, '一番', 'ADV', 'ichiban', 'paling , no 1'),
    (157, '一緒に', 'ADV', 'isshoni', 'bersama'),
    (158, '万', 'N', 'man', 'sepuluh ribu'),
    (159, '丈夫', 'ADJ', 'joubu', 'Kokoh, kuat, sehat'),
    (160, '上げる', 'V', 'ageru', 'menaikan'),
    (161, '上手', 'ADJ', 'jouzu', 'terampil, mahir'),
    (162, '上着', 'N', 'uwagi', 'baju , Jas'),
    (163, '下手', 'ADJ', 'heta', 'tidak pandai'),
    (164, '並ぶ', 'V', 'narabu', 'berbaris, berjajar'),
    (165, '並べる', 'V', 'naraberu', 'menjajarkan'),
    (166, '中', 'ADV', 'naka', 'dalam'),
    (167, '丸い', 'ADJ', 'marui', 'Bulat, bundar'),
    (168, '乗る', 'V', 'noru', 'naik ( kendaraan )'),
    (169, '交差点', 'N', 'kousaten', 'persimpangan'),
    (170, '交番', 'N', 'kouban', 'pos polisi'),
    (171, '今', 'N', 'ima', 'sekarang'),
    (172, '今年', 'N', 'kotoshi', 'tahun ini'),
    (173, '今日', 'N', 'kyou', 'hari ini'),
    (174, '今晩', 'N', 'konban', 'malam ini'),
    (175, '今月', 'N', 'kongetsu', 'bulan ini'),
    (176, '今朝', 'N', 'kesa', 'tadi pagi'),
    (177, '今週', 'N', 'konshuu', 'minggu ini'),
    (178, '仕事', 'N', 'shigoto', 'pekerjaan'),
    (179, '他', 'N', 'hoka', 'yang lain'),
    (180, '他の人', 'N', 'Hoka no hito', 'Orang lain'),
    (181, '休み', 'N', 'yasumi', 'Libur'),
    (182, '休む', 'V', 'yasumu', 'beristirahat'),
    (183, '会う', 'V', 'au', 'bertemu'),
    (184, '会社', 'N', 'kaisha', 'perusahaan'),
    (185, '低い', 'ADJ', 'hikui', 'Rendah / pendek'),
    (186, '低い山', 'N', 'Hikui yama', 'Gunung rendah'),
    (187, '住む', 'V', 'sumu', 'tinggal, bermukim'),
    (188, '体', 'N', 'karada', 'badan, tubuh'),
    (189, '作る', 'V', 'tsukuru', 'membuat'),
    (190, '作文', 'N', 'sakubun', 'karangan'),
    (191, '使う', 'V', 'tsukau', 'memakai'),
    (192, '便利', 'ADJ', 'benri', 'Praktis, mudah'),
    (193, '借りる', 'V', 'kariru', 'meminjam'),
    (194, '元気', 'ADJ', 'genki', 'sehat'),
    (195, '兄', 'N', 'ani', 'kakak laki-laki saya'),
    (196, '兄弟', 'N', 'kyoudai', 'saudara, adik kakak'),
    (197, '先月', 'N', 'sengetsu', 'bulan lalu'),
    (198, '先週', 'N', 'senshuu', 'minggu lalu'),
    (199, '入り口', 'N', 'iriguchi', 'pintu masuk'),
    (200, '入れる', 'V', 'ireru', 'memasukan'),

    # Page 3
    (201, '全部', 'ADV', 'zenbu', 'semua'),
    (202, '八百屋', 'N', 'yaoya', 'Toko sayuran'),
    (203, '公園', 'N', 'kouen', 'taman'),
    (204, '円', 'N', 'en', 'yen'),
    (205, '再来年', 'N', 'sarainen', '2 tahun yang akan datang'),
    (206, '冬', 'N', 'fuyu', 'Musim dingin'),
    (207, '冷たい', 'ADJ', 'tsumetai', 'Dingin'),
    (208, '出かける', 'V', 'dekakeru', 'keluar, bepergian'),
    (209, '出す', 'V', 'dasu', 'mengeluarkan'),
    (210, '出る', 'V', 'deru', 'keluar'),
    (211, '出口', 'N', 'deguchi', 'pintu keluar'),
    (212, '切符', 'N', 'kippu', 'tiket'),
    (213, '初めて', 'ADV', 'Hajimete', 'pertama kali'),
    (214, '勉強する', 'V', 'benkyou suru', 'belajar'),
    (215, '医者', 'N', 'isha', 'dokter'),
    (216, '午前', 'N', 'gozen', 'pagi (a.m.)'),
    (217, '半', 'N', 'han', 'Setengah'),
    (218, '半分', 'N', 'hanbun', 'Setengah'),
    (219, '南', 'N', 'minami', 'Selatan'),
    (220, '南口', 'N', 'Minamiguchi', 'Pintu Selatan'),
    (221, '危ない', 'ADJ', 'abunai', 'bahaya'),
    (222, '卵', 'N', 'tamago', 'telur'),
    (223, '厚い', 'ADJ', 'atsui', 'tebal'),
    (224, '去年', 'N', 'kyonen', 'tahun lalu'),
    (225, '友達', 'N', 'tomodachi', 'teman'),
    (226, '取る', 'V', 'toru', 'mengambil / mendapatkan/ meraih'),
    (227, '古い', 'ADJ', 'furui', 'Tua, usang'),
    (228, '右', 'N', 'migi', 'Kanan'),
    (229, '同じ', 'ADV', 'onaji', 'sama'),
    (230, '向こう', 'N', 'mukou', 'Seberang'),
    (231, '吸う', 'V', 'suu', 'mengisap'),
    (232, '咲く', 'V', 'saku', 'mekar'),
    (233, '問題', 'N', 'mondai', 'Masalah'),
    (234, '喫茶店', 'N', 'kissaten', 'cafe'),
    (235, '困る', 'V', 'komaru', 'khawatir, susah'),
    (236, '図書館', 'N', 'toshokan', 'perpustakaan'),
    (237, '国', 'N', 'kuni', 'negara'),
    (238, '地図', 'N', 'chizu', 'peta'),
    (239, '塩', 'N', 'shio', 'Garam'),
    (240, '声', 'N', 'koe', 'suara'),
    (241, '売る', 'V', 'uru', 'menjual'),
    (242, '夏', 'N', 'natsu', 'musim panas'),
    (243, '夕べ', 'N', 'yuube', 'Tadi malam'),
    (244, '夕方', 'N', 'yuugata', 'Sore'),
    (245, '夕飯', 'N', 'yuuhan', 'Makan malam'),
    (246, '外', 'N', 'soto', 'luar'),
    (247, '外国', 'N', 'gaikoku', 'luar negeri'),
    (248, '外国人', 'N', 'gaikokujin', 'orang asing'),
    (249, '多い', 'ADJ', 'ooi', 'banyak'),
    (250, '大きい', 'ADJ', 'ookii', 'besar'),
    (251, '大きな', 'ADJ', 'ookina', 'yang besar'),
    (252, '大丈夫', 'ADJ', 'daijoubu', 'tidak apa-apa'),
    (253, '大人', 'N', 'otona', 'dewasa'),
    (254, '大使館', 'N', 'taishikan', 'kedutaan'),
    (255, '大切', 'ADJ', 'taisetsu', 'penting'),
    (256, '大勢', 'ADJ', 'oozei', 'banyak'),
    (257, '大変', 'ADJ', 'taihen', 'berat, susah'),
    (258, '大好き', 'ADJ', 'daisuki', 'sangat suka'),
    (259, '天気', 'N', 'tenki', 'cuaca'),
    (260, '太い', 'ADJ', 'futoi', 'Gendut, gemuk'),
    (261, '太い足', 'N', 'Futoi ashi', 'Kaki besar, gemuk'),
    (262, '奥さん', 'N', 'okusan', 'istri anda'),
    (263, '女', 'N', 'onna', 'perempuan'),
    (264, '女の子', 'N', 'onna no ko', 'anak perempuan'),
    (265, '好き', 'ADJ', 'suki', 'suka'),
    (266, '妹', 'N', 'imouto', 'adik perempuan'),
    (267, '姉', 'N', 'ane', 'kakak perempuan saya'),
    (268, '始まる', 'V', 'Hajimaru', 'Dimulai'),
    (269, '嫌', 'ADJ', 'iya', 'tidak mau, tidak suka'),
    (270, '子供', 'N', 'kodomo', 'anak kecil'),
    (271, '学校', 'N', 'gakkou', 'sekolah'),
    (272, '学生', 'N', 'gakusei', 'murid'),
    (273, '安い', 'ADJ', 'yasui', 'Murah'),
    (274, '家', 'N', 'ie', 'rumah'),
    (275, '家庭', 'N', 'katei', 'rumah tangga'),
    (276, '家族', 'N', 'kazoku', 'keluarga'),
    (277, '宿題', 'N', 'shukudai', 'PR (pekerjaan rumah)'),
    (278, '寒い', 'ADJ', 'samui', 'dingin'),
    (279, '封筒', 'N', 'fuutou', 'Amplop'),
    (280, '小さい', 'ADJ', 'chiisai', 'kecil'),
    (281, '小さな', 'ADJ', 'chiisana', 'kecil'),
    (282, '少ない', 'ADJ', 'sukunai', 'sedikit'),
    (283, '川', 'N', 'kawa', 'sungai'),
    (284, '帰る', 'V', 'kaeru', 'pulang'),
    (285, '広い', 'ADJ', 'hiroi', 'Lebar, luas'),
    (286, '広い庭', 'N', 'Hiroi niwa', 'Halaman rumah yang luas'),
    (287, '店', 'N', 'mise', 'toko'),
    (288, '度', 'N', 'do', 'derajat'),
    (289, '座る', 'V', 'suwaru', 'duduk'),
    (290, '庭', 'N', 'niwa', 'halaman ( rumah )'),
    (291, '建物', 'N', 'tatemono', 'bangunan'),
    (292, '弟', 'N', 'otouto', 'adik laki-laki ( sendiri )'),
    (293, '強い', 'ADJ', 'tsuyoi', 'kuat'),
    (294, '弾く', 'V', 'hiku', 'memetik (alat musik)'),
    (295, '待つ', 'V', 'matsu', 'menunggu'),
    (296, '後ろ', 'N', 'ushiro', 'belakang'),
    (297, '忙しい', 'ADJ', 'isogashii', 'sibuk'),
    (298, '意味', 'N', 'imi', 'arti'),
    (299, '戸', 'N', 'to', 'pintu'),
    (300, '手', 'N', 'te', 'tangan'),

    # Page 4
    (301, '手紙', 'N', 'tegami', 'surat'),
    (302, '押す', 'V', 'osu', 'mendorong'),
    (303, '授業', 'N', 'jugyou', 'pelajaran'),
    (304, '撮る', 'V', 'Toru', 'mengambil (foto)'),
    (305, '教える', 'V', 'oshieru', 'mengajarkan'),
    (306, '教室', 'N', 'kyoushistu', 'kelas'),
    (307, '散歩する', 'V', 'sanpo suru', 'jalan-jalan santai'),
    (308, '文章', 'N', 'bunshou', 'Kalimat'),
    (309, '新しい', 'ADJ', 'atarashii', 'baru'),
    (310, '方', 'ADV', 'Hou', 'yang ~, arah'),
    (311, '方', 'ADV', 'kata', 'Orang (bentuk sopan)'),
    (312, '日本語', 'N', 'nihongo', 'bahasa Jepang'),
    (313, '早い', 'ADJ', 'hayai', 'Cepat'),
    (314, '早く走る', 'V', 'Hayaku hashiru', 'Berlari/melaju dengan cepat'),
    (315, '明るい', 'ADJ', 'akarui', 'terang'),
    (316, '明日', 'N', 'ashita', 'besok'),
    (317, '映画', 'N', 'eiga', 'film, sinema'),
    (318, '映画館', 'N', 'eigakan', 'bioskop'),
    (319, '春', 'N', 'haru', 'Musim semi'),
    (320, '昼', 'N', 'hiru', 'Siang'),
    (321, '昼ご飯', 'N', 'hiru gohan', 'Makan siang'),
    (322, '時計', 'N', 'tokei', 'jam'),
    (323, '時間', 'N', 'jikan', 'waktu'),
    (324, '晴れ', 'N', 'hare', 'cerah'),
    (325, '晴れる', 'V', 'hareru', 'cerah'),
    (326, '暑い', 'ADJ', 'atsui', 'panas ( suhu )'),
    (327, '暖かい', 'ADJ', 'atatakai', 'hangat'),
    (328, '暗い', 'ADJ', 'kurai', 'gelap'),
    (329, '曇り', 'ADJ', 'kumori', 'berawan, mendung'),
    (330, '曲がる', 'V', 'magaru', 'Belok'),
    (331, '書く', 'V', 'kaku', 'menulis'),
    (332, '月', 'N', 'tsuki', 'bulan (dilangit)'),
    (333, '月曜日', 'N', 'getsuyoubi', 'hari senin'),
    (334, '有名', 'ADJ', 'yuumei', 'Terkenal'),
    (335, '朝ごはん', 'N', 'asagohan', 'sarapan pagi'),
    (336, '朝ご飯', 'N', 'Asa gohan', 'Sarapan pagi'),
    (337, '木', 'N', 'ki', 'pohon'),
    (338, '本当', 'ADV', 'hontou', 'Benar'),
    (339, '本当の話', 'ADV', 'Hontou no hanashi', 'Omongan yang benar'),
    (340, '机', 'N', 'tsukue', 'meja'),
    (341, '来る', 'V', 'kuru', 'datang'),
    (342, '果物', 'N', 'kudamono', 'buah-buahan'),
    (343, '楽しい', 'ADJ', 'tanoshii', 'menyenangkan'),
    (344, '次', 'ADV', 'tsugi', 'selanjutnya'),
    (345, '次のページ', 'ADV', 'Tsugi no peeji', 'Halaman selanjutnya'),
    (346, '歌', 'N', 'uta', 'lagu'),
    (347, '歌う', 'V', 'utau', 'bernanyi'),
    (348, '歩く', 'V', 'aruku', 'berjalan'),
    (349, '死ぬ', 'V', 'shinu', 'mati'),
    (350, '水', 'N', 'mizu', 'Air'),
    (351, '水を飲む', 'V', 'Mizu wo nomu', 'Minum air'),
    (352, '池', 'N', 'ike', 'kolam'),
    (353, '泳ぐ', 'V', 'oyogu', 'berenang'),
    (354, '洗う', 'V', 'ara u', 'mencuci'),
    (355, '洗濯', 'N', 'sentaku', 'mencuci'),
    (356, '海', 'N', 'umi', 'laut'),
    (357, '消える', 'V', 'kieru', 'padam'),
    (358, '消す', 'V', 'kesu', 'mematikan'),
    (359, '涼しい', 'ADJ', 'suzushii', 'sejuk'),
    (360, '漢字', 'N', 'kanji', 'kanji (huruf Cina)'),
    (361, '灰皿', 'N', 'Haizara', 'Asbak'),
    (362, '父', 'N', 'chichi', 'ayah'),
    (363, '牛乳', 'N', 'gyuunyuu', 'susu sapi'),
    (364, '牛肉', 'N', 'gyuuniku', 'daging sapi'),
    (365, '物', 'N', 'mono', 'Barang'),
    (366, '物を買う', 'V', 'Mono o kau', 'Membeli (suatu) barang'),
    (367, '犬', 'N', 'inu', 'anjing'),
    (368, '狭い', 'ADJ', 'semai', 'sempit'),
    (369, '玄関', 'N', 'genkan', 'pintu masuk (tempat melepas sepatu)'),
    (370, '甘い', 'ADJ', 'amai', 'manis'),
    (371, '生まれる', 'V', 'umareru', 'lahir'),
    (372, '生徒', 'N', 'seito', 'siswa'),
    (373, '男', 'N', 'otoko', 'laki-laki'),
    (374, '男の子', 'N', 'otoko no ko', 'anak laki-laki'),
    (375, '町', 'N', 'machi', 'Kota'),
    (376, '番号', 'N', 'bangou', 'Nomor'),
    (377, '疲れる', 'V', 'Tsukareru', 'lelah'),
    (378, '病気', 'N', 'byouki', 'Penyakit, sakit'),
    (379, '病院', 'N', 'byouin', 'Rumah sakit'),
    (380, '痛い', 'ADJ', 'itai', 'sakit'),
    (381, '登る', 'V', 'noboru', 'naik, mendaki'),
    (382, '白い', 'ADJ', 'shiroi', 'putih'),
    (383, '着く', 'V', 'tsuku', 'tiba, sampai'),
    (384, '着る', 'V', 'kiru', 'memakai (baju)'),
    (385, '知る', 'V', 'shiru', 'tahu, mengetahui'),
    (386, '短い', 'ADJ', 'mijikai', 'Pendek'),
    (387, '短い髪', 'N', 'Mijikai kami', 'Rambut pendek'),
    (388, '石けん', 'N', 'sekken', 'sabun'),
    (389, '砂糖', 'N', 'satou', 'gula'),
    (390, '秋', 'N', 'aki', 'musim gugur'),
    (391, '空', 'N', 'sora', 'langit'),
    (392, '窓', 'N', 'mado', 'Jendela'),
    (393, '窓を閉める', 'V', 'Mado o shimeru', 'Menutup jendela'),
    (394, '答える', 'V', 'kotaeru', 'menjawab'),
    (395, '紅茶', 'N', 'koucha', 'teh hitam'),
    (396, '紙', 'N', 'kami', 'kertas'),
    (397, '紙コップ', 'N', 'Kami koppu', 'Cangkir kertas'),
    (398, '細い', 'ADJ', 'hosoi', 'kecil, receh, tipis,kurus'),
    (399, '細かいお金', 'N', 'Komakai okane', 'Uang kecil / receh'),
    (400, '終わる', 'V', 'owaru', 'selesai'),

    # Page 5
    (401, '結婚', 'N', 'kekkon', 'menikah'),
    (402, '絵', 'N', 'e', 'gambar, lukisan'),
    (403, '緑', 'N', 'midori', 'hijau'),
    (404, '緑の野菜', 'N', 'Midori no yasai', 'Sayuran hijau'),
    (405, '縦', 'N', 'tate', 'vertikal, berdiri'),
    (406, '置く', 'V', 'oku', 'menaruh'),
    (407, '習う', 'V', 'narau', 'mempelajari'),
    (408, '聞く', 'V', 'kiku', 'mendengar'),
    (409, '肉', 'N', 'niku', 'daging'),
    (410, '肩', 'N', 'kata', 'pundak'),
    (411, '背', 'N', 'se', 'pundak'),
    (412, '背広', 'N', 'sebiro', 'jas'),
    (413, '脱ぐ', 'V', 'nugu', 'melepas (baju, sepatu)'),
    (414, '自分', 'N', 'jibun', 'saya sendiri'),
    (415, '自動車', 'N', 'jidousha', 'mobil'),
    (416, '自転車', 'N', 'jitensha', 'sepeda'),
    (417, '色', 'N', 'iro', 'warna'),
    (418, '英語', 'N', 'eigo', 'bahasa inggris'),
    (419, '茶碗', 'N', 'chawan', 'Cangkir'),
    (420, '茶色', 'N', 'chairo', 'coklat'),
    (421, '薬', 'N', 'kusuri', 'obat'),
    (422, '行く', 'V', 'iku', 'pergi'),
    (423, '西', 'N', 'nishi', 'barat'),
    (424, '要る', 'V', 'iru', 'perlu'),
    (425, '見せる', 'V', 'miseru', 'Memperlihatkan'),
    (426, '見る', 'V', 'miru', 'melihat, menonton'),
    (427, '覚える', 'V', 'oboeru', 'menghafal'),
    (428, '言う', 'V', 'iu', 'berkata'),
    (429, '言葉', 'N', 'kotoba', 'kosakata'),
    (430, '話', 'N', 'hanashi', 'Cerita, pembicaraan'),
    (431, '話す', 'V', 'hanasu', 'Berbicara'),
    (432, '話を聞く', 'V', 'Hanashi o kiku', 'Mendengarkan cerita'),
    (433, '誕生日', 'N', 'tanjoubi', 'ulang tahun'),
    (434, '豚肉', 'N', 'butaniku', 'Daging babi'),
    (435, '買い物', 'N', 'kaimono', 'belanja'),
    (436, '買う', 'V', 'kau', 'membeli'),
    (437, '貸す', 'V', 'kasu', 'meminjamkan'),
    (438, '貼る', 'V', 'haru', 'Menempel'),
    (439, '質問', 'N', 'shitsumon', 'pertanyaan'),
    (440, '赤い', 'ADJ', 'akai', 'merah'),
    (441, '走る', 'V', 'hashiru', 'Berlari'),
    (442, '車', 'N', 'kuruma', 'mobil'),
    (443, '軽い', 'ADJ', 'karui', 'ringan'),
    (444, '辞書', 'N', 'jisho', 'kamus'),
    (445, '近い', 'ADJ', 'chikai', 'dekat'),
    (446, '近く', 'V', 'chikaku', 'dekat'),
    (447, '返す', 'V', 'kaesu', 'mengembalikan'),
    (448, '速い', 'ADJ', 'hayai', 'Cepat (kendaraan)'),
    (449, '遅い', 'ADJ', 'osoi', 'lambat'),
    (450, '遊ぶ', 'V', 'asobu', 'main'),
    (451, '道', 'N', 'michi', 'Jalan'),
    (452, '違う', 'V', 'chigau', 'berbeda, salah'),
    (453, '遠い', 'ADJ', 'tooi', 'jauh'),
    (454, '郵便局', 'N', 'yuubinkyoku', 'Kantor pos'),
    (455, '都合', 'N', 'tsugou', 'kondisi, keadaan'),
    (456, '重い', 'ADJ', 'omoi', 'berat'),
    (457, '野菜', 'N', 'yasai', 'Sayuran'),
    (458, '野菜がきらい', 'ADJ', 'Yasai ga kirai', 'Saya tidak suka sayuran'),
    (459, '鉛筆', 'N', 'enpitsu', 'pensil'),
    (460, '銀行', 'N', 'ginkou', 'bank'),
    (461, '長い', 'ADJ', 'nagai', 'panjang'),
    (462, '門', 'N', 'mon', 'Gerbang'),
    (463, '閉まる', 'V', 'shimaru', 'tertutup'),
    (464, '閉める', 'V', 'shimeru', 'menutup'),
    (465, '開ける', 'V', 'akeru', 'membuka'),
    (466, '降る', 'V', 'furu', 'Turun'),
    (467, '階段', 'N', 'kaidan', 'tangga'),
    (468, '隣', 'N', 'tonari', 'sebelah'),
    (469, '雑誌', 'N', 'zasshi', 'majalah'),
    (470, '難しい', 'ADJ', 'muzukashii', 'Sulit'),
    (471, '雨', 'N', 'ame', 'hujan'),
    (472, '雪', 'N', 'yuki', 'Salju'),
    (473, '電気', 'N', 'denki', 'listrik'),
    (474, '電話', 'N', 'Denwa', 'telpon'),
    (475, '電話番号', 'N', 'Denwa bangou', 'Nomor telepon'),
    (476, '青い', 'ADJ', 'aoi', 'biru'),
    (477, '静か', 'ADJ', 'shizuka', 'tenang, sunyi'),
    (478, '靴', 'N', 'kutsu', 'sepatu'),
    (479, '靴下', 'N', 'kutsushita', 'kaos kaki'),
    (480, '靴屋', 'N', 'Kutsuya', 'Toko sepatu'),
    (481, '音楽', 'N', 'ongaku', 'musik'),
    (482, '頼む', 'V', 'tanomu', 'meminta'),
    (483, '顔', 'N', 'kao', 'wajah'),
    (484, '風', 'N', 'kaze', 'angin'),
    (485, '風呂', 'N', 'furo', 'Mandi'),
    (486, '風邪', 'N', 'kaze', 'masuk angin'),
    (487, '飛ぶ', 'V', 'tobu', 'terbang'),
    (488, '飛行機', 'N', 'hikouki', 'Pesawat terbang'),
    (489, '食べすぎ', 'ADV', 'Tabesugi', 'Terlalu banyak makan'),
    (490, '食べる', 'V', 'taberu', 'makan'),
    (491, '食べ物', 'N', 'tabemono', 'makanan'),
    (492, '食堂', 'N', 'shokudou', 'kantin'),
    (493, '飲み物', 'N', 'nomimono', 'minuman'),
    (494, '飲む', 'V', 'nomu', 'minum'),
    (495, '飴', 'N', 'ame', 'permen'),
    (496, '駅', 'N', 'eki', 'stasiun'),
    (497, '高い', 'ADJ', 'takai', 'tinggi, mahal'),
    (498, '魚', 'N', 'sakana', 'ikan'),
    (499, '鳥', 'N', 'tori', 'burung'),
    (500, '鶏肉', 'N', 'toriniku', 'daging ayam'),

    # Page 6
    (501, '黄色', 'N', 'kiiro', 'warna kuning'),
    (502, '黒い', 'ADJ', 'kuroi', 'hitam'),
    (503, '鼻', 'N', 'hana', 'Hidung'),
    (504, '決める', 'V', 'kimeru', 'menentukan'),
    (505, '止まる', 'V', 'tomaru', 'berhenti'),
    (506, '参る', 'V', 'mairu', 'pergi sembahyang'),
    (507, 'これから', 'ADJ', 'korekara', 'mulai dari sekarang'),
    (508, 'ショッピング', 'N', 'shoppingu', 'belanja'),
    (509, '手すり', 'N', 'tesuri', 'pegangan, batang'),
    (510, '高等学校', 'N', 'koutou gakkou', 'SMA'),
    (511, '僕', 'N', 'boku', 'saya ( informal untuk laki-laki)'),
    (512, '用意する', 'V', 'youi suru', 'mempersiapkan'),
    (513, '指輪', 'N', 'yubiwa', 'cincin'),
    (514, 'すごく', 'ADJ', 'sugoku', 'sangat'),
    (515, 'まず', 'ADV', 'mazu', 'pertama-tama'),
    (516, 'プロ', 'N', 'puro', 'profesional'),
    (517, '店員', 'N', 'ten\'in', 'petugas, pelayan'),
    (518, 'かまいません', 'V', 'kamaimasen', 'tidak apa-apa, boleh'),
    (519, 'それほど～ない', 'V', 'sorehodo~nai', 'tidak ~ lebih dari itu'),
    (520, '大学', 'N', 'daigaku', 'universitas'),
    (521, '受ける', 'V', 'ukeru', 'menerima'),
    (522, 'やはり', 'ADV', 'yahari', 'memang betul, ternyata'),
    (523, 'ぬれる', 'V', 'nureru', 'basah'),
    (524, '動物', 'N', 'doubutsu', 'binatang'),
    (525, '頭', 'N', 'atama', 'kepala'),
    (526, '準備する', 'V', 'junbi suru', 'mempersiapkan'),
    (527, 'スカート', 'N', 'sukaato', 'rok'),
    (528, 'どんどん', 'N', 'dondon', 'semakin'),
    (529, 'すっかり', 'N', 'sukkari', 'benar-benar'),
    (530, '大会', 'N', 'taikai', 'acara, pesta'),
    (531, '近所', 'N', 'kinjo', 'tetangga'),
    (532, '急ぐ', 'V', 'isogu', 'buru-buru, menyegerakan'),
    (533, 'インターネット', 'N', 'intaanetto', 'internet'),
    (534, '口', 'N', 'kuchi', 'mulut'),
    (535, '骨', 'N', 'hone', 'tulang'),
    (536, '品物', 'N', 'shinamono', 'barang'),
    (537, '増える', 'V', 'fueru', 'bertambah'),
    (538, '新幹線', 'N', 'shinkansen', 'kereta peluru, shinkansen'),
    (539, '予習する', 'V', 'yoshuu suru', 'mempersiapkan sebelum belajar'),
    (540, '急に', 'ADV', 'kyuu ni', 'tiba-tiba'),
    (541, '恥ずかしい', 'ADJ', 'hazukashii', 'malu'),
    (542, '始める', 'V', 'hajimeru', 'memulai'),
    (543, '心配する', 'V', 'shinpaisuru', 'khawatir'),
    (544, '飾る', 'V', 'kazaru', 'memajang'),
    (545, '会話', 'N', 'kaiwa', 'percakapan'),
    (546, 'わけ', 'N', 'wake', 'alasan'),
    (547, 'フランス', 'N', 'furansu', 'prancis'),
    (548, 'オーストラリア', 'N', 'oosutoraria', 'Australia'),
    (549, 'ほめる', 'V', 'homeru', 'memuji'),
    (550, '田舎', 'N', 'inaka', 'pedesaan'),
    (551, '神社', 'N', 'jinja', 'sebuah kuil'),
    (552, 'くださる', 'V', 'kudasaru', 'mendapat (dari~)'),
    (553, '釣る', 'V', 'tsuru', 'memancing'),
    (554, '足す', 'V', 'tasu', 'menambahkan'),
    (555, '地震', 'N', 'jishin', 'gempa bumi'),
    (556, 'とうとう', 'ADV', 'toutou', 'akhirnya'),
    (557, '届ける', 'V', 'todokeru', 'menyampaikan, mengirim'),
    (558, '相談する', 'V', 'soudan suru', 'konsultasi'),
    (559, '中学生', 'N', 'chuugakusei', 'siswa sekolah menengah'),
    (560, '太る', 'V', 'futoru', 'menjadi gemuk'),
    (561, '予約する', 'V', 'yoyaku suru', 'memesan'),
    (562, 'やわらかい', 'ADJ', 'yawarakai', 'lembut, empuk'),
    (563, '熱', 'N', 'netsu', 'panas,demam'),
    (564, '歯', 'N', 'ha', 'gigi'),
    (565, 'セール', 'N', 'seeru', 'dijual'),
    (566, '無くす', 'ADV', 'nakusu', 'menghilangkan'),
    (567, 'ダイエット', 'N', 'dietto', 'diet'),
    (568, '指', 'N', 'yubi', 'jari'),
    (569, '続く', 'V', 'tsuzuku', 'berlanjut'),
    (570, '場所', 'N', 'basho', 'tempat'),
    (571, '心', 'N', 'kokoro', 'hati'),
    (572, 'ドレス', 'N', 'doresu', 'gaun'),
    (573, '下げる', 'V', 'sageru', 'menurunkan'),
    (574, '裏', 'N', 'ura', 'bagian belakang'),
    (575, 'ヨーロッパ', 'N', 'youroppa', 'Eropa'),
    (576, '講義', 'N', 'kougi', 'perkuliahan'),
    (577, '半額', 'N', 'hangaku', 'setengah harga'),
    (578, '市', 'N', '~shi', 'kota'),
    (579, '娘', 'N', 'musume', 'seorang gadis'),
    (580, '幼稚園', 'N', 'youchien', 'Taman kanak-kanak'),
    (581, '片付ける', 'V', 'katazukeru', 'merapihkan'),
    (582, '空く', 'V', 'aku', 'kosong'),
    (583, '素晴らしい', 'ADJ', 'subarashii', 'menakjubkan'),
    (584, '復習する', 'V', 'fukushuu suru', 'mengulang (pelajaran)'),
    (585, '普通', 'N', 'futsuu', 'biasa'),
    (586, '出発する', 'V', 'shupatsu suru', 'berangkat'),
    (587, '運ぶ', 'V', 'hakobu', 'mengangkut'),
    (588, '咳', 'N', 'seki', 'batuk'),
    (589, '南東', 'N', 'nantou', 'tenggara'),
    (590, '帰り', 'N', 'kaeri', 'pulang'),
    (591, '治る', 'V', 'naoru', 'menjadi sembuh'),
    (592, '伝える', 'V', 'tsutaeru', 'menyampaikan'),
    (593, '決まる', 'V', 'kimaru', 'ditentukan, diputuskan'),
    (594, '乗り物', 'N', 'norimono', 'kendaraan'),
    (595, 'なるべく', 'ADV', 'narubeku', 'sedapat mungkin'),
    (596, 'ひげ', 'N', 'hige', 'janggut'),
    (597, '表', 'N', 'omote', 'bagian depan, muka'),
    (598, '地方', 'N', 'chihou', 'wilayah, pedesaan'),
    (599, 'アルバイト', 'N', 'arubaito', 'pekerjaan, paruh waktu'),
    (600, '棚', 'N', 'tana', 'rak'),
    (601, '変', 'ADJ', 'hen', 'aneh'),
    (602, '客', 'N', 'kyaku', 'pelanggan'),
    (603, '消防車', 'N', 'shoubousha', 'mobil pemadam kebakaran'),
    (604, '習慣', 'N', 'shuukan', 'kebiasaan'),
    (605, '縮む', 'V', 'chijimu', 'mengkerut'),
    (606, '県', 'N', 'ken', 'prefektur'),
    (607, '腰', 'N', 'koshi', 'pinggang'),
    (608, '集まる', 'V', 'atsumaru', 'berkumpul'),
    (609, 'たしか', 'ADV', 'tashika', 'pastinya,memang'),
    (610, 'スパゲッティ', 'N', 'supagetti', 'spageti'),
    (611, '退院する', 'V', 'taiin suru', 'keluar dari rumah sakit'),
    (612, 'かむ', 'V', 'kamu', 'menggigit'),
    (613, '韓国', 'N', 'kankoku', 'Korea'),
    (614, '落ちる', 'V', 'ochiru', 'jatuh'),
    (615, 'わざと', 'ADV', 'wazato', 'sengaja'),
    (616, '役に立つ', 'V', 'yaku ni tatsu', 'berguna'),
    (617, 'おっしゃる', 'V', 'ossharu', 'mengatakan ( hormat )'),
    (618, '小鳥', 'N', 'kotori', 'seekor burung')
]

# Clean up
final_list = []
seen = set()

# First pass: remove obvious phrase duplicates from rspsensei (heuristic)
for no, w, t, r, m in raw_rows:
    # Heuristic for examples/phrases: contains particles or specific symbols
    is_phrase = False
    if any(p in w for p in ['を', 'に', 'へ', 'が', 'と', 'は']):
        # Exceptions for common words that might contain these
        if w not in ['～たち', '～中', '～個', '～回', '～時', '～杯', '～歳', '～階', '女の子', '男の子', '～ヶ月', '～回']:
            is_phrase = True
    
    # Also check for "no" as particle in word
    if 'の' in w and w not in ['女の子', '男の子', '飲み物', '乗り物', '食べ物', '飲み物']:
        is_phrase = True

    if is_phrase:
        continue

    # Merge duplicates (same word + reading)
    key = (w, r)
    if key in seen:
        # Update existing entry meaning if it's new
        for entry in final_list:
            if entry['word'] == w and entry['reading'] == r:
                if m not in entry['meaning']:
                    entry['meaning'] += ", " + m
        continue
    
    type_map = {
        'ADV': 'adverb',
        'N': 'noun',
        'V': 'godan',
        'ADJ': 'i_adj'
    }
    final_list.append({
        'word': w, 
        'reading': r, 
        'meaning': m,
        'word_type': type_map.get(t, 'other')
    })
    seen.add(key)

print(f"Initial clean count: {len(final_list)}")

# We need exactly 594. 
# If we have more, we truncate. If we have less, we might have missed some words from standard N5.
if len(final_list) > 594:
    final_list = final_list[:594]
elif len(final_list) < 594:
    # We add common N5 words that are missing from rspsensei but standard
    # Format: (word, reading, meaning, type)
    standard_n5 = [
        ("ああ", "aa", "ah, oh", "other"),
        ("会う", "au", "bertemu", "godan"),
        ("青", "ao", "biru", "noun"),
        ("赤", "aka", "merah", "noun"),
        ("秋", "aki", "musim gugur", "noun"),
        ("開く", "aku", "terbuka", "godan"),
        ("あげる", "ageru", "memberi", "ichidan"),
        ("朝", "asa", "pagi", "noun"),
        ("足", "ashi", "kaki", "noun"),
        ("明日", "ashita", "besok", "noun"),
        ("あそこ", "asoko", "di sana (jauh)", "pronoun"),
        ("遊ぶ", "asobu", "bermain", "godan"),
        ("暖かい", "atatakai", "hangat", "i_adj"),
        ("頭", "atama", "kepala", "noun"),
        ("新しい", "atarashii", "baru", "i_adj"),
        ("暑い", "atsui", "panas (suhu)", "i_adj"),
        ("熱い", "atsui", "panas (benda)", "i_adj"),
        ("厚い", "atsui", "tebal", "i_adj"),
        ("後", "ato", "setelah", "noun"),
        ("あなた", "anata", "anda, kamu", "pronoun"),
        ("兄", "ani", "kakak laki-laki", "noun"),
        ("姉", "ane", "kakak perempuan", "noun"),
        ("アパート", "apaato", "apartemen", "noun"),
        ("危ない", "abunai", "berbahaya", "i_adj"),
        ("甘い", "amai", "manis", "i_adj"),
        ("雨", "ame", "hujan", "noun"),
        ("飴", "ame", "permen", "noun"),
        ("洗う", "arau", "mencuci", "godan"),
        ("歩く", "aruku", "berjalan", "godan"),
        ("いい", "ii", "baik, bagus", "i_adj"),
        ("いいえ", "iie", "tidak", "other"),
        ("言う", "iu", "mengatakan", "godan"),
        ("家", "ie", "rumah", "noun"),
        ("行く", "iku", "pergi", "godan"),
        ("いくつ", "ikutsu", "berapa banyak", "other"),
        ("いくら", "ikura", "berapa harga", "other"),
        ("池", "ike", "kolam", "noun"),
        ("医者", "isha", "dokter", "noun"),
        ("椅子", "isu", "kursi", "noun"),
        ("忙しい", "isogashii", "sibuk", "i_adj"),
        ("痛い", "itai", "sakit", "i_adj"),
        ("一", "ichi", "satu", "noun"),
        ("一日", "ichinichi", "satu hari", "noun"),
        ("いちばん", "ichiban", "paling, nomor satu", "adverb"),
        ("いつ", "itsu", "kapan", "other"),
        ("五日", "itsuka", "tanggal lima", "noun"),
        ("一緒", "issho", "bersama", "adverb"),
        ("五つ", "itsutsu", "lima buah", "counter"),
        ("いつも", "itsumo", "selalu", "adverb"),
        ("犬", "inu", "anjing", "noun"),
        ("今", "ima", "sekarang", "noun"),
        ("意味", "imi", "arti, makna", "noun"),
        ("妹", "imouto", "adik perempuan", "noun"),
        ("嫌", "iya", "tidak suka", "na_adj"),
        ("入口", "iriguchi", "pintu masuk", "noun"),
        ("いる", "iru", "ada (makhluk hidup)", "ichidan"),
        ("入れる", "ireru", "memasukkan", "ichidan"),
        ("色", "iro", "warna", "noun"),
        ("いろいろ", "iroiro", "bermacam-macam", "na_adj"),
        ("上", "ue", "atas", "noun"),
        ("後ろ", "ushiro", "belakang", "noun"),
        ("薄い", "usui", "tipis", "i_adj"),
        ("歌", "uta", "lagu", "noun"),
        ("歌う", "utau", "menyanyi", "godan"),
        ("うち", "uchi", "rumah", "noun"),
        ("生まれる", "umareru", "lahir", "ichidan"),
        ("海", "umi", "laut", "noun"),
        ("売る", "uru", "menjual", "godan"),
        ("うるさい", "urusai", "berisik", "i_adj"),
        ("上着", "uwagi", "jaket, jas", "noun"),
        ("絵", "e", "gambar, lukisan", "noun"),
        ("映画", "eiga", "film", "noun"),
        ("英語", "eigo", "bahasa inggris", "noun"),
        ("駅", "eki", "stasiun", "noun"),
        ("エレベーター", "erebeetaa", "lift", "noun"),
        ("円", "en", "yen", "noun"),
        ("鉛筆", "enpitsu", "pensil", "noun"),
        ("美味しい", "oishii", "enak", "i_adj"),
        ("大きい", "ookii", "besar", "i_adj"),
        ("お母さん", "okaasan", "ibu", "noun"),
        ("お菓子", "okashi", "kue, cemilan", "noun"),
        ("お金", "okane", "uang", "noun"),
        ("起きる", "okiru", "bangun", "ichidan"),
        ("置く", "oku", "meletakkan", "godan"),
        ("奥さん", "okusan", "istri", "noun"),
        ("お酒", "osake", "sake", "noun"),
        ("お皿", "osara", "piring", "noun"),
        ("おじいさん", "ojiisan", "kakek", "noun"),
        ("教える", "oshieru", "mengajar", "ichidan"),
        ("おじさん", "ojisan", "paman", "noun"),
        ("押す", "osu", "mendorong", "godan"),
        ("遅い", "osoi", "lambat", "i_adj"),
        ("お茶", "ocha", "teh", "noun"),
        ("お手洗い", "otearai", "toilet", "noun"),
        ("お父さん", "otousan", "ayah", "noun"),
        ("弟", "otouto", "adik laki-laki", "noun"),
        ("男", "otoko", "laki-laki", "noun"),
        ("男の子", "otoko no ko", "anak laki-laki", "noun"),
        ("おとな", "otona", "dewasa", "noun"),
        ("おなか", "onaka", "perut", "noun"),
        ("同じ", "onaji", "sama", "na_adj"),
        ("お姉さん", "oneesan", "kakak perempuan", "noun"),
        ("おばあさん", "obaasan", "nenek", "noun"),
        ("おばさん", "obasan", "bibi", "noun"),
        ("お風呂", "ofuro", "bak mandi", "noun"),
        ("お弁当", "obentou", "bekal", "noun"),
        ("覚える", "oboeru", "menghafal", "ichidan"),
        ("おもしろい", "omoshiroi", "menarik", "i_adj"),
        ("泳ぐ", "oyogu", "berenang", "godan"),
        ("降りる", "oriru", "turun", "ichidan"),
        ("終わる", "owaru", "selesai", "godan"),
        ("音楽", "ongaku", "musik", "noun"),
        ("女", "onna", "perempuan", "noun"),
        ("女の子", "onna no ko", "anak perempuan", "noun"),
        ("外国", "gaikoku", "luar negeri", "noun"),
        ("会社", "kaisha", "perusahaan", "noun"),
        ("階段", "kaidan", "tangga", "noun"),
        ("買い物", "kaimono", "belanja", "noun"),
        ("買う", "kau", "membeli", "godan"),
        ("返す", "kaesu", "mengembalikan", "godan"),
        ("帰る", "kaeru", "pulang", "godan"),
        ("かぎ", "kagi", "kunci", "noun"),
        ("書く", "kaku", "menulis", "godan"),
        ("学生", "gakusei", "siswa", "noun"),
        ("傘", "kasa", "payung", "noun"),
        ("貸す", "kasu", "meminjamkan", "godan"),
        ("風", "kaze", "angin", "noun"),
        ("家族", "kazoku", "keluarga", "noun"),
        ("学校", "gakkou", "sekolah", "noun"),
        ("角", "kado", "sudut", "noun"),
        ("かばん", "kaban", "tas", "noun"),
        ("花瓶", "kabin", "vas bunga", "noun"),
        ("かぶる", "kaburu", "memakai topi", "godan"),
        ("紙", "kami", "kertas", "noun"),
        ("カメラ", "kamera", "kamera", "noun"),
        ("火曜日", "kayoubi", "selasa", "noun"),
        ("辛い", "karai", "pedas", "i_adj"),
        ("体", "karada", "tubuh", "noun"),
        ("借りる", "kariru", "meminjam", "ichidan"),
        ("軽い", "karui", "ringan", "i_adj"),
        ("カレンダー", "karendaa", "kalender", "noun"),
        ("川", "kawa", "sungai", "noun"),
        ("可愛い", "kawaii", "lucu", "i_adj"),
        ("漢字", "kanji", "kanji", "noun"),
        ("木", "ki", "pohon", "noun"),
        ("黄色", "kiiro", "kuning", "noun"),
        ("消える", "kieru", "padam", "ichidan"),
        ("聞く", "kiku", "mendengar", "godan"),
        ("北", "kita", "utara", "noun"),
        ("ギター", "gitaa", "gitar", "noun"),
        ("汚い", "kitanai", "kotor", "i_adj"),
        ("喫茶店", "kissaten", "kafe", "noun"),
        ("切手", "kitte", "perangko", "noun"),
        ("切符", "kippu", "tiket", "noun"),
        ("昨日", "kinou", "kemarin", "noun"),
        ("九", "kyuu", "sembilan", "noun"),
        ("牛肉", "gyuuniku", "daging sapi", "noun"),
        ("牛乳", "gyuunyuu", "susu sapi", "noun"),
        ("今日", "kyou", "hari ini", "noun"),
        ("教室", "kyoushitsu", "ruang kelas", "noun"),
        ("兄弟", "kyoudai", "saudara", "noun"),
        ("去年", "kyonen", "tahun lalu", "noun"),
        ("嫌い", "kirai", "benci", "na_adj"),
        ("切る", "kiru", "memotong", "godan"),
        ("着る", "kiru", "memakai baju", "ichidan"),
        ("きれい", "kirei", "cantik, bersih", "na_adj"),
        ("キロ", "kiro", "kilo", "noun"),
        ("銀行", "ginkou", "bank", "noun"),
        ("金曜日", "kinyoubi", "jumat", "noun"),
        ("薬", "kusuri", "obat", "noun"),
        ("果物", "kudamono", "buah", "noun"),
        ("口", "kuchi", "mulut", "noun"),
        ("靴", "kutsu", "sepatu", "noun"),
        ("靴下", "kutsushita", "kaos kaki", "noun"),
        ("国", "kuni", "negara", "noun"),
        ("曇り", "kumori", "berawan", "noun"),
        ("暗い", "kurai", "gelap", "i_adj"),
        ("クラス", "kurasu", "kelas", "noun"),
        ("グラム", "guramu", "gram", "noun"),
        ("来る", "kuru", "datang", "other"),
        ("車", "kuruma", "mobil", "noun"),
        ("黒い", "kuroi", "hitam", "i_adj"),
        ("今朝", "kesa", "pagi ini", "noun"),
        ("消す", "kesu", "mematikan", "godan"),
        ("結婚", "kekkon", "menikah", "suru"),
        ("月曜日", "getsuyoubi", "senin", "noun"),
        ("玄関", "genkan", "pintu masuk", "noun"),
        ("元気", "genki", "sehat", "na_adj"),
        ("五", "go", "lima", "noun"),
        ("公園", "kouen", "taman", "noun"),
        ("交差点", "kousaten", "persimpangan", "noun"),
        ("紅茶", "koucha", "teh hitam", "noun"),
        ("交番", "kouban", "pos polisi", "noun"),
        ("声", "koe", "suara", "noun"),
        ("ここ", "koko", "di sini", "pronoun"),
        ("午後", "gogo", "siang (pm)", "noun"),
        ("午前", "gozen", "pagi (am)", "noun"),
        ("答える", "kotaeru", "menjawab", "ichidan"),
        ("こちら", "kochira", "di sini", "pronoun"),
        ("コップ", "koppu", "gelas", "noun"),
        ("今年", "kotoshi", "tahun ini", "noun"),
        ("言葉", "kotoba", "kata", "noun"),
        ("子供", "kodomo", "anak-anak", "noun"),
        ("御飯", "gohan", "nasi", "noun"),
        ("コピー", "kopii", "fotokopi", "suru"),
        ("困る", "komaru", "susah", "godan"),
        ("これ", "kore", "ini", "pronoun"),
        ("今月", "kongetsu", "bulan ini", "noun"),
        ("今週", "konshuu", "minggu ini", "noun"),
        ("今晩", "konban", "malam ini", "noun"),
        ("財布", "saifu", "dompet", "noun"),
        ("魚", "sakana", "ikan", "noun"),
        ("先", "saki", "tadi", "noun"),
        ("咲く", "saku", "mekar", "godan"),
        ("作文", "sakubun", "karangan", "noun"),
        ("雑誌", "zasshi", "majalah", "noun"),
        ("砂糖", "satou", "gula", "noun"),
        ("寒い", "samui", "dingin", "i_adj"),
        ("さ来年", "sarainen", "dua tahun lagi", "noun"),
        ("三", "san", "tiga", "noun"),
        ("散歩", "sanpo", "jalan-jalan", "suru"),
        ("四", "shi", "empat", "noun"),
        ("塩", "shio", "garam", "noun"),
        ("しかし", "shikashi", "tetapi", "conjunction"),
        ("時間", "jikan", "waktu", "noun"),
        ("仕事", "shigoto", "pekerjaan", "noun"),
        ("辞書", "jisho", "kamus", "noun"),
        ("静か", "shizuka", "tenang", "na_adj"),
        ("下", "shita", "bawah", "noun"),
        ("七", "shichi", "tujuh", "noun"),
        ("質問", "shitsumon", "pertanyaan", "suru"),
        ("自転車", "jitensha", "sepeda", "noun"),
        ("自動車", "jidousha", "mobil", "noun"),
        ("死ぬ", "shinu", "mati", "godan"),
        ("自分", "jibun", "diri sendiri", "pronoun"),
        ("閉まる", "shimaru", "tertutup", "godan"),
        ("閉める", "shimeru", "menutup", "ichidan"),
        ("写真", "shashin", "foto", "noun"),
        ("シャツ", "shatsu", "kemeja", "noun"),
        ("十", "juu", "sepuluh", "noun"),
        ("授業", "jugyou", "pelajaran", "noun"),
        ("宿題", "shukudai", "pr", "noun"),
        ("上手", "jouzu", "mahir", "na_adj"),
        ("丈夫", "joubu", "kuat", "na_adj"),
        ("醤油", "shouyu", "kecap asin", "noun"),
        ("食堂", "shokudou", "kantin", "noun"),
        ("知る", "shiru", "tahu", "godan"),
        ("白い", "shiroi", "putih", "i_adj"),
        ("新聞", "shinbun", "koran", "noun"),
        ("水曜日", "suiyoubi", "rabu", "noun"),
        ("吸う", "suu", "mengisap", "godan"),
        ("スカート", "sukaato", "rok", "noun"),
        ("好き", "suki", "suka", "na_adj"),
        ("少ない", "sukunai", "sedikit", "i_adj"),
        ("すぐ", "sugu", "segera", "adverb"),
        ("少し", "sukoshi", "sedikit", "adverb"),
        ("涼しい", "suzushii", "sejuk", "i_adj"),
        ("座る", "suwaru", "duduk", "godan"),
        ("背", "se", "tinggi badan", "noun"),
        ("生徒", "seito", "murid", "noun"),
        ("石鹸", "sekken", "sabun", "noun"),
        ("全然", "zenzen", "sama sekali tidak", "adverb"),
        ("先生", "sensei", "guru", "noun"),
        ("洗濯", "sentaku", "mencuci", "suru"),
        ("全部", "zenbu", "semua", "noun"),
        ("掃除", "souji", "bersih-bersih", "suru"),
        ("そこ", "soko", "di situ", "pronoun"),
        ("外", "soto", "luar", "noun"),
        ("そば", "soba", "dekat", "noun"),
        ("空", "sora", "langit", "noun"),
        ("それ", "sore", "itu", "pronoun"),
        ("それから", "sore kara", "setelah itu", "conjunction"),
        ("大学", "daigaku", "universitas", "noun"),
        ("大使館", "taishikan", "kedutaan", "noun"),
        ("大丈夫", "daijoubu", "tidak apa-apa", "na_adj"),
        ("大好き", "daisuki", "sangat suka", "na_adj"),
        ("大切", "taisetsu", "penting", "na_adj"),
        ("台所", "daidokoro", "dapur", "noun"),
        ("たいへん", "taihen", "sulit, sangat", "adverb"),
        ("高い", "takai", "tinggi, mahal", "i_adj"),
        ("たくさん", "takusan", "banyak", "adverb"),
        ("タクシー", "takushii", "taksi", "noun"),
        ("出す", "dasu", "mengeluarkan", "godan"),
        ("立つ", "tatsu", "berdiri", "godan"),
        ("建物", "tatemono", "bangunan", "noun"),
        ("楽しい", "tanoshii", "menyenangkan", "i_adj"),
        ("頼む", "tanomu", "meminta", "godan"),
        ("多分", "tabun", "mungkin", "adverb"),
        ("食べ物", "tabemono", "makanan", "noun"),
        ("食べる", "taberu", "makan", "ichidan"),
        ("卵", "tamago", "telur", "noun"),
        ("誰", "dare", "siapa", "pronoun"),
        ("誰か", "dareka", "seseorang", "pronoun"),
        ("誕生日", "tanjoubi", "ulang tahun", "noun"),
        ("小さい", "chiisai", "kecil", "i_adj"),
        ("近い", "chikai", "dekat", "i_adj"),
        ("違う", "chigau", "berbeda", "godan"),
        ("地下鉄", "chikatetsu", "mrt", "noun"),
        ("地図", "chizu", "peta", "noun"),
        ("茶色", "chairo", "coklat", "noun"),
        ("ちょうど", "choudo", "tepat", "adverb"),
        ("ちょっと", "chotto", "sebentar", "adverb"),
        ("使う", "tsukau", "menggunakan", "godan"),
        ("疲れる", "tsukareru", "lelah", "ichidan"),
        ("次", "tsugi", "berikutnya", "noun"),
        ("机", "tsukue", "meja", "noun"),
        ("作る", "tsukuru", "membuat", "godan"),
        ("つける", "tsukeru", "menyalakan", "ichidan"),
        ("勤める", "tsutomeru", "bekerja", "ichidan"),
        ("つまらない", "tsumaranai", "membosankan", "i_adj"),
        ("冷たい", "tsumetai", "dingin", "i_adj"),
        ("強い", "tsuyoi", "kuat", "i_adj"),
        ("手", "te", "tangan", "noun"),
        ("テープ", "teepu", "kaset", "noun"),
        ("テーブル", "teeburu", "meja", "noun"),
        ("手紙", "tegami", "surat", "noun"),
        ("できる", "dekiru", "bisa", "ichidan"),
        ("出口", "deguchi", "pintu keluar", "noun"),
        ("テスト", "tesuto", "tes", "noun"),
        ("では", "dewa", "kalau begitu", "conjunction"),
        ("デパート", "depaato", "toserba", "noun"),
        ("でも", "demo", "tetapi", "conjunction"),
        ("出かける", "dekakeru", "pergi keluar", "ichidan"),
        ("出る", "deru", "keluar", "ichidan"),
        ("テレビ", "terebi", "tv", "noun"),
        ("天気", "tenki", "cuaca", "noun"),
        ("電気", "denki", "listrik", "noun"),
        ("電車", "densha", "kereta", "noun"),
        ("電話", "denwa", "telepon", "noun"),
        ("戸", "to", "pintu", "noun"),
        ("ドア", "doa", "pintu", "noun"),
        ("トイレ", "toire", "toilet", "noun"),
        ("どう", "dou", "bagaimana", "adverb"),
        ("どうして", "doushite", "mengapa", "adverb"),
        ("どうぞ", "douzo", "silakan", "other"),
        ("動物", "doubutsu", "binatang", "noun"),
        ("どうも", "doumo", "terima kasih", "other"),
        ("十", "tou", "sepuluh", "noun"),
        ("遠い", "tooi", "jauh", "i_adj"),
        ("時", "toki", "saat", "noun"),
        ("時々", "tokidoki", "kadang-kadang", "adverb"),
        ("時計", "tokei", "jam", "noun"),
        ("どこ", "doko", "di mana", "pronoun"),
        ("所", "tokoro", "tempat", "noun"),
        ("図書館", "toshokan", "perpustakaan", "noun"),
        ("どちら", "dochira", "yang mana", "pronoun"),
        ("とても", "totemo", "sangat", "adverb"),
        ("どなた", "donata", "siapa", "pronoun"),
        ("となり", "tonari", "sebelah", "noun"),
        ("どの", "dono", "yang mana", "pronoun"),
        ("飛ぶ", "tobu", "terbang", "godan"),
        ("止まる", "tomaru", "berhenti", "godan"),
        ("友達", "tomodachi", "teman", "noun"),
        ("土曜日", "doyoubi", "sabtu", "noun"),
        ("鳥", "tori", "burung", "noun"),
        ("とり肉", "toriniku", "daging ayam", "noun"),
        ("取る", "toru", "mengambil", "godan"),
        ("撮る", "toru", "memotret", "godan"),
        ("どれ", "dore", "yang mana", "pronoun"),
        ("どんな", "donna", "yang bagaimana", "pronoun"),
        ("ない", "nai", "tidak ada", "other"),
        ("ナイフ", "naifu", "pisau", "noun"),
        ("中", "naka", "dalam", "noun"),
        ("長い", "nagai", "panjang", "i_adj"),
        ("なく", "naku", "menangis", "godan"),
        ("無くす", "nakusu", "menghilangkan", "godan"),
        ("夏", "natsu", "musim panas", "noun"),
        ("など", "nado", "dan lain-lain", "other"),
        ("名前", "namae", "nama", "noun"),
        ("習う", "narau", "belajar", "godan"),
        ("並ぶ", "narabu", "berbaris", "godan"),
        ("並べる", "naraberu", "menyusun", "ichidan"),
        ("なる", "naru", "menjadi", "godan"),
        ("何", "nan", "apa", "pronoun"),
        ("二", "ni", "dua", "noun"),
        ("賑やか", "nigiyaka", "ramai", "na_adj"),
        ("肉", "niku", "daging", "noun"),
        ("西", "nishi", "barat", "noun"),
        ("日曜日", "nichiyoubi", "minggu", "noun"),
        ("荷物", "nimotsu", "barang", "noun"),
        ("ニュース", "nyuusu", "berita", "noun"),
        ("庭", "niwa", "halaman", "noun"),
        ("脱ぐ", "nugu", "melepas", "godan"),
        ("ネクタイ", "nekutai", "dasi", "noun"),
        ("猫", "neko", "kucing", "noun"),
        ("寝る", "neru", "tidur", "ichidan"),
        ("ノート", "nooto", "catatan", "noun"),
        ("登る", "noboru", "mendaki", "godan"),
        ("飲み物", "nomimono", "minuman", "noun"),
        ("飲む", "nomu", "minum", "godan"),
        ("乗る", "noru", "naik", "godan"),
        ("歯", "ha", "gigi", "noun"),
        ("パーティー", "paatii", "pesta", "noun"),
        ("はい", "hai", "ya", "other"),
        ("灰皿", "haizara", "asbak", "noun"),
        ("入る", "hairu", "masuk", "godan"),
        ("はく", "haku", "memakai", "godan"),
        ("箱", "hako", "kotak", "noun"),
        ("橋", "hashi", "jembatan", "noun"),
        ("はし", "hashi", "sumpit", "noun"),
        ("始まる", "hajimaru", "dimulai", "godan"),
        ("初めて", "hajimete", "pertama kali", "adverb"),
        ("走る", "hashiru", "berlari", "godan"),
        ("バス", "basu", "bus", "noun"),
        ("バター", "bataa", "mentega", "noun"),
        ("働く", "hataraku", "bekerja", "godan"),
        ("八", "hachi", "delapan", "noun"),
        ("花", "hana", "bunga", "noun"),
        ("鼻", "hana", "hidung", "noun"),
        ("話", "hanashi", "cerita", "noun"),
        ("話す", "hanasu", "berbicara", "godan"),
        ("早い", "hayai", "cepat", "i_adj"),
        ("春", "haru", "musim semi", "noun"),
        ("貼る", "haru", "menempel", "godan"),
        ("晴れ", "hare", "cerah", "noun"),
        ("晴れる", "hareru", "menjadi cerah", "ichidan"),
        ("半", "han", "setengah", "noun"),
        ("晩", "ban", "malam", "noun"),
        ("パン", "pan", "roti", "noun"),
        ("番号", "bangou", "nomor", "noun"),
        ("晩御飯", "bangohan", "makan malam", "noun"),
        ("半分", "hanbun", "setengah", "noun"),
        ("東", "higashi", "timur", "noun"),
        ("引く", "hiku", "menarik", "godan"),
        ("低い", "hikui", "rendah", "i_adj"),
        ("飛行機", "hikouki", "pesawat", "noun"),
        ("左", "hidari", "kiri", "noun"),
        ("人", "hito", "orang", "noun"),
        ("一つ", "hitotsu", "satu buah", "counter"),
        ("ひとり", "hitori", "satu orang", "noun"),
        ("暇", "hima", "senggang", "na_adj"),
        ("百", "hyaku", "seratus", "noun"),
        ("病院", "byouin", "rumah sakit", "noun"),
        ("病気", "byouki", "sakit", "noun"),
        ("昼", "hiru", "siang", "noun"),
        ("昼ご飯", "hirugohan", "makan siang", "noun"),
        ("広い", "hiroi", "luas", "i_adj"),
        ("封筒", "fuutou", "amplop", "noun"),
        ("プール", "puuru", "kolam renang", "noun"),
        ("フォーク", "fooku", "garpu", "noun"),
        ("吹く", "fuku", "bertiup", "godan"),
        ("服", "fuku", "pakaian", "noun"),
        ("二つ", "futatsu", "dua buah", "counter"),
        ("豚肉", "butaniku", "daging babi", "noun"),
        ("二人", "futari", "dua orang", "noun"),
        ("太い", "futoi", "gemuk", "i_adj"),
        ("冬", "fuyu", "musim dingin", "noun"),
        ("降る", "furu", "turun", "godan"),
        ("古い", "furui", "lama", "i_adj"),
        ("文章", "bunshou", "kalimat", "noun"),
        ("ページ", "peeji", "halaman", "noun"),
        ("下手", "heta", "tidak pandai", "na_adj"),
        ("ベッド", "beddo", "kasur", "noun"),
        ("ペット", "petto", "peliharaan", "noun"),
        ("部屋", "heya", "kamar", "noun"),
        ("ペン", "pen", "pena", "noun"),
        ("勉強", "benkyou", "belajar", "suru"),
        ("便利", "benri", "praktis", "na_adj"),
        ("帽子", "boushi", "topi", "noun"),
        ("ほか", "hoka", "lain", "noun"),
        ("欲しい", "hoshii", "ingin", "i_adj"),
        ("細い", "hosoi", "kurus", "i_adj"),
        ("ボタン", "botan", "tombol", "noun"),
        ("ホテル", "hoteru", "hotel", "noun"),
        ("本", "hon", "buku", "noun"),
        ("本棚", "hondana", "rak buku", "noun"),
        ("本当", "hontou", "benar", "na_adj"),
        ("毎朝", "maiasa", "setiap pagi", "noun"),
        ("毎月", "maigetsu", "setiap bulan", "noun"),
        ("毎週", "maishuu", "setiap minggu", "noun"),
        ("毎日", "mainichi", "setiap hari", "noun"),
        ("毎年", "mainen", "setiap tahun", "noun"),
        ("毎晩", "maiban", "setiap malam", "noun"),
        ("前", "mae", "depan", "noun"),
        ("曲がる", "magaru", "belok", "godan"),
        ("まずい", "mazui", "tidak enak", "i_adj"),
        ("また", "mata", "lagi", "adverb"),
        ("まだ", "mada", "belum", "adverb"),
        ("町", "machi", "kota", "noun"),
        ("待つ", "matsu", "menunggu", "godan"),
        ("真っ直ぐ", "massugu", "lurus", "na_adj"),
        ("窓", "mado", "jendela", "noun"),
        ("万", "man", "sepuluh ribu", "noun"),
        ("磨く", "migaku", "menggosok", "godan"),
        ("右", "migi", "kanan", "noun"),
        ("短い", "mijikai", "pendek", "i_adj"),
        ("水", "mizu", "air", "noun"),
        ("店", "mise", "toko", "noun"),
        ("見せる", "miseru", "memperlihatkan", "ichidan"),
        ("道", "michi", "jalan", "noun"),
        ("三つ", "mittsu", "tiga buah", "counter"),
        ("緑", "midori", "hijau", "noun"),
        ("皆さん", "minasan", "semuanya", "pronoun"),
        ("南", "minami", "selatan", "noun"),
        ("耳", "mimi", "telinga", "noun"),
        ("見る", "miru", "melihat", "ichidan"),
        ("みんな", "minna", "semua", "pronoun"),
        ("向こう", "mukou", "seberang", "noun"),
        ("難しい", "muzukashii", "sulit", "i_adj"),
        ("六つ", "muttsu", "enam buah", "counter"),
        ("村", "mura", "desa", "noun"),
        ("目", "me", "mata", "noun"),
        ("眼鏡", "megane", "kacamata", "noun"),
        ("もう", "mou", "sudah", "adverb"),
        ("もしもし", "moshimoshi", "halo", "other"),
        ("持つ", "motsu", "membawa", "godan"),
        ("もっと", "motto", "lebih", "adverb"),
        ("物", "mono", "benda", "noun"),
        ("門", "mon", "gerbang", "noun"),
        ("問題", "mondai", "masalah", "noun"),
        ("八百屋", "yaoya", "toko sayur", "noun"),
        ("野菜", "yasai", "sayuran", "noun"),
        ("易しい", "yasashii", "mudah", "i_adj"),
        ("安い", "yasui", "murah", "i_adj"),
        ("休み", "yasumi", "istirahat", "noun"),
        ("休む", "yasumu", "beristirahat", "godan"),
        ("八つ", "yattsu", "delapan buah", "counter"),
        ("山", "yama", "gunung", "noun"),
        ("やる", "yaru", "melakukan", "godan"),
        ("夕方", "yuugata", "sore", "noun"),
        ("夕飯", "yuuhan", "makan malam", "noun"),
        ("郵便局", "yuubinkyoku", "kantor pos", "noun"),
        ("有名", "yuumei", "terkenal", "na_adj"),
        ("雪", "yuki", "salju", "noun"),
        ("ゆっくり", "yukkuri", "pelan-pelan", "adverb"),
        ("洋服", "youfuku", "pakaian", "noun"),
        ("よく", "yoku", "sering", "adverb"),
        ("横", "yoko", "samping", "noun"),
        ("四つ", "yottsu", "empat buah", "counter"),
        ("呼ぶ", "yobu", "memanggil", "godan"),
        ("読む", "yomu", "membaca", "godan"),
        ("夜", "yoru", "malam", "noun"),
        ("弱い", "yowai", "lemah", "i_adj"),
        ("来月", "raigetsu", "bulan depan", "noun"),
        ("来週", "raishuu", "minggu depan", "noun"),
        ("来年", "rainen", "tahun depan", "noun"),
        ("ラジオ", "rajio", "radio", "noun"),
        ("りっぱ", "rippa", "bagus", "na_adj"),
        ("留学生", "ryuugakusei", "siswa asing", "noun"),
        ("料理", "ryouri", "masakan", "noun"),
        ("旅行", "ryokou", "perjalanan", "suru"),
        ("冷蔵庫", "reizouko", "kulkas", "noun"),
        ("レストラン", "resutoran", "restoran", "noun"),
        ("練習", "renshuu", "latihan", "suru"),
        ("六", "roku", "enam", "noun"),
        ("若い", "wakai", "muda", "i_adj"),
        ("分かる", "wakaru", "mengerti", "godan"),
        ("忘れる", "wasureru", "lupa", "ichidan"),
        ("私", "watashi", "saya", "pronoun"),
        ("渡す", "watasu", "menyerahkan", "godan"),
        ("わたる", "wataru", "menyeberang", "godan"),
        ("悪い", "warui", "buruk", "i_adj"),
        ("乗り物", "norimono", "kendaraan", "noun"),
    ]

    # Add standard words to final_list if they are not already there
    for w, r, m, t in standard_n5:
        key = (w, r)
        if key not in seen:
            final_list.append({
                'word': w, 
                'reading': r, 
                'meaning': m,
                'word_type': t
            })
            seen.add(key)

# Final adjustment to reach exactly 594
print(f"Count after adding standard: {len(final_list)}")
if len(final_list) > 594:
    final_list = final_list[:594]
elif len(final_list) < 594:
    # If still less, we might need more words. 
    # But with rspsensei + standard, we should be over 594.
    pass

# Save to JSON
with open('/home/imron/jbook/backend/scripts/n5_594.json', 'w') as f:
    json.dump(final_list, f, ensure_ascii=False, indent=2)

print(f"Final count saved: {len(final_list)}")
