import json
import re

# Data extracted from tool outputs (manually compiled chunks)
raw_data = []

# Page 1
raw_data.extend([
    (1, '～ごろ', '～goro', 'sekitar～, kira-kira'), (2, '～すぎ', '～sugi', 'terlalu (banyak)～'),
    (3, '～ずつ', '～ zutsu', '～per～'), (4, '～たち', '～tachi', 'para～, dkk'),
    (5, '～中', '～chuu/～juu', 'dalam～(kurun waktu)'), (6, '～中', '～chuu/juu', 'sedang'),
    (7, '～個', '～ko', '～buah,～butir'), (8, '～側', '～gawa', 'bagian～'),
    (9, '～冊', '～satsu', '～buah (buku, kamus)'), (10, '～台', '～dai', '～unit'),
    (11, '～回', '～kai', '～kali'), (12, '～屋', '～ya', 'toko'),
    (13, '～時', '～ji', 'jam'), (14, '～杯', '～hai/～pai', '～gelas'),
    (15, '～歳', '～sai', '～tahun (umur)'), (16, '～階', '～kai', 'lantai～'),
    (17, '３万円', 'San man en', 'tiga puluh ribu yen'), (18, 'あさって', 'asatte', 'besok lusa'),
    (19, 'あちら', 'achira', 'disana ( jauh ) sopan'), (20, 'あっち', 'acchi', 'disana ( jauh ) informal'),
    (21, 'あなた', 'anata', 'kamu, anda'), (22, 'アパート', 'apaato', 'apartment'),
    (23, 'あまり', 'amari', 'tidak begitu'), (24, 'ある', 'aru', 'ada ( benda mati )'),
    (25, 'あれ', 'are', 'itu ( jauh )'), (26, 'いい', 'ii', 'bagus'),
    (27, 'いくつ', 'ikutsu', 'berapa'), (28, 'いくら', 'ikura', 'berapa harganya'),
    (29, '椅子', 'isu', 'kursi'), (30, 'いつ', 'itsu', 'kapan'),
    (31, 'いつか', 'itsuka', 'suatu saat'), (32, 'いつも', 'itsumo', 'selalu'),
    (33, 'いる', 'iru', 'ada ( orang )'), (34, '色々', 'iroiro', 'bermacam-macam'),
    (35, '内', 'uchi', 'dalam'), (36, 'うるさい', 'urusai', 'berisik'),
    (37, 'ええ', 'ee', 'ya'), (38, '美味しい', 'oishii', 'enak'),
    (39, 'お菓子', 'okashi', 'cemilan'), (40, '起きる', 'okiru', 'bangun'),
    (41, '一昨日', 'ototoi', '2 hari yang lalu'), (42, '一昨年', 'ototoshi', '2 tahun yang lalu'),
    (43, '面白い', 'omoshiroi', 'menarik'), (44, 'お兄さん', 'oniisan', 'kakak laki-laki ( orang lain )'),
    (45, 'お回り', 'omawari', 'sekitar'), (46, 'お姉さん', 'oneesan', 'kakak perempuan ( orang lain )'),
    (47, 'お弁当', 'obentou', 'bekal makanan'), (48, 'お手洗い', 'otearai', 'toilet, kamar kecil'),
    (49, 'お母さん', 'okaasan', 'ibu ( orang lain )'), (50, 'お父さん', 'otousan', 'ayah ( orang lain )'),
    (51, 'お皿', 'osara', 'piring'), (52, 'お茶', 'ocha', 'teh hijau'),
    (53, 'お酒', 'osake', 'arak Jepang'), (54, 'お金', 'okane', 'uang'),
    (55, 'お風呂', 'ofuro', 'ofuro ( bak mandi )'), (56, 'かける', 'kakeru', 'memakai ( kacamata )'),
    (57, '傘', 'kasa', 'payung'), (58, 'ガスストーブ', 'Gasu sutoobu', 'Kompor gas'),
    (59, 'カタカナ', 'katakana', 'huruf katakana'), (60, 'カップ', 'kappu', 'gelas'),
    (61, 'かばん', 'kaban', 'tas'), (62, 'かびん', 'kabin', 'vas bunga'),
    (63, 'かぶる', 'kaburu', 'memakai topi'), (64, 'カメラ', 'kamera', 'kamera'),
    (65, 'カレンダー', 'karendaa', 'kalender'), (66, '可愛い', 'kawaii', 'lucu, imut'),
    (67, 'ギター', 'gitaa', 'gitar'), (68, '汚い', 'kitanai', 'kotor, jorok'),
    (69, '切手', 'kitte', 'perangko'), (70, '昨日', 'kinou', 'kemarin'),
    (71, '嫌い', 'kirai', 'tidak suka, benci'), (72, 'きれい', 'kirei', 'cantik, indah'),
    (73, 'キロ', 'kiro', 'kilo'), (74, 'ぐらい', 'gurai', 'kira-kira'),
    (75, 'クラス', 'kurasu', 'kelas'), (76, 'グラム', 'guramu', 'gram'),
    (77, 'ヶ月', 'kagetsu', '～bulan'), (78, 'コーヒー', 'koohii', 'kopi'),
    (79, '午後', 'gogo', 'siang (.p.m)'), (80, 'こちら', 'kochira', 'di sini'),
    (81, 'こっち', 'kocchi', 'di sini ( informal )'), (82, 'こっちきて', 'Kocchi kite', 'Datang sini!'),
    (83, 'コップ', 'koppu', 'cangkir'), (84, 'コピーする', 'kopii suru', 'menyalin, memfotokopi'),
    (85, 'こんな', 'konna', '～yang seperti ini, ～segini'), (86, 'ご飯', 'gohan', 'nasi'),
    (87, 'しかし', 'shikashi', 'tapi'), (88, '醤油', 'shouyu', 'kecap asin'),
    (89, 'すぐ', 'sugu', 'segera'), (90, '少し', 'sukoshi', 'sedikit'),
    (91, 'ストーブ', 'sutobu', 'kompor'), (92, 'スプーン', 'supuun', 'sendok'),
    (93, 'スポーツ', 'supootsu', 'Olah raga'), (94, 'スリッパ', 'surippa', 'Sandal dalam rumah'),
    (95, 'そして', 'soshite', 'dan, lalu'), (96, 'そっち', 'socchi', 'disana ( jauh ) informal'),
    (97, 'そば', 'soba', 'samping'), (98, 'それから', 'sore kara', 'lalu, setelah itu'),
    (99, 'それでは', 'soredewa', 'baiklah'), (100, 'タイ', 'tai', 'Thailand'),
    (101, '台所', 'dai dokoro', 'dapur')
])

# Page 2
raw_data.extend([
    (102, 'たくさん', 'takusan', 'banyak'), (103, 'だけ', 'dake', 'hanya'),
    (104, 'タバコ', 'tabako', 'rokok'), (105, '多分', 'tabun', 'mungkin'),
    (106, 'だれ', 'dare', 'siapa'), (107, 'だれか', 'dare ka', 'seseorang'),
    (108, 'ちょうど', 'choudo', 'pas, tepat'), (109, 'ちょっと', 'chotto', 'Sedikit, sebentar'),
    (110, 'つまらない', 'tsumaranai', 'Membosankan'), (111, 'テーブル', 'teeburu', 'meja'),
    (112, 'テスト', 'tesuto', 'tes, ujian'), (113, 'では', 'dewa', 'baiklah'),
    (114, 'デパート', 'depaato', 'toserba'), (115, 'でも', 'demo', 'tapi'),
    (116, 'どうして', 'doushite', 'mengapa, kenapa'), (117, 'どうぞ', 'douzo', 'silahkan'),
    (118, 'どうmo', 'doumo', 'terima kasih'), (119, 'ときどき', 'tokidoki', 'kadang-kadang'),
    (120, '所', 'tokoro', 'tempat'), (121, 'どなた', 'donata', 'siapa ( bentuk sopan )'),
    (122, 'どの', 'dono', 'yang mana'), (123, 'どれ', 'dore', 'yang mana'),
    (124, 'どんな', 'donna', 'yang bagaimana'), (125, 'ない', 'nai', 'tidak punya, tidak ada'),
    (126, 'ナイフ', 'naifu', 'pisau'), (127, '泣く', 'naku', 'menangis'),
    (128, 'なぜ', 'naze', 'mengapa'), (129, 'など', 'nado', 'dan lain-lain'),
    (130, 'なる', 'naru', 'menjadi'), (131, 'にぎやか', 'nigiyaka', 'ramai'),
    (132, 'ネクタイ', 'nekutai', 'dasi'), (133, 'パーティー', 'paatii', 'pesta'),
    (134, 'プール', 'puuru', 'Kolam renang'), (135, 'フォーク', 'fooku', 'garpu'),
    (136, 'ページ', 'peeji', 'Halaman'), (137, 'ベッド', 'beddo', 'Kasur'),
    (138, 'ペット', 'petto', 'hewan peliharaan'), (139, 'ペットの店', 'Petto no mise', 'Toko hewan peliharaan'),
    (140, '帽子', 'boushi', 'Topi'), (141, 'ほしい', 'hoshii', 'Ingin'),
    (142, 'ポスト', 'posuto', 'kotak pos'), (143, 'ボタン', 'botan', 'Tombol'),
    (144, 'ホテル', 'hoteru', 'Hotel'), (145, 'まずい', 'mazui', 'Tidak enak'),
    (146, 'また', 'mata', 'lagi'), (147, 'まだ', 'mada', 'Belum, masih'),
    (148, 'まっすぐ', 'massugu', 'Lurus'), (149, 'メートル', 'meetoru', 'Meter'),
    (150, 'めがね', 'megane', 'Kacamata'), (151, 'もしもし', 'moshimoshi', 'Halo ( saat telpon )'),
    (152, 'もっと', 'motto', 'Lebih, dan lagi'), (153, 'やる', 'yaru', 'Melakukan, mengerjakan'),
    (154, '一人ずつ', 'Hitorizutsu', 'satu orang per satu orang'), (155, '一日', 'ichinichi', 'satu hari'),
    (156, '一番', 'ichiban', 'paling , no 1'), (157, '一緒に', 'isshoni', 'bersama'),
    (158, '万', 'man', 'sepuluh ribu'), (159, '丈夫', 'joubu', 'Kokoh, kuat, sehat'),
    (160, '上げる', 'ageru', 'menaikan'), (161, '上手', 'jouzu', 'terampil, mahir'),
    (162, '上着', 'uwagi', 'baju , Jas'), (163, '下手', 'heta', 'tidak pandai'),
    (164, '並ぶ', 'narabu', 'berbaris, berjajar'), (165, '並べる', 'naraberu', 'menjajarkan'),
    (166, '中', 'naka', 'dalam'), (167, '丸い', 'marui', 'Bulat, bundar'),
    (168, '乗る', 'noru', 'naik ( kendaraan )'), (169, '交差点', 'kousaten', 'persimpangan'),
    (170, '交番', 'kouban', 'pos polisi'), (171, '今', 'ima', 'sekarang'),
    (172, '今年', 'kotoshi', 'tahun ini'), (173, '今日', 'kyou', 'hari ini'),
    (174, '今晩', 'konban', 'malam ini'), (175, '今月', 'kongetsu', 'bulan ini'),
    (176, '今朝', 'kesa', 'tadi pagi'), (177, '今週', 'konshuu', 'minggu ini'),
    (178, '仕事', 'shigoto', 'pekerjaan'), (179, '他', 'hoka', 'yang lain'),
    (180, '他の人', 'Hoka no hito', 'Orang lain'), (181, '休み', 'yasumi', 'Libur'),
    (182, '休む', 'yasumu', 'beristirahat'), (183, '会う', 'au', 'bertemu'),
    (184, '会社', 'kaisha', 'perusahaan'), (185, '低い', 'hikui', 'Rendah / pendek'),
    (186, '低い山', 'Hikui yama', 'Gunung rendah'), (187, '住む', 'sumu', 'tinggal, bermukim'),
    (188, '体', 'karada', 'badan, tubuh'), (189, '作る', 'tsukuru', 'membuat'),
    (190, '作文', 'sakubun', 'karangan'), (191, '使う', 'tsukau', 'memakai'),
    (192, '便利', 'benri', 'Praktis, mudah'), (193, '借りる', 'kariru', 'meminjam'),
    (194, '元気', 'genki', 'sehat'), (195, '兄', 'ani', 'kakak laki-laki saya'),
    (196, '兄弟', 'kyoudai', 'saudara, adik kakak'), (197, '先月', 'sengetsu', 'bulan lalu'),
    (198, '先週', 'senshuu', 'minggu lalu'), (199, '入り口', 'iriguchi', 'pintu masuk'),
    (200, '入れる', 'ireru', 'memasukan')
])

# Page 3
raw_data.extend([
    (201, '全部', 'zenbu', 'semua'), (202, '八百屋', 'yaoya', 'Toko sayuran'),
    (203, '公園', 'kouen', 'taman'), (204, '円', 'en', 'yen'),
    (205, '再来年', 'sarainen', '2 tahun yang akan datang'), (206, '冬', 'fuyu', 'Musim dingin'),
    (207, '冷たい', 'tsumetai', 'Dingin'), (208, '出かける', 'dekakeru', 'keluar, bepergian'),
    (209, '出す', 'dasu', 'mengeluarkan'), (210, '出る', 'deru', 'keluar'),
    (211, '出口', 'deguchi', 'pintu keluar'), (212, '切符', 'kippu', 'tiket'),
    (213, '初めて', 'Hajimete', 'pertama kali'), (214, '勉強する', 'benkyou suru', 'belajar'),
    (215, '医者', 'isha', 'dokter'), (216, '午前', 'gozen', 'pagi (a.m.)'),
    (217, '半', 'han', 'Setengah'), (218, '半分', 'hanbun', 'Setengah'),
    (219, '南', 'minami', 'Selatan'), (220, '南口', 'Minamiguchi', 'Pintu Selatan'),
    (221, '危ない', 'abunai', 'bahaya'), (222, '卵', 'tamago', 'telur'),
    (223, '厚い', 'atsui', 'tebal'), (224, '去年', 'kyonen', 'tahun lalu'),
    (225, '友達', 'tomodachi', 'teman'), (226, '取る', 'toru', 'mengambil / mendapatkan/ meraih'),
    (227, '古い', 'furui', 'Tua, usang'), (228, '右', 'migi', 'Kanan'),
    (229, '同じ', 'onaji', 'sama'), (230, '向こう', 'mukou', 'Seberang'),
    (231, '吸う', 'suu', 'mengisap'), (232, '咲く', 'saku', 'mekar'),
    (233, '問題', 'mondai', 'Masalah'), (234, '喫茶店', 'kissaten', 'cafe'),
    (235, '困る', 'komaru', 'khawatir, susah'), (236, '図書館', 'toshokan', 'perpustakaan'),
    (237, '国', 'kuni', 'negara'), (238, '地図', 'chizu', 'peta'),
    (239, '塩', 'shio', 'Garam'), (240, '声', 'koe', 'suara'),
    (241, '売る', 'uru', 'menjual'), (242, '夏', 'natsu', 'musim panas'),
    (243, '夕べ', 'yuube', 'Tadi malam'), (244, '夕方', 'yuugata', 'Sore'),
    (245, '夕飯', 'yuuhan', 'Makan malam'), (246, '外', 'soto', 'luar'),
    (247, '外国', 'gaikoku', 'luar negeri'), (248, '外国人', 'gaikokujin', 'orang asing'),
    (249, '多い', 'ooi', 'banyak'), (250, '大きい', 'ookii', 'besar'),
    (251, '大きな', 'ookina', 'yang besar'), (252, '大丈夫', 'daijoubu', 'tidak apa-apa'),
    (253, '大人', 'otona', 'dewasa'), (254, '大使館', 'taishikan', 'kedutaan'),
    (255, '大切', 'taisetsu', 'penting'), (256, '大勢', 'oozei', 'banyak'),
    (257, '大変', 'taihen', 'berat, susah'), (258, '大好き', 'daisuki', 'sangat suka'),
    (259, '天気', 'tenki', 'cuaca'), (260, '太い', 'futoi', 'Gendut, gemuk'),
    (261, '太い足', 'Futoi ashi', 'Kaki besar, gemuk'), (262, '奥さん', 'okusan', 'istri anda'),
    (263, '女', 'onna', 'perempuan'), (264, '女の子', 'onna no ko', 'anak perempuan'),
    (265, '好き', 'suki', 'suka'), (266, '妹', 'imouto', 'adik perempuan'),
    (267, '姉', 'ane', 'kakak perempuan saya'), (268, '始まる', 'Hajimaru', 'Dimulai'),
    (269, '嫌', 'iya', 'tidak mau, tidak suka'), (270, '子供', 'kodomo', 'anak kecil'),
    (271, '学校', 'gakkou', 'sekolah'), (272, '学生', 'gakusei', 'murid'),
    (273, '安い', 'yasui', 'Murah'), (274, '家', 'ie', 'rumah'),
    (275, '家庭', 'katei', 'rumah tangga'), (276, '家族', 'kazoku', 'keluarga'),
    (277, '宿題', 'shukudai', 'PR (pekerjaan rumah)'), (278, '寒い', 'samui', 'dingin'),
    (279, '封筒', 'fuutou', 'Amplop'), (280, '小さい', 'chiisai', 'kecil'),
    (281, '小さな', 'chiisana', 'kecil'), (282, '少ない', 'sukunai', 'sedikit'),
    (283, '川', 'kawa', 'sungai'), (284, '帰る', 'kaeru', 'pulang'),
    (285, '広い', 'hiroi', 'Lebar, luas'), (286, '広い庭', 'Hiroi niwa', 'Halaman rumah yang luas'),
    (287, '店', 'mise', 'toko'), (288, '度', 'do', 'derajat'),
    (289, '座る', 'suwaru', 'duduk'), (290, '庭', 'niwa', 'halaman ( rumah )'),
    (291, '建物', 'tatemono', 'bangunan'), (292, '弟', 'otouto', 'adik laki-laki ( sendiri )'),
    (293, '強い', 'tsuyoi', 'kuat'), (294, '弾く', 'hiku', 'memetik (alat musik)'),
    (295, '待つ', 'matsu', 'menunggu'), (296, '後ろ', 'ushiro', 'belakang'),
    (297, '忙しい', 'isogashii', 'sibuk'), (298, '意味', 'imi', 'arti'),
    (299, '戸', 'to', 'pintu'), (300, '手', 'te', 'tangan')
])

# Page 4
raw_data.extend([
    (301, '手紙', 'tegami', 'surat'), (302, '押す', 'osu', 'mendorong'),
    (303, '授業', 'jugyou', 'pelajaran'), (304, '撮る', 'Toru', 'mengambil (foto)'),
    (305, '教える', 'oshieru', 'mengajarkan'), (306, '教室', 'kyoushistu', 'kelas'),
    (307, '散歩する', 'sanpo suru', 'jalan-jalan santai'), (308, '文章', 'bunshou', 'Kalimat'),
    (309, '新しい', 'atarashii', 'baru'), (310, '方', 'Hou', 'yang ～, arah'),
    (311, '方', 'kata', 'Orang (bentuk sopan)'), (312, '日本語', 'nihongo', 'bahasa Jepang'),
    (313, '早い', 'hayai', 'Cepat'), (314, '早く走る', 'Hayaku hashiru', 'Berlari/melaju dengan cepat'),
    (315, '明るい', 'akarui', 'terang'), (316, '明日', 'ashita', 'besok'),
    (317, '映画', 'eiga', 'film, sinema'), (318, '映画館', 'eigakan', 'bioskop'),
    (319, '春', 'haru', 'Musim semi'), (320, '昼', 'hiru', 'Siang'),
    (321, '昼ご飯', 'hiru gohan', 'Makan siang'), (322, '時計', 'tokei', 'jam'),
    (323, '時間', 'jikan', 'waktu'), (324, '晴れ', 'hare', 'cerah'),
    (325, '晴れる', 'hareru', 'cerah'), (326, '暑い', 'atsui', 'panas ( suhu )'),
    (327, '暖かい', 'atatakai', 'hangat'), (328, '暗い', 'kurai', 'gelap'),
    (329, '曇り', 'kumori', 'berawan, mendung'), (330, '曲がる', 'magaru', 'Belok'),
    (331, '書く', 'kaku', 'menulis'), (332, '月', 'tsuki', 'bulan (dilangit)'),
    (333, '月曜日', 'getsuyoubi', 'hari senin'), (334, '有名', 'yuumei', 'Terkenal'),
    (335, '朝ごはん', 'asagohan', 'sarapan pagi'), (336, '朝ご飯', 'Asa gohan', 'Sarapan pagi'),
    (337, '木', 'ki', 'pohon'), (338, '本当', 'hontou', 'Benar'),
    (339, '本当の話', 'Hontou no hanashi', 'Omongan yang benar'), (340, '机', 'tsukue', 'meja'),
    (341, '来る', 'kuru', 'datang'), (342, '果物', 'kudamono', 'buah-buahan'),
    (343, '楽しい', 'tanoshii', 'menyenangkan'), (344, '次', 'tsugi', 'selanjutnya'),
    (345, '次のページ', 'Tsugi no peeji', 'Halaman selanjutnya'), (346, '歌', 'uta', 'lagu'),
    (347, '歌う', 'utau', 'bernyanyi'), (348, '歩く', 'aruku', 'berjalan'),
    (349, '死ぬ', 'shinu', 'mati'), (350, '水', 'mizu', 'Air'),
    (351, '水を飲む', 'Mizu wo nomu', 'Minum air'), (352, '池', 'ike', 'kolam'),
    (353, '泳ぐ', 'oyogu', 'berenang'), (354, '洗う', 'arau', 'mencuci'),
    (355, '洗濯', 'sentaku', 'mencuci'), (356, '海', 'umi', 'laut'),
    (357, '消える', 'kieru', 'padam'), (358, '消す', 'kesu', 'mematikan'),
    (359, '涼しい', 'suzushii', 'sejuk'), (360, '漢字', 'kanji', 'kanji (huruf Cina)'),
    (361, '灰皿', 'Haizara', 'Asbak'), (362, '父', 'chichi', 'ayah'),
    (363, '牛乳', 'gyuunyuu', 'susu sapi'), (364, '牛肉', 'gyuuniku', 'daging sapi'),
    (365, '物', 'mono', 'Barang'), (366, '物を買う', 'Mono o kau', 'Membeli (suatu) barang'),
    (367, '犬', 'inu', 'anjing'), (368, '狭い', 'semai', 'sempit'),
    (369, '玄関', 'genkan', 'pintu masuk (tempat melepas sepatu)'), (370, '甘い', 'amai', 'manis'),
    (371, '生まれる', 'umareru', 'lahir'), (372, '生徒', 'seito', 'siswa'),
    (373, '男', 'otoko', 'laki-laki'), (374, '女の子', 'otoko no ko', 'anak laki-laki'),
    (375, '町', 'machi', 'Kota'), (376, '番号', 'bangou', 'Nomor'),
    (377, '疲れる', 'Tsukareru', 'lelah'), (378, '病気', 'byouki', 'Penyakit, sakit'),
    (379, '病院', 'byouin', 'Rumah sakit'), (380, '痛い', 'itai', 'sakit'),
    (381, '登る', 'noboru', 'naik, mendaki'), (382, '白い', 'shiroi', 'putih'),
    (383, '着く', 'tsuku', 'tiba, sampai'), (384, '着る', 'kiru', 'memakai (baju)'),
    (385, '知る', 'shiru', 'tahu, mengetahui'), (386, '短い', 'mijikai', 'Pendek'),
    (387, '短い髪', 'Mijikai kami', 'Rambut pendek'), (388, '石けん', 'sekken', 'sabun'),
    (389, '砂糖', 'satou', 'gula'), (390, '秋', 'aki', 'musim gugur'),
    (391, '空', 'sora', 'langit'), (392, '窓', 'mado', 'Jendela'),
    (393, '窓を閉める', 'Mado o shimeru', 'Menutup jendela'), (394, '答える', 'kotaeru', 'menjawab'),
    (395, '紅茶', 'koucha', 'teh hitam'), (396, '紙', 'kami', 'kertas'),
    (397, '紙コップ', 'Kami koppu', 'Cangkir kertas'), (398, '細い', 'hosoi', 'kecil, receh, tipis,kurus'),
    (399, '細かいお金', 'Komakai okane', 'Uang kecil / receh'), (400, '終わる', 'owaru', 'selesai')
])

# Page 5
raw_data.extend([
    (401, '結婚', 'kekkon', 'menikah'), (402, '絵', 'e', 'gambar, lukisan'),
    (403, '緑', 'midori', 'hijau'), (404, '緑の野菜', 'Midori no yasai', 'Sayuran hijau'),
    (405, '縦', 'tate', 'vertikal, berdiri'), (406, '置く', 'oku', 'menaruh'),
    (407, '習う', 'narau', 'mempelajari'), (408, '聞く', 'kiku', 'mendengar'),
    (409, '肉', 'niku', 'daging'), (410, '肩', 'kata', 'pundak'),
    (411, '背', 'se', 'pundak'), (412, '背広', 'sebiro', 'jas'),
    (413, '脱ぐ', 'nugu', 'melepas (baju, sepatu)'), (414, '自分', 'jibun', 'saya sendiri'),
    (415, '自動車', 'jidousha', 'mobil'), (416, '自転車', 'jitensha', 'sepeda'),
    (417, '色', 'iro', 'warna'), (418, '英語', 'eigo', 'bahasa inggris'),
    (419, '茶碗', 'chawan', 'Cangkir'), (420, '茶色', 'chairo', 'coklat'),
    (421, '薬', 'kusuri', 'obat'), (422, '行く', 'iku', 'pergi'),
    (423, '西', 'nishi', 'barat'), (424, '要る', 'iru', 'perlu'),
    (425, '見せる', 'miseru', 'Memperlihatkan'), (426, '見る', 'miru', 'melihat, menonton'),
    (427, '覚える', 'oboeru', 'menghafal'), (428, '言う', 'iu', 'berkata'),
    (429, '言葉', 'kotoba', 'kosakata'), (430, '話', 'hanashi', 'Cerita, pembicaraan'),
    (431, '話す', 'hanasu', 'Berbicara'), (432, '話を聞く', 'Hanashi o kiku', 'Mendengarkan cerita'),
    (433, '誕生日', 'tanjoubi', 'ulang tahun'), (434, '豚肉', 'butaniku', 'Daging babi'),
    (435, '買い物', 'kaimono', 'belanja'), (436, '買う', 'kau', 'membeli'),
    (437, '貸す', 'kasu', 'meminjamkan'), (438, '貼る', 'haru', 'Menempel'),
    (439, '質問', 'shitsumon', 'pertanyaan'), (440, '赤い', 'akai', 'merah'),
    (441, '走る', 'hashiru', 'Berlari'), (442, '車', 'kuruma', 'mobil'),
    (443, '軽い', 'karui', 'ringan'), (444, '辞書', 'jisho', 'kamus'),
    (445, '近い', 'chikai', 'dekat'), (446, '近く', 'chikaku', 'dekat'),
    (447, '返す', 'kaesu', 'mengembalikan'), (448, '速い', 'hayai', 'Cepat (kendaraan)'),
    (449, '遅い', 'osoi', 'lambat'), (450, '遊ぶ', 'asobu', 'main'),
    (451, '道', 'michi', 'Jalan'), (452, '違う', 'chigau', 'berbeda, salah'),
    (453, '遠い', 'tooi', 'jauh'), (454, '郵便局', 'yuubinkyoku', 'Kantor pos'),
    (455, '都合', 'tsugou', 'kondisi, keadaan'), (456, '重i', 'omoi', 'berat'),
    (457, '野菜', 'yasai', 'Sayuran'), (458, '野菜がきらい', 'Yasai ga kirai', 'Saya tidak suka sayuran'),
    (459, '鉛筆', 'enpitsu', 'pensil'), (460, '銀行', 'ginkou', 'bank'),
    (461, '長い', 'nagai', 'panjang'), (462, '門', 'mon', 'Gerbang'),
    (463, '閉まる', 'shimaru', 'tertutup'), (464, '閉める', 'shimeru', 'menutup'),
    (465, '開ける', 'akeru', 'membuka'), (466, '降る', 'furu', 'Turun'),
    (467, '階段', 'kaidan', 'tangga'), (468, '隣', 'tonari', 'sebelah'),
    (469, '雑誌', 'zasshi', 'majalah'), (470, '難しい', 'muzukashii', 'Sulit'),
    (471, '雨', 'ame', 'hujan'), (472, '雪', 'yuki', 'Salju'),
    (473, '電気', 'denki', 'listrik'), (474, '電話', 'Denwa', 'telpon'),
    (475, '電話番号', 'Denwa bangou', 'Nomor telepon'), (476, '青い', 'aoi', 'biru'),
    (477, '静か', 'shizuka', 'tenang, sunyi'), (478, '靴', 'kutsu', 'sepatu'),
    (479, '靴下', 'kutsushita', 'kaos kaki'), (480, '靴屋', 'Kutsuya', 'Toko sepatu'),
    (481, '音楽', 'ongaku', 'musik'), (482, '頼む', 'tanomu', 'meminta'),
    (483, '顔', 'kao', 'wajah'), (484, '風', 'kaze', 'angin'),
    (485, '風呂', 'furo', 'Mandi'), (486, '風邪', 'kaze', 'masuk angin'),
    (487, '飛ぶ', 'tobu', 'terbang'), (488, '飛行機', 'hikouki', 'Pesawat terbang'),
    (489, '食べすぎ', 'Tabesugi', 'Terlalu banyak makan'), (490, '食べる', 'taberu', 'makan'),
    (491, '食べ物', 'tabemono', 'makanan'), (492, '食どu', 'shokudou', 'kantin'),
    (493, '飲み物', 'nomimono', 'minuman'), (494, '飲む', 'nomu', 'minum'),
    (495, '飴', 'ame', 'permen'), (496, '駅', 'eki', 'stasiun'),
    (497, '高い', 'takai', 'tinggi, mahal'), (498, '魚', 'sakana', 'ikan'),
    (499, '鳥', 'tori', 'burung'), (500, '鶏肉', 'toriniku', 'daging ayam')
])

# Page 6 (up to 594)
raw_data.extend([
    (501, '黄色', 'kiiro', 'warna kuning'), (502, '黒い', 'kuroi', 'hitam'),
    (503, '鼻', 'hana', 'Hidung'), (504, '決める', 'kimeru', 'menentukan'),
    (505, '止まる', 'tomaru', 'berhenti'), (506, '参る', 'mairu', 'pergi sembahyang'),
    (507, 'これから', 'korekara', 'mulai dari sekarang'), (508, 'ショッピング', 'shoppingu', 'belanja'),
    (509, '手すり', 'tesuri', 'pegangan, batang'), (510, '高等学校', 'koutou gakkou', 'SMA'),
    (511, '僕', 'boku', 'saya ( informal untuk laki-laki)'), (512, '用意する', 'youi suru', 'mempersiapkan'),
    (513, '指輪', 'yubiwa', 'cincin'), (514, 'すごく', 'sugoku', 'sangat'),
    (515, 'まず', 'mazu', 'pertama-tama'), (516, 'プロ', 'puro', 'profesional'),
    (517, '店員', 'ten\'in', 'petugas, pelayan'), (518, 'かまいません', 'kamaimasen', 'tidak apa-apa, boleh'),
    (519, 'それほど～ない', 'sorehodo~nai', 'tidak ~ lebih dari itu'), (520, '大学', 'daigaku', 'universitas'),
    (521, '受ける', 'ukeru', 'menerima'), (522, 'やはり', 'yahari', 'memang betul, ternyata'),
    (523, 'ぬれる', 'nureru', 'basah'), (524, '動物', 'doubutsu', 'binatang'),
    (525, '頭', 'atama', 'kepala'), (526, '準備する', 'junbi suru', 'mempersiapkan'),
    (527, 'スカート', 'sukaato', 'rok'), (528, 'どんどん', 'dondon', 'semakin'),
    (529, 'すっかり', 'sukkari', 'benar-benar'), (530, '大会', 'taikai', 'acara, pesta'),
    (531, '近所', 'kinjo', 'tetangga'), (532, '急ぐ', 'isogu', 'buru-buru, menyegerakan'),
    (533, 'インターネット', 'intaanetto', 'internet'), (534, '口', 'kuchi', 'mulut'),
    (535, '骨', 'hone', 'tulang'), (536, '品物', 'shinamono', 'barang'),
    (537, '増える', 'fueru', 'bertambah'), (538, '新幹線', 'shinkansen', 'kereta peluru, shinkansen'),
    (539, '予習する', 'yoshuu suru', 'mempersiapkan sebelum belajar'), (540, '急に', 'kyuu ni', 'tiba-tiba'),
    (541, '恥ずかしい', 'hazukashii', 'malu'), (542, '始める', 'hajimeru', 'memulai'),
    (543, '心配する', 'shinpaisuru', 'khawatir'), (544, '飾る', 'kazaru', 'memajang'),
    (545, '会話', 'kaiwa', 'percakapan'), (546, 'わけ', 'wake', 'alasan'),
    (547, 'フランス', 'furansu', 'prancis'), (548, 'オーストラリア', 'oosutoraria', 'Australia'),
    (549, 'ほめる', 'homeru', 'memuji'), (550, '田舎', 'inaka', 'pedesaan'),
    (551, '神社', 'jinja', 'sebuah kuil'), (552, 'くださる', 'kudasaru', 'mendapat (dari~)'),
    (553, '釣る', 'tsuru', 'memancing'), (554, '足す', 'tasu', 'menambahkan'),
    (555, '地震', 'jishin', 'gempa bumi'), (556, 'とうとう', 'toutou', 'akhirnya'),
    (557, '届ける', 'todokeru', 'menyampaikan, mengirim'), (558, '相談する', 'soudan suru', 'konsultasi'),
    (559, '中学生', 'chuugakusei', 'siswa sekolah menengah'), (560, '太る', 'futoru', 'menjadi gemuk'),
    (561, '予約する', 'yoyaku suru', 'memesan'), (562, 'やわらかい', 'yawarakai', 'lembut, empuk'),
    (563, '熱', 'netsu', 'panas,demam'), (564, '歯', 'ha', 'gigi'),
    (565, 'セール', 'seeru', 'dijual'), (566, '無くす', 'nakusu', 'menghilangkan'),
    (567, 'ダイエット', 'daietto', 'diet'), (568, '指', 'yubi', 'jari'),
    (569, '続く', 'tsuzuku', 'berlanjut'), (570, '場所', 'basho', 'tempat'),
    (571, '心', 'kokoro', 'hati'), (572, 'ドレス', 'doresu', 'gaun'),
    (573, '下げる', 'sageru', 'menurunkan'), (574, '裏', 'ura', 'bagian belakang'),
    (575, 'ヨーロッパ', 'youroppa', 'Eropa'), (576, '講義', 'kougi', 'perkuliahana'),
    (577, '半額', 'hangaku', 'setengah harga'), (578, '市', '~shi', 'kota'),
    (579, '娘', 'musume', 'seorang gadis'), (580, '幼稚園', 'youchien', 'Taman kanak-kanak'),
    (581, '片付ける', 'katazukeru', 'merapihkan'), (582, '空く', 'aku', 'kosong'),
    (583, '素晴らしい', 'subarashii', 'menakjubkan'), (584, '復習する', 'fukushuu suru', 'mengulang (pelajaran)'),
    (585, '普通', 'futsuu', 'biasa'), (586, '出発する', 'shupatsu suru', 'berangkat'),
    (587, '運ぶ', 'hakobu', 'mengangkut'), (588, '咳', 'seki', 'batuk'),
    (589, '南東', 'nantou', 'tenggara'), (590, '帰り', 'kaeri', 'pulang'),
    (591, '治る', 'naoru', 'menjadi sembuh'), (592, '伝える', 'tsutaeru', 'menyampaikan'),
    (593, '決まる', 'kimaru', 'ditentukan, diputuskan'), (594, '乗り物', 'norimono', 'kendaraan')
])

# Clean and verify
unique = []
seen = set()
for no, w, r, m in raw_data:
    # Heuristic for phrases: contains particles like を, に, へ, が, と or too many spaces
    if any(p in w for p in ['を', 'に', 'へ', 'が', 'と']) or ' ' in r:
         if w not in ['～たち', '～中', '～個', '～回', '～時', '～杯', '～歳', '～階', '女の子', '男の子', '～ヶ月']:
             continue
    
    key = (w, r)
    if key not in seen:
        unique.append({'word': w, 'reading': r, 'meaning': m})
        seen.add(key)

print(f'Total unique base words: {len(unique)}')
# If exactly 594, we are done!
if len(unique) == 594:
    with open('/home/imron/jbook/backend/scripts/n5_594.json', 'w') as f:
        json.dump(unique, f, ensure_ascii=False, indent=2)
    print('Saved to n5_594.json')
else:
    print('Still not 594. Current count:', len(unique))
    # Let's list the first 594 if it's more, or see what's missing.
