# Generated by Django 6.0.2 on 2026-02-11 05:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('structure', models.CharField(max_length=255)),
                ('explanation', models.TextField(help_text='Penjelasan detail dalam Bahasa Indonesia')),
                ('jlpt_level', models.IntegerField(choices=[(5, 'N5'), (4, 'N4'), (3, 'N3'), (2, 'N2'), (1, 'N1')])),
                ('sentences', models.JSONField(default=list, help_text='Contoh kalimat dengan terjemahan Bahasa Indonesia')),
            ],
        ),
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('character', models.CharField(max_length=1)),
                ('meaning', models.CharField(help_text='Arti dalam Bahasa Indonesia', max_length=255)),
                ('onyomi', models.JSONField(default=list)),
                ('kunyomi', models.JSONField(default=list)),
                ('strokes', models.IntegerField()),
                ('jlpt_level', models.IntegerField(choices=[(5, 'N5'), (4, 'N4'), (3, 'N3'), (2, 'N2'), (1, 'N1')])),
                ('examples', models.JSONField(default=list, help_text='List of words using this Kanji with Indonesian meanings')),
            ],
        ),
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=255)),
                ('reading', models.CharField(max_length=255)),
                ('meaning', models.CharField(help_text='Arti kata dalam Bahasa Indonesia', max_length=255)),
                ('jlpt_level', models.IntegerField(choices=[(5, 'N5'), (4, 'N4'), (3, 'N3'), (2, 'N2'), (1, 'N1')], default=5)),
                ('kanji_rel', models.ManyToManyField(blank=True, related_name='vocab', to='content.kanji')),
            ],
        ),
    ]
