# Generated by Django 6.0.2 on 2026-02-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='radical',
            field=models.CharField(blank=True, help_text='Radikal utama', max_length=5, null=True),
        ),
    ]
