# Generated by Django 6.0.2 on 2026-02-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_kanji_radical'),
    ]

    operations = [
        migrations.AddField(
            model_name='grammar',
            name='chapter',
            field=models.IntegerField(default=0, help_text='Bab / Chapter number'),
        ),
    ]
