# Generated by Django 6.0.2 on 2026-02-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocab',
            name='examples',
            field=models.JSONField(default=list, help_text='Contoh kalimat'),
        ),
    ]
