# Generated by Django 6.0.2 on 2026-02-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_vocab_examples"),
    ]

    operations = [
        migrations.AddField(
            model_name="vocab",
            name="furigana",
            field=models.CharField(
                blank=True,
                help_text="Cara baca spesifik dalam Kana (Furigana)",
                max_length=255,
                null=True,
            ),
        ),
    ]
