# Generated by Django 6.0.2 on 2026-03-16 09:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_vocab_furigana"),
    ]

    operations = [
        migrations.CreateModel(
            name="Particle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "character",
                    models.CharField(
                        help_text="Karakter partikel (e.g. は, が, を)", max_length=10
                    ),
                ),
                (
                    "meaning",
                    models.CharField(help_text="Arti/Fungsi singkat", max_length=255),
                ),
                ("explanation", models.TextField(help_text="Penjelasan penggunaan")),
                (
                    "jlpt_level",
                    models.IntegerField(
                        choices=[(5, "N5"), (4, "N4"), (3, "N3"), (2, "N2"), (1, "N1")],
                        default=5,
                    ),
                ),
            ],
        ),
    ]
