# Generated by Django 6.0.2 on 2026-03-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_particle"),
    ]

    operations = [
        migrations.AddField(
            model_name="particle",
            name="sentences",
            field=models.JSONField(
                default=list,
                help_text="Contoh kalimat dengan placeholder ( ) dan terjemahan",
            ),
        ),
    ]
