# Generated by Django 6.0.2 on 2026-03-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_contentsuggestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="vocab",
            name="word_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("noun", "Noun (Kata Benda)"),
                    ("godan_verb", "Godan Verb (Kata Kerja Gol. 1)"),
                    ("ichidan_verb", "Ichidan Verb (Kata Kerja Gol. 2)"),
                    ("suru_verb", "Suru Verb (Kata Kerja Gol. 3)"),
                    ("intransitive_verb", "Intransitive Verb (Intransitif)"),
                    ("transitive_verb", "Transitive Verb (Transitif)"),
                    ("i_adjective", "I-Adjective (Kata Sifat -i)"),
                    ("na_adjective", "Na-Adjective (Kata Sifat -na)"),
                    ("adverb", "Adverb (Kata Keterangan)"),
                    ("particle", "Particle (Partikel)"),
                    ("suffix", "Suffix (Akhiran)"),
                    ("prefix", "Prefix (Awalan)"),
                    ("conjunction", "Conjunction (Kata Sambung)"),
                    ("expression", "Expression (Ungkapan)"),
                    ("other", "Other (Lain-lain)"),
                ],
                help_text="Tipe kata (jenis kata)",
                max_length=20,
                null=True,
            ),
        ),
    ]
