# Generated by Django 6.0.2 on 2026-03-19 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_add_word_type_to_vocab"),
        ("content", "0011_alter_vocab_word_type"),
    ]

    operations = []
