# Generated by Django 6.0.2 on 2026-03-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0012_merge_20260319_0746"),
    ]

    operations = [
        migrations.AddField(
            model_name="kanji",
            name="word_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("noun", "Noun (Kata Benda)"),
                    ("godan", "Godan Verb (Kata Kerja Golongan 1)"),
                    ("ichidan", "Ichidan Verb (Kata Kerja Golongan 2)"),
                    ("suru", "Suru Verb (Kata Kerja Golongan 3)"),
                    ("intransitive", "Intransitive Verb (Kata Kerja Intransitif)"),
                    ("transitive", "Transitive Verb (Kata Kerja Transitif)"),
                    ("i_adj", "I-Adjective (Kata Sifat I)"),
                    ("na_adj", "Na-Adjective (Kata Sifat Na)"),
                    ("adverb", "Adverb (Kata Keterangan)"),
                    ("particle", "Particle (Partikel)"),
                    ("suffix", "Suffix (Akhiran)"),
                    ("other", "Lain-lain"),
                ],
                help_text="Tipe kata utama jika ada",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vocab",
            name="word_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("noun", "Noun (Kata Benda)"),
                    ("godan", "Godan Verb (Kata Kerja Golongan 1)"),
                    ("ichidan", "Ichidan Verb (Kata Kerja Golongan 2)"),
                    ("suru", "Suru Verb (Kata Kerja Golongan 3)"),
                    ("intransitive", "Intransitive Verb (Kata Kerja Intransitif)"),
                    ("transitive", "Transitive Verb (Kata Kerja Transitif)"),
                    ("i_adj", "I-Adjective (Kata Sifat I)"),
                    ("na_adj", "Na-Adjective (Kata Sifat Na)"),
                    ("adverb", "Adverb (Kata Keterangan)"),
                    ("particle", "Particle (Partikel)"),
                    ("suffix", "Suffix (Akhiran)"),
                    ("other", "Lain-lain"),
                ],
                help_text="Tipe kata (e.g. Noun, Godan Verb)",
                max_length=20,
                null=True,
            ),
        ),
    ]
