# Generated by Django 6.0.2 on 2026-05-08 12:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0014_alter_kanji_word_type_alter_vocab_word_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "content",
                    models.TextField(
                        help_text="Isi pengumuman (mendukung teks panjang)"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("info", "Informasi (Biru)"),
                            ("warning", "Peringatan (Kuning)"),
                            ("important", "Penting (Merah)"),
                            ("success", "Sukses (Hijau)"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "show_as_popup",
                    models.BooleanField(
                        default=False,
                        help_text="Jika dicentang, akan muncul sebagai modal popup, jika tidak hanya sebagai banner",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
