# Generated by Django 6.0.2 on 2026-05-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0015_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="priority",
            field=models.IntegerField(
                default=0,
                help_text="Prioritas pengumuman (makin besar makin awal muncul)",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="show_from",
            field=models.DateTimeField(
                blank=True, help_text="Mulai ditampilkan pada", null=True
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="show_until",
            field=models.DateTimeField(
                blank=True, help_text="Selesai ditampilkan pada", null=True
            ),
        ),
    ]
