# Generated by Django 6.0.2 on 2026-05-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0016_announcement_deleted_at_announcement_priority_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kanji",
            name="svg_data",
            field=models.TextField(
                blank=True, help_text="Data mentah file SVG dari KanjiVG", null=True
            ),
        ),
    ]
