# Generated by Django 6.0.2 on 2026-06-02 03:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0017_kanji_svg_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="MinnaQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "book",
                    models.IntegerField(
                        choices=[(1, "Minna no Nihongo 1"), (2, "Minna no Nihongo 2")],
                        help_text="Nomor buku Minna no Nihongo (1 atau 2)",
                    ),
                ),
                ("chapter", models.IntegerField(help_text="Nomor bab dalam buku")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("doukai", "Doukai (Benar/Salah)"),
                            ("fill_blank", "Fill in the Blank"),
                            ("context_match", "Context Match"),
                            ("choice", "Multiple Choice"),
                        ],
                        help_text="Tipe soal latihan",
                        max_length=20,
                    ),
                ),
                (
                    "question_jp",
                    models.TextField(help_text="Kalimat/soal dalam bahasa Jepang"),
                ),
                (
                    "question_id",
                    models.TextField(
                        blank=True,
                        help_text="Konteks soal dalam Bahasa Indonesia (opsional)",
                    ),
                ),
                (
                    "shown_translation",
                    models.TextField(
                        blank=True,
                        help_text="Terjemahan yang ditampilkan (khusus tipe doukai)",
                    ),
                ),
                (
                    "is_translation_correct",
                    models.BooleanField(
                        blank=True,
                        help_text="Apakah shown_translation itu benar? (kunci jawaban doukai)",
                        null=True,
                    ),
                ),
                (
                    "correct_answer",
                    models.CharField(help_text="Jawaban yang benar", max_length=512),
                ),
                (
                    "options",
                    models.JSONField(
                        default=list,
                        help_text="Daftar pilihan jawaban (list of string)",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, help_text="Penjelasan singkat setelah user menjawab"
                    ),
                ),
                (
                    "jlpt_level",
                    models.IntegerField(
                        choices=[(5, "N5"), (4, "N4"), (3, "N3"), (2, "N2"), (1, "N1")],
                        default=5,
                        help_text="Level JLPT yang sesuai",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "grammar",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pola tata bahasa yang terkait",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="minna_questions",
                        to="content.grammar",
                    ),
                ),
                (
                    "vocab",
                    models.ForeignKey(
                        blank=True,
                        help_text="Kosakata yang terkait",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="minna_questions",
                        to="content.vocab",
                    ),
                ),
            ],
            options={
                "ordering": ["book", "chapter", "question_type"],
                "indexes": [
                    models.Index(
                        fields=["book", "chapter"], name="content_min_book_079156_idx"
                    ),
                    models.Index(
                        fields=["question_type", "jlpt_level"],
                        name="content_min_questio_3e88c6_idx",
                    ),
                ],
            },
        ),
    ]
