# Generated by Django 6.0.2 on 2026-06-02 08:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0018_add_minna_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoukaiPassage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Judul cerita (bahasa Indonesia)", max_length=300
                    ),
                ),
                (
                    "text_jp",
                    models.TextField(help_text="Teks cerita dalam bahasa Jepang"),
                ),
                (
                    "text_id",
                    models.TextField(
                        blank=True, help_text="Terjemahan Indonesia (opsional)"
                    ),
                ),
                (
                    "book",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Minna no Nihongo 1"), (2, "Minna no Nihongo 2")],
                        help_text="Dari buku Minna no Nihongo berapa? (opsional)",
                        null=True,
                    ),
                ),
                (
                    "chapter",
                    models.IntegerField(
                        blank=True,
                        help_text="Nomor bab dalam buku (opsional)",
                        null=True,
                    ),
                ),
                (
                    "jlpt_level",
                    models.IntegerField(
                        blank=True,
                        choices=[(5, "N5"), (4, "N4"), (3, "N3"), (2, "N2"), (1, "N1")],
                        help_text="Level JLPT yang sesuai (opsional)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Doukai Passage",
                "verbose_name_plural": "Doukai Passages",
                "ordering": ["book", "chapter", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["book", "chapter"], name="content_dou_book_8cbc98_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DoukaiQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "question_text",
                    models.TextField(
                        help_text="Pernyataan tentang isi cerita (bisa JP atau ID)"
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        help_text="True = pernyataan ini BENAR sesuai isi cerita"
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, help_text="Penjelasan singkat setelah user menjawab"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, help_text="Urutan tampil soal"),
                ),
                (
                    "passage",
                    models.ForeignKey(
                        help_text="Passage cerita yang terkait dengan soal ini",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="content.doukaipassage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doukai Question",
                "verbose_name_plural": "Doukai Questions",
                "ordering": ["order", "id"],
            },
        ),
    ]
