# Generated by Django 6.0.2 on 2026-06-20 06:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0019_doukaipassage_doukaiquestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomModule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "module_type",
                    models.CharField(
                        choices=[
                            ("general", "Umum"),
                            ("dokkai", "Dokkai (Reading)"),
                            ("choukai", "Choukai (Listening)"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "passage",
                    models.TextField(blank=True, help_text="Teks bacaan untuk Dokkai"),
                ),
                (
                    "audio_url",
                    models.CharField(
                        blank=True, help_text="URL Audio untuk Choukai", max_length=512
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="minnaquestion",
            name="is_translation_correct",
        ),
        migrations.RemoveField(
            model_name="minnaquestion",
            name="shown_translation",
        ),
        migrations.AlterField(
            model_name="minnaquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("fill_blank", "Fill in the Blank"),
                    ("context_match", "Context Match"),
                    ("choice", "Multiple Choice"),
                ],
                help_text="Tipe soal latihan",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CustomQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("choice", "Pilihan Ganda"),
                            ("true_false", "Benar/Salah (Maru/Batsu)"),
                            ("fill_blank", "Isian Singkat"),
                        ],
                        default="choice",
                        max_length=20,
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Daftar pilihan jika tipe soal adalah Pilihan Ganda",
                    ),
                ),
                (
                    "correct_answer",
                    models.CharField(
                        help_text="Jawaban benar (Teks atau 'True'/'False')",
                        max_length=512,
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="content.custommodule",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
