# Generated by Django 6.0.7 on 2026-08-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0020_custommodule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vocab",
            name="furigana_map",
            field=models.JSONField(
                default=list,
                help_text="List of furigana segments aligned per character in `word`",
            ),
        ),
    ]
