# Generated by Django 6.0.7 on 2026-09-06 05:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0021_vocab_furigana_map"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="blog/media/%Y/%m/%d/")),
                ("filename", models.CharField(max_length=255)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("document", "Document"),
                            ("other", "Other"),
                        ],
                        default="image",
                        max_length=20,
                    ),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, help_text="Ukuran file dalam bytes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="blog",
            name="excerpt",
            field=models.TextField(
                blank=True, help_text="Cuplikan singkat postingan", null=True
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Gambar utama postingan",
                null=True,
                upload_to="blog/featured/",
            ),
        ),
    ]
