# Generated by Django 6.0.7 on 2026-10-09 11:25

import django.db.models.deletion
from django.db import migrations, models


def copy_legacy_grammar_sentences(apps, schema_editor):
    Grammar = apps.get_model("content", "Grammar")
    GrammarSentence = apps.get_model("content", "GrammarSentence")

    for grammar in Grammar.objects.all().iterator():
        sentences = grammar.sentences if isinstance(grammar.sentences, list) else []
        for order, sentence in enumerate(sentences):
            if not isinstance(sentence, dict):
                continue
            jp = sentence.get("jp") or sentence.get("ja") or ""
            translation = sentence.get("id") or sentence.get("translation") or sentence.get("en") or ""
            if jp or translation:
                GrammarSentence.objects.create(
                    grammar_id=grammar.id,
                    order=order,
                    jp=jp,
                    translation=translation,
                )


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0023_add_vocab_expression_word_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrammarSentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("jp", models.TextField()),
                ("translation", models.TextField()),
                (
                    "expressions",
                    models.ManyToManyField(
                        blank=True, related_name="grammar_sentences", to="content.vocab"
                    ),
                ),
                (
                    "grammar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentence_records",
                        to="content.grammar",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("grammar", "order"),
                        name="unique_grammar_sentence_order",
                    )
                ],
            },
        ),
        migrations.RunPython(copy_legacy_grammar_sentences, migrations.RunPython.noop),
    ]
