# Generated by Django 6.0.2 on 2026-02-19 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_blog'),
        ('learning', '0003_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='grammar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.grammar'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='vocab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.vocab'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='kanji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.kanji'),
        ),
    ]
