# Generated by Django 6.0.2 on 2026-03-16 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_particle"),
        ("learning", "0004_quizattempt_grammar_quizattempt_vocab_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="particle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.particle",
            ),
        ),
    ]
