# Generated by Django 6.0.2 on 2026-03-25 12:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0005_quizattempt_particle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizattempt",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
