# Generated by Django 6.0.2 on 2026-06-02 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0018_add_minna_question"),
        ("learning", "0007_quizattempt_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="minna_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="content.minnaquestion",
            ),
        ),
    ]
