// Kamus Data Radikal Kanji (214 Radikal Kangxi & Varian Populer)
// Berisi nama Jepang, arti dalam Bahasa Indonesia, dan kategori mnemonik

export const RADICAL_DATA = {
    // 1 Stroke
    '一': { name: 'Ichi', meaning: 'Satu / Garis Horizontal', reading: 'いち' },
    '丨': { name: 'Bou / Tatebou', meaning: 'Garis Vertikal / Tongkat', reading: 'ぼう' },
    '丶': { name: 'Ten', meaning: 'Titik / Tetesan', reading: 'てん' },
    '丿': { name: 'No / Harai', meaning: 'Garis Miring / Sabit', reading: 'の' },
    '乙': { name: 'Otsu', meaning: 'Kedua / Belokan', reading: 'おつ' },
    '亅': { name: 'Hanebou', meaning: 'Kait / Cantelan', reading: 'はねぼう' },

    // 2 Strokes
    '二': { name: 'Ni', meaning: 'Dua', reading: 'に' },
    '亠': { name: 'Nabekefuta', meaning: 'Tutup Panci / Atas', reading: 'なべぶた' },
    '人': { name: 'Hito', meaning: 'Orang / Manusia', reading: 'ひと' },
    '亻': { name: 'Ninben', meaning: 'Orang (Sisi Kiri)', reading: 'にんべん' },
    '儿': { name: 'Hitoashi / Hito', meaning: 'Kaki Orang / Berjalan', reading: 'ひとあし' },
    '入': { name: 'Iri / Nyū', meaning: 'Masuk', reading: 'いり' },
    '八': { name: 'Hachi', meaning: 'Delapan / Terbuka', reading: 'はち' },
    '冂': { name: 'Doukamae / Makigamae', meaning: 'Batas Luar / Bingkai Terbuka', reading: 'どうがまえ' },
    '冖': { name: 'Wakanmuri', meaning: 'Penutup / Tudung', reading: 'わかんむり' },
    '冫': { name: 'Nisui', meaning: 'Es / Dingin / Membeku', reading: 'にすい' },
    '几': { name: 'Kinyou / Tsukue', meaning: 'Meja / Bangku', reading: 'きにょう' },
    '凵': { name: 'Kankamae', meaning: 'Wadah Terbuka / Kotak', reading: 'かんがまえ' },
    '刀': { name: 'Katana', meaning: 'Pedang / Pisau', reading: 'かたな' },
    '刂': { name: 'Rittou', meaning: 'Pisau (Sisi Kanan) / Memotong', reading: 'りっとう' },
    '力': { name: 'Chikara', meaning: 'Kekuatan / Tenaga Otot', reading: 'ちから' },
    '勹': { name: 'Tsutsumigamae', meaning: 'Bungkus / Memeluk', reading: 'つつみがまえ' },
    '匕': { name: 'Saji', meaning: 'Sendok / Belati Pendek', reading: 'さじ' },
    '匚': { name: 'Hakogamae', meaning: 'Kotak Penyimpan', reading: 'はこがまえ' },
    '十': { name: 'Jū', meaning: 'Sepuluh / Silang Sempurna', reading: 'じゅう' },
    '卜': { name: 'Boku / Uranai', meaning: 'Ramalan / Tanda Retak', reading: 'ぼく' },
    '卩': { name: 'Fushizukuri', meaning: 'Segel / Orang Berlutut', reading: 'ふしづくり' },
    '厂': { name: 'Gantare', meaning: 'Tebing Curam / Batu Karang', reading: 'がんだれ' },
    '厶': { name: 'Mu', meaning: 'Pribadi / Rahasia', reading: 'む' },
    '又': { name: 'Mata', meaning: 'Lagi / Tangan Kanan', reading: 'また' },

    // 3 Strokes
    '口': { name: 'Kuchi', meaning: 'Mulut / Bukaan / Ucapan', reading: 'くち' },
    '囗': { name: 'Kunigamae', meaning: 'Kurungan / Perbatasan Wilayah', reading: 'くにがまえ' },
    '土': { name: 'Tsuchi', meaning: 'Tanah / Bumi / Lahan', reading: 'つち' },
    '士': { name: 'Samurai / Shi', meaning: 'Cendekiawan / Prajurit', reading: 'さむらい' },
    '夂': { name: 'Fuyugashira', meaning: 'Musim Dingin / Langkah Lambat', reading: 'ふゆがしら' },
    '夕': { name: 'Yū / Yūbe', meaning: 'Sore / Senja / Malam', reading: 'ゆう' },
    '大': { name: 'Dai / Oo', meaning: 'Besar / Luas', reading: 'だい' },
    '女': { name: 'Onna', meaning: 'Wanita / Perempuan', reading: 'おんな' },
    '子': { name: 'Ko', meaning: 'Anak / Keturunan', reading: 'こ' },
    '宀': { name: 'Ukanmuri', meaning: 'Atap / Rumah / Tempat Tinggal', reading: 'うかんむり' },
    '寸': { name: 'Sun', meaning: 'Inci / Ukuran / Aturan Kecil', reading: 'すん' },
    '小': { name: 'Shou / Chiisai', meaning: 'Kecil / Sedikit', reading: 'しょう' },
    '⺌': { name: 'Shoukanmuri', meaning: 'Kecil (Atas)', reading: 'しょうかんむり' },
    '尢': { name: 'Dainoueyashiki', meaning: 'Pincang / Cacat', reading: 'だいのうえやしき' },
    '尸': { name: 'Shikabane', meaning: 'Tubuh / Duduk Melengkung / Mayat', reading: 'しかばね' },
    '屮': { name: 'Tetsukanmuri', meaning: 'Tunas / Tumbuhan Muda', reading: 'てつかんむり' },
    '山': { name: 'Yama', meaning: 'Gunung / Puncak', reading: 'やま' },
    '川': { name: 'Kawa', meaning: 'Sungai / Aliran Air', reading: 'かわ' },
    '巛': { name: 'Magarigawa', meaning: 'Aliran Sungai Melengkung', reading: 'まがりがわ' },
    '工': { name: 'Takumi / Kou', meaning: 'Pekerjaan / Pertukangan / Alat', reading: 'こう' },
    '己': { name: 'Onore / Ko', meaning: 'Diri Sendiri', reading: 'おのれ' },
    '巾': { name: 'Haba / Kinkanmuri', meaning: 'Kain / Handuk / Sorban', reading: 'はば' },
    '干': { name: 'Kan / Hosu', meaning: 'Kering / Perisai', reading: 'かん' },
    '幺': { name: 'Itogashira', meaning: 'Benang Halus / Pendek', reading: 'いとがしら' },
    '广': { name: 'Madare', meaning: 'Rumah Besar / Bangunan Lereng', reading: 'まだれ' },
    '廴': { name: 'Ennyou', meaning: 'Langkah Panjang / Membentang', reading: 'えんにょう' },
    '廾': { name: 'Nijūashi', meaning: 'Dua Tangan Mengangkat', reading: 'にじゅうあし' },
    '弋': { name: 'Shikigamae', meaning: 'Panah / Menembak', reading: 'しきがまえ' },
    '弓': { name: 'Yumi', meaning: 'Busur Panah', reading: 'ゆみ' },
    '彐': { name: 'Keigashira', meaning: 'Moncong Babi / Cakar', reading: 'けいがしら' },
    '彡': { name: 'San Tsukuri', meaning: 'Rambut Halus / Bulu / Pola Indah', reading: 'さんづくり' },
    '彳': { name: 'Gyouninben', meaning: 'Langkah Kaki / Berjalan di Jalan', reading: 'ぎょうにんべん' },
    '⺡': { name: 'Sanzui', meaning: 'Air / Cairan (Sisi Kiri)', reading: 'さんずい' },
    '忄': { name: 'Risshinben', meaning: 'Hati / Perasaan / Pikiran (Sisi Kiri)', reading: 'りっしんべん' },
    '扌': { name: 'Tehen', meaning: 'Tangan / Gerakan Aksi (Sisi Kiri)', reading: 'てへん' },
    '犭': { name: 'Kemonohen', meaning: 'Hewan Liar / Binatang Berbulu', reading: 'けものへん' },
    '艹': { name: 'Kusakanmuri', meaning: 'Rumput / Tumbuhan / Bunga (Atas)', reading: 'くさかんむり' },
    '辶': { name: 'Shinnyou', meaning: 'Jalan / Pergerakan / Bepergian', reading: 'しんにょう' },
    '⻌': { name: 'Shinnyou', meaning: 'Jalan / Pergerakan / Bepergian', reading: 'しんにょう' },
    '门': { name: 'Mongamae', meaning: 'Pintu Gerbang (Ringkas)', reading: 'もんがまえ' },
    '飞': { name: 'Tobu', meaning: 'Terbang', reading: 'とぶ' },
    '饣': { name: 'Shokuhen', meaning: 'Makanan / Makan (Ringkas)', reading: 'しょくへん' },
    '马': { name: 'Uma', meaning: 'Kuda (Ringkas)', reading: 'うま' },

    // 4 Strokes
    '心': { name: 'Kokoro', meaning: 'Hati / Jiwa / Perasaan', reading: 'こころ' },
    '戈': { name: 'Hoko', meaning: 'Tombak / Senjata Perang', reading: 'ほこ' },
    '戶': { name: 'To / Todokoro', meaning: 'Pintu Rumah', reading: 'と' },
    '戸': { name: 'To / Todokoro', meaning: 'Pintu Rumah', reading: 'と' },
    '手': { name: 'Te', meaning: 'Tangan', reading: 'て' },
    '支': { name: 'Shinnyou / Shinyou', meaning: 'Dahan / Cabang / Menyokong', reading: 'しにょう' },
    '攴': { name: 'Bokuzukuri', meaning: 'Pukulan Ringan / Aksi', reading: 'ぼくづくり' },
    '攵': { name: 'Nogibokuzukuri', meaning: 'Pukulan Ringan / Aksi', reading: 'のぎぼくづくり' },
    '文': { name: 'Bun / Moji', meaning: 'Tulisan / Naskah / Pola', reading: 'ぶん' },
    '斗': { name: 'Togamasu', meaning: 'Gayung / Takaran Bintang', reading: 'と' },
    '斤': { name: 'Ono', meaning: 'Kapak / Satuan Berat', reading: 'おの' },
    '方': { name: 'Hou / Kata', meaning: 'Arah / Sisi / Persegi', reading: 'ほう' },
    '无': { name: 'Munyou', meaning: 'Ketiadaan / Tanpa', reading: 'むにょう' },
    '日': { name: 'Hi / Nichi', meaning: 'Matahari / Hari / Terang', reading: 'ひ' },
    '曰': { name: 'Hirabi', meaning: 'Berkata / Bersabda', reading: 'ひらび' },
    '月': { name: 'Tsuki / Nikuzuki', meaning: 'Bulan / Organ Tubuh / Daging', reading: 'つき' },
    '木': { name: 'Ki', meaning: 'Pohon / Kayu', reading: 'き' },
    '欠': { name: 'Akubi', meaning: 'Menguap / Kurang / Haus', reading: 'あくび' },
    '止': { name: 'Tomeru', meaning: 'Berhenti / Jejak Kaki', reading: 'とめる' },
    '歹': { name: 'Gatsuhen', meaning: 'Kematian / Tulang Hancur', reading: 'がつへん' },
    '殳': { name: 'Hokozukuri', meaning: 'Tongkat Pemukul / Senjata', reading: 'ほこづくり' },
    '毋': { name: 'Haha / Nakarigashira', meaning: 'Ibu / Larangan Jangan', reading: 'はは' },
    '比': { name: 'Kuraberu', meaning: 'Membandingkan / Berdampingan', reading: 'くらべる' },
    '毛': { name: 'Ke', meaning: 'Bulu / Rambut', reading: 'け' },
    '氏': { name: 'Uji', meaning: 'Marga / Klan', reading: 'うじ' },
    '气': { name: 'Kigamae', meaning: 'Uap / Gas / Nafas Udara', reading: 'きがまえ' },
    '水': { name: 'Mizu', meaning: 'Air / Cairan', reading: 'みず' },
    '火': { name: 'Hi', meaning: 'Api / Membakar', reading: 'ひ' },
    '灬': { name: 'Rengyou / Rekka', meaning: 'Api di Bawah / Memanggang', reading: 'れんぎょう' },
    '爪': { name: 'Tsume', meaning: 'Cakar / Kuku', reading: 'つめ' },
    '父': { name: 'Chichi', meaning: 'Ayah / Kepala Keluarga', reading: 'ちち' },
    '爻': { name: 'Kou', meaning: 'Garis Silang Ramalan', reading: 'こう' },
    '爿': { name: 'Shouhen', meaning: 'Belahan Kayu / Ranjang', reading: 'しょうへん' },
    '片': { name: 'Kata / Katahen', meaning: 'Potongan / Lembaran Tipis', reading: 'かた' },
    '牙': { name: 'Kiba', meaning: 'Taring / Gigi Runcing', reading: 'きば' },
    '牛': { name: 'Ushi', meaning: 'Sapi / Lembu', reading: 'うし' },
    '犬': { name: 'Inu', meaning: 'Anjing', reading: 'いぬ' },
    '王': { name: 'Ou / Gyoku', meaning: 'Raja / Permata / Giok', reading: 'おう' },

    // 5 Strokes
    '玄': { name: 'Gen', meaning: 'Gelap / Misterius', reading: 'げん' },
    '玉': { name: 'Tama', meaning: 'Permata / Batu Berharga', reading: 'たま' },
    '瓜': { name: 'Uri', meaning: 'Melon / Labu', reading: 'うり' },
    '瓦': { name: 'Kawara', meaning: 'Genteng / Tembikar', reading: 'かわら' },
    '甘': { name: 'Amai', meaning: 'Manis', reading: 'あまい' },
    '生': { name: 'Sei / Iki', meaning: 'Kehidupan / Tumbuh / Lahir', reading: 'せい' },
    '用': { name: 'Mochiiru', meaning: 'Menggunakan / Kegunaan', reading: 'もちいる' },
    '田': { name: 'Ta', meaning: 'Sawah / Ladang', reading: 'た' },
    '疋': { name: 'Hiki', meaning: 'Kaki / Gulungan Kain', reading: 'ひき' },
    '疒': { name: 'Yamaitare', meaning: 'Penyakit / Sakit / Tempat Tidur Pasien', reading: 'やまいたれ' },
    '癶': { name: 'Hatsugashira', meaning: 'Langkah Kaki Berseberangan', reading: 'はつがしら' },
    '白': { name: 'Shiro', meaning: 'Putih / Terang / Jelas', reading: 'しろ' },
    '皮': { name: 'Kawa / Kegawa', meaning: 'Kulit / Lapisan Luar', reading: 'かわ' },
    '皿': { name: 'Sara', meaning: 'Piring / Wadah Makanan', reading: 'さら' },
    '目': { name: 'Me', meaning: 'Mata / Penglihatan', reading: 'め' },
    '矛': { name: 'Hoko', meaning: 'Tombak Panjang', reading: 'ほこ' },
    '矢': { name: 'Ya', meaning: 'Anak Panah', reading: 'や' },
    '石': { name: 'Ishi', meaning: 'Batu / Mineral', reading: 'いし' },
    '示': { name: 'Shimesu', meaning: 'Petunjuk / Altar Pemujaan', reading: 'しめす' },
    '礻': { name: 'Neeshimasu', meaning: 'Dewa / Ibadah / Berkah Spiritual', reading: 'ねへん' },
    '禸': { name: 'Jū', meaning: 'Jejak Hewan Liar', reading: 'じゅう' },
    '禾': { name: 'Nogi', meaning: 'Padi / Bulir Gandum / Tanaman Pangan', reading: 'のぎ' },
    '穴': { name: 'Ana', meaning: 'Lubang / Gua / Rongga', reading: 'あな' },
    '立': { name: 'Tatsu', meaning: 'Berdiri / Tegak', reading: 'たつ' },

    // 6 Strokes
    '竹': { name: 'Take', meaning: 'Bambu', reading: 'たけ' },
    '⺮': { name: 'Takekanmuri', meaning: 'Bambu (Atas)', reading: 'たけかんむり' },
    '米': { name: 'Kome', meaning: 'Beras / Nasi / Makanan Pokok', reading: 'こめ' },
    '糸': { name: 'Ito', meaning: 'Benang / Tekstil / Ikatan Hubungan', reading: 'いと' },
    '糹': { name: 'Itohen', meaning: 'Benang (Sisi Kiri)', reading: 'いとへん' },
    '缶': { name: 'Kama / Hotogi', meaning: 'Kaleng / Guci Tanah Liat', reading: 'ほとぎ' },
    '网': { name: 'Ami', meaning: 'Jaring / Perangkap / Jala', reading: 'あみ' },
    '羊': { name: 'Hitsuji', meaning: 'Domba / Kambing / Kebaikan', reading: 'ひつじ' },
    '羽': { name: 'Hane', meaning: 'Bulu Burung / Sayap', reading: 'はね' },
    '老': { name: 'Oi', meaning: 'Tua / Pengalaman', reading: 'おい' },
    '而': { name: 'Shikashite', meaning: 'Janggut / Menghubungkan', reading: 'しかして' },
    '耒': { name: 'Rabin', meaning: 'Bajak Tanah / Cangkul Pertanian', reading: 'らいすき' },
    '耳': { name: 'Mimi', meaning: 'Telinga / Mendengar', reading: 'みみ' },
    '聿': { name: 'Fude', meaning: 'Kuas Kaligrafi / Menulis', reading: 'ふで' },
    '肉': { name: 'Niku', meaning: 'Daging / Tubuh Manusia', reading: 'にく' },
    '臣': { name: 'Shin / Omi', meaning: 'Menteri / Abdi Negara', reading: 'しん' },
    '自': { name: 'Mizukara / Ji', meaning: 'Diri Sendiri / Hidung', reading: 'みずから' },
    '至': { name: 'Itaru', meaning: 'Tiba / Sampai / Puncak', reading: 'いたる' },
    '臼': { name: 'Usu', meaning: 'Lesung / Menumbuk', reading: 'うす' },
    '舌': { name: 'Shita', meaning: 'Lidah / Rasa / Bicara', reading: 'した' },
    '舛': { name: 'Masu', meaning: 'Berlawanan Arah / Menari', reading: 'ます' },
    '舟': { name: 'Fune', meaning: 'Perahu / Kapal Air', reading: 'ふね' },
    '艮': { name: 'Ushitora', meaning: 'Batas / Berhenti Menatap', reading: 'うしとら' },
    '色': { name: 'Iro', meaning: 'Warna / Rupa / Daya Tarik', reading: 'いろ' },
    '艸': { name: 'Kusa', meaning: 'Tumbuhan / Rerumputan', reading: 'くさ' },
    '虍': { name: 'Toragashira', meaning: 'Kulit Harimau / Belang Gagah', reading: 'とらがしら' },
    '虫': { name: 'Mushi', meaning: 'Serangga / Cacing / Makhluk Kecil', reading: 'むし' },
    '血': { name: 'Chi', meaning: 'Darah', reading: 'ち' },
    '行': { name: 'Gyou / Iku', meaning: 'Berjalan / Bertindak / Perjalanan', reading: 'ぎょう' },
    '衣': { name: 'Koromo', meaning: 'Pakaian / Baju', reading: 'ころも' },
    '衤': { name: 'Koromohen', meaning: 'Pakaian (Sisi Kiri)', reading: 'ころもへん' },
    '西': { name: 'Nishi', meaning: 'Barat / Tutup Anggur', reading: 'にし' },

    // 7+ Strokes
    '見': { name: 'Miru', meaning: 'Melihat / Mengamati', reading: 'みる' },
    '角': { name: 'Tsunohiro / Kado', meaning: 'Tanduk / Sudut', reading: 'つの' },
    '言': { name: 'Koto / Gon', meaning: 'Kata / Bahasa / Berbicara', reading: 'こと' },
    '谷': { name: 'Tani', meaning: 'Lembah / Jurang', reading: 'たに' },
    '豆': { name: 'Mame', meaning: 'Kacang / Wadah Persembahan', reading: 'まめ' },
    '豕': { name: 'Inoko', meaning: 'Babi Hutan', reading: 'いのこ' },
    '豸': { name: 'Mujina', meaning: 'Hewan Melata Tanpa Cakar', reading: 'むじな' },
    '貝': { name: 'Kai', meaning: 'Kerang / Uang Kuno / Harta Benda', reading: 'かい' },
    '赤': { name: 'Aka', meaning: 'Merah / Murni', reading: 'あか' },
    '走': { name: 'Hashiru', meaning: 'Berlari / Melarikan Diri', reading: 'はしる' },
    '足': { name: 'Ashi', meaning: 'Kaki / Cukup', reading: 'あし' },
    '⻊': { name: 'Ashihen', meaning: 'Kaki (Sisi Kiri)', reading: 'あしへん' },
    '身': { name: 'Mi', meaning: 'Tubuh / Badan Hamil', reading: 'み' },
    '車': { name: 'Kuruma', meaning: 'Kendaraan / Kereta Roda', reading: 'くるま' },
    '辛': { name: 'Karai', meaning: 'Pedas / Pahit / Menusuk', reading: 'からい' },
    '辰': { name: 'Shinnotatsu', meaning: 'Naga / Waktu Pagi', reading: 'しんのたつ' },
    '邑': { name: 'Mura / Oozato', meaning: 'Desa / Kota / Wilayah (Kanan 阝)', reading: 'おおざと' },
    '阝': { name: 'Kozatohen / Oozato', meaning: 'Bukit (Kiri) / Kota (Kanan)', reading: 'こざとへん' },
    '酉': { name: 'Hiyomi / Tori', meaning: 'Guci Anggur / Fermentasi', reading: 'とり' },
    '釆': { name: 'Nogome', meaning: 'Memilah / Membagi', reading: 'のごめ' },
    '里': { name: 'Sato', meaning: 'Desa / Satuan Jarak', reading: 'さと' },
    '金': { name: 'Kane / Kin', meaning: 'Logam / Emas / Besi', reading: 'かね' },
    '釒': { name: 'Kanehen', meaning: 'Logam (Sisi Kiri)', reading: 'かねへん' },
    '長': { name: 'Nagai', meaning: 'Panjang / Pemimpin', reading: 'ながい' },
    '門': { name: 'Mon', meaning: 'Pintu Gerbang Besar', reading: 'もん' },
    '阜': { name: 'Kozato', meaning: 'Bukit Tanah / Tangga Alami', reading: 'こざと' },
    '隶': { name: 'Rei', meaning: 'Budak / Menangkap', reading: 'れい' },
    '隹': { name: 'Furutori', meaning: 'Burung Berekor Pendek', reading: 'ふるとり' },
    '雨': { name: 'Ame', meaning: 'Hujan / Cuaca / Langit', reading: 'あめ' },
    '青': { name: 'Ao', meaning: 'Biru / Hijau / Kemurnian', reading: 'あお' },
    '非': { name: 'Arumazu', meaning: 'Bukan / Kesalahan / Sayap Terbuka', reading: 'あらず' },
    '面': { name: 'Men', meaning: 'Wajah / Muka / Permukaan', reading: 'めん' },
    '革': { name: 'Kawa', meaning: 'Kulit Hewan / Revolusi', reading: 'かわ' },
    '音': { name: 'Oto', meaning: 'Suara / Nada / Bunyi', reading: 'おと' },
    '頁': { name: 'Oogai', meaning: 'Kepala / Lembaran Halaman', reading: 'おおがい' },
    '風': { name: 'Kaze', meaning: 'Angin / Kebiasaan', reading: 'かぜ' },
    '飛': { name: 'Tobu', meaning: 'Terbang', reading: 'とぶ' },
    '食': { name: 'Shoku / Taberu', meaning: 'Makanan / Makan', reading: 'しょく' },
    '首': { name: 'Kubi', meaning: 'Leher / Kepala / Pimpinan', reading: 'くび' },
    '香': { name: 'Kaori', meaning: 'Harum / Wangi Biji-bijian', reading: 'かおり' },
    '馬': { name: 'Uma', meaning: 'Kuda', reading: 'うま' },
    '骨': { name: 'Hone', meaning: 'Tulang / Kerangka Struktur', reading: 'ほね' },
    '高': { name: 'Takai', meaning: 'Tinggi / Menara', reading: 'たかい' },
    '髟': { name: 'Kamikanmuri', meaning: 'Rambut Panjang Berombak', reading: 'かみかんむり' },
    '鬥': { name: 'Tatakau', meaning: 'Bertarung / Berkelahi', reading: 'たたかう' },
    '鬯': { name: 'Chou', meaning: 'Arak Sesajen Herbal', reading: 'ちょう' },
    '鬲': { name: 'Kaku', meaning: 'Kuali Kaki Tiga', reading: 'かく' },
    '鬼': { name: 'Oni', meaning: 'Iblis / Monster / Arwah', reading: 'おに' },
    '魚': { name: 'Uo / Sakana', meaning: 'Ikan / Hewan Air', reading: 'さかな' },
    '鳥': { name: 'Tori', meaning: 'Burung Berekor Panjang', reading: 'とり' },
    '鹵': { name: 'Shiroshio', meaning: 'Tambak Garam', reading: 'しろしお' },
    '鹿': { name: 'Shika', meaning: 'Rusa', reading: 'しか' },
    '麥': { name: 'Mugi', meaning: 'Gandum / Jelai', reading: 'むぎ' },
    '麻': { name: 'Asa', meaning: 'Rami / Serat Tanaman', reading: 'あさ' },
    '黃': { name: 'Ki', meaning: 'Kuning', reading: 'き' },
    '黍': { name: 'Kibi', meaning: 'Jewawut / Biji Millet', reading: 'きび' },
    '黑': { name: 'Kuro', meaning: 'Hitam / Jelaga Api', reading: 'くろ' },
    '黒': { name: 'Kuro', meaning: 'Hitam / Jelaga Api', reading: 'くろ' },
    '黹': { name: 'Chisai', meaning: 'Sulaman / Menjahit', reading: 'ちさい' },
    '黽': { name: 'Kaeru', meaning: 'Katak / Kura-kura', reading: 'かえる' },
    '鼎': { name: 'Kanae', meaning: 'Bejana Berkaki Tiga', reading: 'かなえ' },
    '鼓': { name: 'Tsuzumi', meaning: 'Gendang / Tabuhan Musik', reading: 'つづみ' },
    '鼠': { name: 'Nezumi', meaning: 'Tikus', reading: 'ねずみ' },
    '鼻': { name: 'Hana', meaning: 'Hidung', reading: 'はな' },
    '齊': { name: 'Sei', meaning: 'Rata / Seimbang / Seragam', reading: 'せい' },
    '齒': { name: 'Ha', meaning: 'Gigi / Usia', reading: 'は' },
    '歯': { name: 'Ha', meaning: 'Gigi / Usia', reading: 'は' },
    '龍': { name: 'Ryuu', meaning: 'Naga / Kekuatan Suci', reading: 'りゅう' },
    '竜': { name: 'Ryuu', meaning: 'Naga / Kekuatan Suci', reading: 'りゅう' },
    '龜': { name: 'Kame', meaning: 'Kura-kura / Umur Panjang', reading: 'かめ' },
    '亀': { name: 'Kame', meaning: 'Kura-kura / Umur Panjang', reading: 'かめ' },
    '龠': { name: 'Yakukou', meaning: 'Suling Bambu / Nada Musik', reading: 'やく' }
};

/**
 * Mendapatkan informasi radikal lengkap (Nama, Arti, Bacaan) berdasarkan karakter radikal.
 */
export function getRadicalInfo(radicalChar) {
    if (!radicalChar) return null;
    const clean = String(radicalChar).trim();
    const info = RADICAL_DATA[clean];
    if (info) {
        return {
            char: clean,
            name: info.name,
            meaning: info.meaning,
            reading: info.reading
        };
    }
    return {
        char: clean,
        name: clean,
        meaning: 'Radikal Pembentuk',
        reading: ''
    };
}
